/**
 * AUTO-GENERATED by scripts/generate-product-content.mjs — DO NOT EDIT BY HAND.
 * Source of truth: packages/product-content/
 * Regenerate: yarn product:content
 * Check:      yarn product:content:check
 *
 * contentHash=2d7c649da492b988 skillVersion=2 productVersion=0.1.0
 */

export type ProductHelpSectionId = 'overview' | 'memory' | 'config' | 'troubleshooting' | 'agents'

/** UI product-help locale ids (matches app language tags). */
export type ProductHelpLocale = 'en' | 'zh-CN' | 'zh-TW' | 'ja' | 'ko'

export interface ProductHelpSection {
  id: ProductHelpSectionId
  /** i18n key for the tab / nav label */
  titleKey: string
  /** Markdown body for this locale. */
  markdown: string
}

export interface ProductHelpLocalePack {
  description: string
  capabilityMap: string
  sections: readonly ProductHelpSection[]
}

/** App version from root package.json. */
export const HIP_PRODUCT_VERSION = '0.1.0'

/** Content schema version from packages/product-content/meta.json. */
export const PRODUCT_SKILL_VERSION = '2'

/** English defaults (agent-aligned). Prefer getProductHelpPack(lang) in UI. */
export const HIP_SKILL_DESCRIPTION = 'Product help for the hip desktop agent: Chat/Code surfaces, permission modes, Settings, skills, plugins, MCP, memory, agents, CLI, troubleshooting, and local data. Load when the user asks how hip works or how to configure it.'

/** L0 capability map English (agent + default UI). */
export const PRODUCT_CAPABILITY_MAP = `Product facts (hip):
- Version: 0.1.0.
- Desktop workbench agent in the user's project with real file tools and optional sub-agents.
- Surfaces: Code (full workbench) vs Chat (lighter; previewable files → write_file for artifacts).
- On Code only, tool gates (UI labels): chat = read-only; edit = project sandbox (default); full = user-granted whole FS. Chat surface is not Code "edit mode".
- API keys: ~/.hip/config/auth.json (0600 plaintext by design).
- Cross-session memory: off by default (Settings → Memory).
- Local data: ~/.hip/ (config, db, skills, plugins, logs).`

/** English help sections (backward compatible). */
export const PRODUCT_HELP_SECTIONS: readonly ProductHelpSection[] = [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip is a **desktop AI workbench** (Tauri shell + React UI + Node sidecar), product version **0.1.0**. Each UI tab is an independent session. The default product loop is a **Supervisor ReAct** agent that uses tools and may delegate with \`task\` / \`dispatch_agent\` / \`task_batch\` — there is no forced Planner → Coder → Reviewer pipeline on ordinary turns.

This skill is the authoritative product guide for *hip itself*. For ordinary coding work in the user's project, do **not** load this skill.

Answer product questions in the **user's language** (e.g. Chinese if they wrote in Chinese), but keep config paths and identifiers exact.

## Progressive disclosure

- **Level 1** (system prompt Skills list): name + description only
- **Level 2** (this file): overview below, loaded via \`use_skill({ name: "hip" })\`
- **Level 3**: deeper topics in \`references/\` — read those absolute paths with \`read_file\` when needed

If a product detail is not documented here, say so rather than inventing UI labels or config keys.

## Surfaces

| Surface | Intent |
|---------|--------|
| **Code** | Project workbench: file tools, git guidance, MCP catalog, full agent tools |
| **Chat** | Lighter conversation surface: shorter prompt, no git-commit guidance, prefer writing previewable deliverables (\`page.html\`, \`notes.md\`, SVG, etc.) into the workspace for the artifacts panel |

Surface is chosen in the UI; the system prompt already reflects the active surface.

## Permission modes

| Mode | Effect |
|------|--------|
| **edit** (default) | Filesystem tools sandboxed to the project root |
| **chat** | Read-only: no write/edit/script/git mutations |
| **full** | Un-sandboxed filesystem (user-granted); prefer absolute paths |

Path convention in edit/chat: project-root form starting with \`/\` (e.g. \`/src/index.ts\` maps to \`<cwd>/src/index.ts\`). Never invent shell tool names — use \`run_script\` when available.

## Settings (desktop UI)

Typical destinations (wording may vary slightly in the UI):

- **Providers / API keys** — stored as plaintext under \`~/.hip/config/auth.json\` (mode 0600 by design)
- **Memory** — cross-session memory is **off by default**; enable under Settings → Memory (see \`references/memory.md\`)
- **Skills** — enable/disable installed skills (\`hip.toml\` + skill folders)
- **Plugins** — install/enable plugins (skills, agents, MCP, hooks)
- **Agents** — fixed profiles (supervisor / plan / explore / coder) and custom internal or external agents
- **Network policy** — optional allow/deny for outbound tools

## Skills, plugins, MCP

- **Skills**: Claude-format folders with \`SKILL.md\`. Global: \`~/.hip/skills/<id>/\`. Project: \`.hip/skills/<id>/\`. Progressive disclosure: L1 metadata → \`use_skill\` body → \`references/\` + \`assets/\`.
- **Plugins**: under \`~/.hip/plugins/\`; can contribute skills, agents, MCP servers, and hooks. See \`references/agents-and-plugins.md\`.
- **MCP**: configured servers expose tools. In Code surface the system prompt may list a catalog; use \`mcp_search\` then call namespaced tools \`mcp__<server>__<tool>\`.

## Agents & delegation

- Default session agent decides when to use tools or delegate.
- Prefer specialized roster agents when available: **explore** (read-only search), **plan** (design-only), **coder** (implementation).
- Parallel independent sub-tasks → one \`task_batch\` (not sequential \`dispatch_agent\`).
- Explicit workflows / multi-agent handoff exist but are **not** the ordinary product path.
- Depth: \`references/agents-and-plugins.md\`.

## CLI (\`@hip/cli\`)

Attach-only companion to a **running** hip app (shared sidecar + \`~/.hip\` data). Does not start the product sidecar.

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

If the app is not running, CLI fails with \`APP_NOT_RUNNING\`.

## Project guidance files

When present under the project, hip may inject guidance such as \`AGENTS.md\` / \`Claude.md\` / \`.hip\` config. Prefer following those for **project** conventions; this skill is for **product** behavior.

## Level 3 references

After loading this skill, \`use_skill\` returns absolute paths. When the user needs depth:

- Memory enablement, inject, extract, privacy → \`references/memory.md\`
- Local data layout, config files, env overrides → \`references/config-and-data.md\`
- Common failures (no key, CLI not running, empty memory) → \`references/troubleshooting.md\`
- Agents, plugins, MCP wiring → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip memory (Level 3)

Cross-session memory is **disabled by default** (privacy / cost).

## Enable

1. Open **Settings → Memory**.
2. Enable **use** and/or **generate**.
3. Enabling both from a cold install may apply a dogfood preset (shorter idle / extract interval) when gates are still defaults.
4. Ensure a provider API key is configured (Settings → Providers). Extraction needs an API key.

## What is stored

Structured items in SQLite (\`memory_items\`): preferences, conventions, lessons, workflows, profiles — scoped **global**, **project**, or **session**.

**Source of truth is SQLite.** Markdown under \`~/.hip/memories/\` is an export mirror. Project \`MEMORY.md\` / \`.hip/MEMORY.md\` is separate project-notes injection, not auto-imported into SQLite.

## Runtime behavior

| Path | Behavior |
|------|----------|
| **Use** | Core snapshot + per-turn prefetch + \`memory_*\` tools |
| **Generate** | After idle → Phase1 extract → Phase2 consolidate |
| **Incognito** | Session flag: no inject and no extract |
| **Learn now** | Settings control to force extract/consolidate when dogfooding |

Managed sub-agents may get read-only core injection; external ACP agents default off.

## Privacy notes

- Cold defaults: use/generate off
- Hybrid search (optional) may send snippets to embedding providers
- Threat-scan + secret redact on write
- Soft-delete trash + retention
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip config & local data (Level 3)

## Layout (\`~/.hip/\`)

| Path | Purpose |
|------|---------|
| \`~/.hip/config/auth.json\` | Provider API keys (0600 plaintext by design) |
| \`~/.hip/config/hip.toml\` | Global product config (skills, agent loop, langsmith, …) |
| \`~/.hip/config/memory.json\` | Memory feature flags / pipeline knobs |
| \`~/.hip/config/network.json\` | Optional network policy |
| \`~/.hip/config/hip-plugins.json\` | Installed plugins registry |
| \`~/.hip/db/hip.db\` | SQLite sessions, messages, memory items, events |
| \`~/.hip/data/tool-output/\` | Large tool outputs (kept out of the DB) |
| \`~/.hip/logs/\` | Sidecar / shell logs |
| \`~/.hip/skills/\` | Global skills |
| \`~/.hip/plugins/\` | Installed plugins |
| \`~/.hip/memories/\` | Memory markdown mirrors |
| \`~/.hip/builtin-skills/\` | Built-in progressive product skills (e.g. this \`hip\` skill) |
| \`~/.hip/scratch/\`, worktrees | Scratch / parallel worktree helpers |
| \`~/.hip/trash/\` | Product recycle bin (knowledge FS quarantine; sessions soft-delete via SQLite) |

### Recycle bin & soft-delete

| Behavior | Notes |
|----------|--------|
| UI delete (Chat / Code / Knowledge) | Soft-delete → sidebar **Recycle bin** (above History) |
| Retention | Default **7** days; **Settings → General** or \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **Permanent** hard-delete (not the recycle bin) |
| Memory trash | Still **Settings → Memory** (separate retention, default 30 days) |

Project overrides often live under \`<project>/.hip/\` (e.g. \`.hip/skills/\`, \`.hip/hip.toml\`).

## Env / isolation (advanced)

| Variable | Role |
|----------|------|
| \`HIP_DATA_DIR\` | Redirect data/config roots (tests / isolation) |
| \`HIP_SKILLS_DIR\` | Override global skills root |
| \`HIP_PLUGINS_DIR\` | Override plugins root |
| \`HIP_AUTH_PATH\` | Override auth.json path |
| \`HIP_CONFIG_PATH\` | Override hip.toml path |
| \`HIP_MEMORY_CONFIG_PATH\` | Override memory.json path |
| \`LANGSMITH_*\` | Optional LangSmith tracing (also \`[langsmith]\` in hip.toml) |

**Do not** sync \`~/.hip/config/\` to public cloud or public dotfile repos — it may contain API keys.

## Auth model

Keys are entered in the app Settings panel and stored in \`auth.json\`. Desktop app, standalone sidecar, and tests all read from that store. This is intentional plaintext-on-disk with tight file modes — not a keychain migration target.
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip troubleshooting (Level 3)

## No API / model calls work

1. Open **Settings → Providers** and confirm a key is saved.
2. Keys live in \`~/.hip/config/auth.json\` (never print secrets to the user).
3. Restart the app after changing auth outside the UI.
4. Check sidecar logs under \`~/.hip/logs/\`.

## CLI: \`APP_NOT_RUNNING\`

The product CLI attaches to a **running** hip desktop app. Start the app first (\`yarn tauri dev\` or installed app), then \`yarn cli:dev doctor\`.

## Memory list empty after enabling

1. Confirm **Settings → Memory** has **use** and **generate** as intended.
2. Need enough chat turns + API key for extract; try **Learn now**.
3. Status may show \`no_llm\`, \`rate_limited\`, or empty extract — fix key / quota / wait.
4. SQLite is source of truth; stale mirrors under \`~/.hip/memories/\` are not the DB.

## Agent cannot write files

- Permission mode **chat** is read-only.
- Default **edit** is sandboxed to the project root — paths outside fail.
- Use **full** only when the user explicitly granted whole-machine FS access.

## Skill not listed / use_skill fails

- Skill may be disabled in \`hip.toml\` or plugin disabled.
- Project skill \`paths\` globs may exclude the cwd.
- Built-in product skill id is \`hip\` under \`~/.hip/builtin-skills/hip/\`.

## Sidecar / connection issues

- Desktop shell spawns the sidecar and exposes its WS port.
- If the UI cannot connect, restart the app; check \`~/.hip/logs/\`.
- Dev: regenerate sidecar binary wrapper with \`yarn sidecar:dev-bin\` after toolchain changes.

## Stale DMG / build (macOS)

Stale \`rw.*.dmg\` mounts can break \`yarn tauri build\`; remove them and detach \`/Volumes/hip\` if needed.
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip agents, plugins & MCP (Level 3)

## Built-in agent profiles

Typical fixed profiles (enable/disable in Agents UI):

| Profile | Role |
|---------|------|
| **supervisor** | Default orchestrator: tools, commit, scripts, delegation |
| **plan** | Design / planning oriented (narrower write posture depending on config) |
| **explore** | Read-only codebase search |
| **coder** | Implementation-focused with scripts |

Custom **internal** agents: persona prompt + bound model + tool grants.  
**External / ACP** agents: separate process; product memory defaults off unless configured.

Supported ACP presets (Settings → Agents → Add ACP agent): **OpenCode**, **Grok Build** (\`grok agent stdio\`), **Pi**, **Claude Code**, **Codex**. Grok Build uses native ACP (install via \`https://x.ai/cli\`); auth via \`grok login\` or optional \`XAI_API_KEY\`.

ACP agents are **self-managed** for auth and models: hip does not inject its provider API keys into the ACP child process. Use the agent’s own login / ambient env / optional preset \`authEnvVar\` on the agent config.

## Capability matrix (Built-in vs ACP)

hip can run a **built-in** LangGraph agent, an **ACP agent as the session primary**, or **dispatch an ACP agent as a subagent**. Capabilities differ (current product; planned host work noted where relevant):

| Capability | Built-in primary | ACP primary | ACP subagent (dispatch) |
|------------|------------------|-------------|-------------------------|
| hip tools (read / write / run_script / …) | yes | no (agent’s own tools) | no (agent’s own tools) |
| hip Skills / plugin hooks | yes | no | no |
| hip MCP (merged into session) | yes | no (planned: opt-in forward) | no (planned: opt-in forward) |
| Client FS bridge | n/a | no (stub only; real bridge planned) | no (stub only; real bridge planned) |
| dispatch / task / task_batch | yes | no | no |
| Memory inject (cross-session) | yes | no (config flag reserved; prefix planned) | no |
| Memory extract | yes | no | no |
| hip model picker | yes | no (agent configOptions / agent model UI) | no |
| HITL permission | hip tools | ACP \`requestPermission\` | same as ACP primary |
| permissionMode | hip tool gates | auto-resolve safe kinds (read/fetch/other) in chat/edit; else HITL (\`full\` also HITL on ACP path) | parent session mode |

**Takeaway:** choosing ACP as primary is a peer coding agent with its own stack—not hip’s built-in tools/skills/MCP. Subagent dispatch uses the same agent stack; neither primary nor subagent currently gets hip memory inject or hip MCP.

## Delegation tools (main agent)

| Tool | Use |
|------|-----|
| \`task\` | One sub-task (foreground or background) |
| \`dispatch_agent\` | Named roster agent; blocking unless parallel tool-calls |
| \`task_batch\` | **Preferred** for 2+ independent sub-tasks (true parallel) |

Do not claim work ran "in parallel" if only sequential dispatch was used.

## Plugins

- Installed under \`~/.hip/plugins/\`; registry in \`~/.hip/config/hip-plugins.json\`.
- A plugin may ship skills, agents, MCP server configs, and hooks.
- Disable a plugin to drop its contributions from the session.

### Plugin directory structure

Every plugin **must** contain a \`.plugin/plugin.json\` manifest file. Without it, hip will not discover the plugin:

\`\`\`
~/.hip/plugins/<plugin-id>/
  .plugin/
    plugin.json          ← REQUIRED manifest (name, version, skills, etc.)
  skills/                ← optional, referenced by manifest "skills" field
    <skill-id>/
      SKILL.md
\`\`\`

### \`.plugin/plugin.json\` manifest

**Required fields:**

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0"
}
\`\`\`

**Full example** (all optional fields):

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0",
  "id": "my-plugin",
  "description": "A sample hip plugin",
  "author": { "name": "Author Name" },
  "license": "MIT",
  "keywords": ["ai", "tools"],
  "skills": ["./skills/tdd", "./skills/debug"],
  "mcpServers": "./mcp-config.json",
  "agents": "./agents.json",
  "hooks": "./hooks.json"
}
\`\`\`

- \`skills\` — a path (or array of paths) to directories containing \`SKILL.md\` files. Paths are relative to the plugin root and must not use \`..\`.
- \`mcpServers\`, \`agents\`, \`hooks\` — can be specified inline as JSON arrays/objects, or as a path to an external JSON file under the plugin root.

### \`hip-plugins.json\` registry format

The registry maps plugin IDs to absolute paths. Two formats are supported:

**String array format** (recommended for new plugins):
\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

**Legacy object format** (uses \`"dir"\` key):
\`\`\`json
{
  "plugins": [
    { "dir": "/absolute/path/to/plugin", "enabled": true }
  ]
}
\`\`\`

To install a plugin:

1. Clone/download the plugin under \`~/.hip/plugins/<plugin-id>/\`.
2. Ensure \`.plugin/plugin.json\` exists with at least \`name\` and \`version\`.
3. Add the absolute path to \`hip-plugins.json\` → \`plugins\` array (string format).
4. The plugin will be discovered on next session start or after \`plugin:reload\`.

## MCP

- Server configs come from hip.toml / plugin synthesis.
- Code surface may inject a short catalog; discover with \`mcp_search\`.
- Call tools as \`mcp__<server>__<tool>\`.
- Network policy (if configured) may block outbound MCP/web tools.

## Skills scopes

| Scope | Location |
|-------|----------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\` (wins over global same id) |
| plugin | plugin-owned skill dirs |
| builtin product | \`~/.hip/builtin-skills/hip/\` (lowest priority; overridable by same id) |
`,
  }
] as const

/** All UI locales for Settings → Product help. Agent embeds stay English. */
export const PRODUCT_HELP_LOCALES: Record<ProductHelpLocale, ProductHelpLocalePack> = {
  en: {
  description: 'Product help for the hip desktop agent: Chat/Code surfaces, permission modes, Settings, skills, plugins, MCP, memory, agents, CLI, troubleshooting, and local data. Load when the user asks how hip works or how to configure it.',
  capabilityMap: `Product facts (hip):
- Version: 0.1.0.
- Desktop workbench agent in the user's project with real file tools and optional sub-agents.
- Surfaces: Code (full workbench) vs Chat (lighter; previewable files → write_file for artifacts).
- On Code only, tool gates (UI labels): chat = read-only; edit = project sandbox (default); full = user-granted whole FS. Chat surface is not Code "edit mode".
- API keys: ~/.hip/config/auth.json (0600 plaintext by design).
- Cross-session memory: off by default (Settings → Memory).
- Local data: ~/.hip/ (config, db, skills, plugins, logs).`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip is a **desktop AI workbench** (Tauri shell + React UI + Node sidecar), product version **0.1.0**. Each UI tab is an independent session. The default product loop is a **Supervisor ReAct** agent that uses tools and may delegate with \`task\` / \`dispatch_agent\` / \`task_batch\` — there is no forced Planner → Coder → Reviewer pipeline on ordinary turns.

This skill is the authoritative product guide for *hip itself*. For ordinary coding work in the user's project, do **not** load this skill.

Answer product questions in the **user's language** (e.g. Chinese if they wrote in Chinese), but keep config paths and identifiers exact.

## Progressive disclosure

- **Level 1** (system prompt Skills list): name + description only
- **Level 2** (this file): overview below, loaded via \`use_skill({ name: "hip" })\`
- **Level 3**: deeper topics in \`references/\` — read those absolute paths with \`read_file\` when needed

If a product detail is not documented here, say so rather than inventing UI labels or config keys.

## Surfaces

| Surface | Intent |
|---------|--------|
| **Code** | Project workbench: file tools, git guidance, MCP catalog, full agent tools |
| **Chat** | Lighter conversation surface: shorter prompt, no git-commit guidance, prefer writing previewable deliverables (\`page.html\`, \`notes.md\`, SVG, etc.) into the workspace for the artifacts panel |

Surface is chosen in the UI; the system prompt already reflects the active surface.

## Permission modes

| Mode | Effect |
|------|--------|
| **edit** (default) | Filesystem tools sandboxed to the project root |
| **chat** | Read-only: no write/edit/script/git mutations |
| **full** | Un-sandboxed filesystem (user-granted); prefer absolute paths |

Path convention in edit/chat: project-root form starting with \`/\` (e.g. \`/src/index.ts\` maps to \`<cwd>/src/index.ts\`). Never invent shell tool names — use \`run_script\` when available.

## Settings (desktop UI)

Typical destinations (wording may vary slightly in the UI):

- **Providers / API keys** — stored as plaintext under \`~/.hip/config/auth.json\` (mode 0600 by design)
- **Memory** — cross-session memory is **off by default**; enable under Settings → Memory (see \`references/memory.md\`)
- **Skills** — enable/disable installed skills (\`hip.toml\` + skill folders)
- **Plugins** — install/enable plugins (skills, agents, MCP, hooks)
- **Agents** — fixed profiles (supervisor / plan / explore / coder) and custom internal or external agents
- **Network policy** — optional allow/deny for outbound tools

## Skills, plugins, MCP

- **Skills**: Claude-format folders with \`SKILL.md\`. Global: \`~/.hip/skills/<id>/\`. Project: \`.hip/skills/<id>/\`. Progressive disclosure: L1 metadata → \`use_skill\` body → \`references/\` + \`assets/\`.
- **Plugins**: under \`~/.hip/plugins/\`; can contribute skills, agents, MCP servers, and hooks. See \`references/agents-and-plugins.md\`.
- **MCP**: configured servers expose tools. In Code surface the system prompt may list a catalog; use \`mcp_search\` then call namespaced tools \`mcp__<server>__<tool>\`.

## Agents & delegation

- Default session agent decides when to use tools or delegate.
- Prefer specialized roster agents when available: **explore** (read-only search), **plan** (design-only), **coder** (implementation).
- Parallel independent sub-tasks → one \`task_batch\` (not sequential \`dispatch_agent\`).
- Explicit workflows / multi-agent handoff exist but are **not** the ordinary product path.
- Depth: \`references/agents-and-plugins.md\`.

## CLI (\`@hip/cli\`)

Attach-only companion to a **running** hip app (shared sidecar + \`~/.hip\` data). Does not start the product sidecar.

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

If the app is not running, CLI fails with \`APP_NOT_RUNNING\`.

## Project guidance files

When present under the project, hip may inject guidance such as \`AGENTS.md\` / \`Claude.md\` / \`.hip\` config. Prefer following those for **project** conventions; this skill is for **product** behavior.

## Level 3 references

After loading this skill, \`use_skill\` returns absolute paths. When the user needs depth:

- Memory enablement, inject, extract, privacy → \`references/memory.md\`
- Local data layout, config files, env overrides → \`references/config-and-data.md\`
- Common failures (no key, CLI not running, empty memory) → \`references/troubleshooting.md\`
- Agents, plugins, MCP wiring → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip memory (Level 3)

Cross-session memory is **disabled by default** (privacy / cost).

## Enable

1. Open **Settings → Memory**.
2. Enable **use** and/or **generate**.
3. Enabling both from a cold install may apply a dogfood preset (shorter idle / extract interval) when gates are still defaults.
4. Ensure a provider API key is configured (Settings → Providers). Extraction needs an API key.

## What is stored

Structured items in SQLite (\`memory_items\`): preferences, conventions, lessons, workflows, profiles — scoped **global**, **project**, or **session**.

**Source of truth is SQLite.** Markdown under \`~/.hip/memories/\` is an export mirror. Project \`MEMORY.md\` / \`.hip/MEMORY.md\` is separate project-notes injection, not auto-imported into SQLite.

## Runtime behavior

| Path | Behavior |
|------|----------|
| **Use** | Core snapshot + per-turn prefetch + \`memory_*\` tools |
| **Generate** | After idle → Phase1 extract → Phase2 consolidate |
| **Incognito** | Session flag: no inject and no extract |
| **Learn now** | Settings control to force extract/consolidate when dogfooding |

Managed sub-agents may get read-only core injection; external ACP agents default off.

## Privacy notes

- Cold defaults: use/generate off
- Hybrid search (optional) may send snippets to embedding providers
- Threat-scan + secret redact on write
- Soft-delete trash + retention
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip config & local data (Level 3)

## Layout (\`~/.hip/\`)

| Path | Purpose |
|------|---------|
| \`~/.hip/config/auth.json\` | Provider API keys (0600 plaintext by design) |
| \`~/.hip/config/hip.toml\` | Global product config (skills, agent loop, langsmith, …) |
| \`~/.hip/config/memory.json\` | Memory feature flags / pipeline knobs |
| \`~/.hip/config/network.json\` | Optional network policy |
| \`~/.hip/config/hip-plugins.json\` | Installed plugins registry |
| \`~/.hip/db/hip.db\` | SQLite sessions, messages, memory items, events |
| \`~/.hip/data/tool-output/\` | Large tool outputs (kept out of the DB) |
| \`~/.hip/logs/\` | Sidecar / shell logs |
| \`~/.hip/skills/\` | Global skills |
| \`~/.hip/plugins/\` | Installed plugins |
| \`~/.hip/memories/\` | Memory markdown mirrors |
| \`~/.hip/builtin-skills/\` | Built-in progressive product skills (e.g. this \`hip\` skill) |
| \`~/.hip/scratch/\`, worktrees | Scratch / parallel worktree helpers |
| \`~/.hip/trash/\` | Product recycle bin (knowledge FS quarantine; sessions soft-delete via SQLite) |

### Recycle bin & soft-delete

| Behavior | Notes |
|----------|--------|
| UI delete (Chat / Code / Knowledge) | Soft-delete → sidebar **Recycle bin** (above History) |
| Retention | Default **7** days; **Settings → General** or \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **Permanent** hard-delete (not the recycle bin) |
| Memory trash | Still **Settings → Memory** (separate retention, default 30 days) |

Project overrides often live under \`<project>/.hip/\` (e.g. \`.hip/skills/\`, \`.hip/hip.toml\`).

## Env / isolation (advanced)

| Variable | Role |
|----------|------|
| \`HIP_DATA_DIR\` | Redirect data/config roots (tests / isolation) |
| \`HIP_SKILLS_DIR\` | Override global skills root |
| \`HIP_PLUGINS_DIR\` | Override plugins root |
| \`HIP_AUTH_PATH\` | Override auth.json path |
| \`HIP_CONFIG_PATH\` | Override hip.toml path |
| \`HIP_MEMORY_CONFIG_PATH\` | Override memory.json path |
| \`LANGSMITH_*\` | Optional LangSmith tracing (also \`[langsmith]\` in hip.toml) |

**Do not** sync \`~/.hip/config/\` to public cloud or public dotfile repos — it may contain API keys.

## Auth model

Keys are entered in the app Settings panel and stored in \`auth.json\`. Desktop app, standalone sidecar, and tests all read from that store. This is intentional plaintext-on-disk with tight file modes — not a keychain migration target.
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip troubleshooting (Level 3)

## No API / model calls work

1. Open **Settings → Providers** and confirm a key is saved.
2. Keys live in \`~/.hip/config/auth.json\` (never print secrets to the user).
3. Restart the app after changing auth outside the UI.
4. Check sidecar logs under \`~/.hip/logs/\`.

## CLI: \`APP_NOT_RUNNING\`

The product CLI attaches to a **running** hip desktop app. Start the app first (\`yarn tauri dev\` or installed app), then \`yarn cli:dev doctor\`.

## Memory list empty after enabling

1. Confirm **Settings → Memory** has **use** and **generate** as intended.
2. Need enough chat turns + API key for extract; try **Learn now**.
3. Status may show \`no_llm\`, \`rate_limited\`, or empty extract — fix key / quota / wait.
4. SQLite is source of truth; stale mirrors under \`~/.hip/memories/\` are not the DB.

## Agent cannot write files

- Permission mode **chat** is read-only.
- Default **edit** is sandboxed to the project root — paths outside fail.
- Use **full** only when the user explicitly granted whole-machine FS access.

## Skill not listed / use_skill fails

- Skill may be disabled in \`hip.toml\` or plugin disabled.
- Project skill \`paths\` globs may exclude the cwd.
- Built-in product skill id is \`hip\` under \`~/.hip/builtin-skills/hip/\`.

## Sidecar / connection issues

- Desktop shell spawns the sidecar and exposes its WS port.
- If the UI cannot connect, restart the app; check \`~/.hip/logs/\`.
- Dev: regenerate sidecar binary wrapper with \`yarn sidecar:dev-bin\` after toolchain changes.

## Stale DMG / build (macOS)

Stale \`rw.*.dmg\` mounts can break \`yarn tauri build\`; remove them and detach \`/Volumes/hip\` if needed.
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip agents, plugins & MCP (Level 3)

## Built-in agent profiles

Typical fixed profiles (enable/disable in Agents UI):

| Profile | Role |
|---------|------|
| **supervisor** | Default orchestrator: tools, commit, scripts, delegation |
| **plan** | Design / planning oriented (narrower write posture depending on config) |
| **explore** | Read-only codebase search |
| **coder** | Implementation-focused with scripts |

Custom **internal** agents: persona prompt + bound model + tool grants.  
**External / ACP** agents: separate process; product memory defaults off unless configured.

Supported ACP presets (Settings → Agents → Add ACP agent): **OpenCode**, **Grok Build** (\`grok agent stdio\`), **Pi**, **Claude Code**, **Codex**. Grok Build uses native ACP (install via \`https://x.ai/cli\`); auth via \`grok login\` or optional \`XAI_API_KEY\`.

ACP agents are **self-managed** for auth and models: hip does not inject its provider API keys into the ACP child process. Use the agent’s own login / ambient env / optional preset \`authEnvVar\` on the agent config.

## Capability matrix (Built-in vs ACP)

hip can run a **built-in** LangGraph agent, an **ACP agent as the session primary**, or **dispatch an ACP agent as a subagent**. Capabilities differ (current product; planned host work noted where relevant):

| Capability | Built-in primary | ACP primary | ACP subagent (dispatch) |
|------------|------------------|-------------|-------------------------|
| hip tools (read / write / run_script / …) | yes | no (agent’s own tools) | no (agent’s own tools) |
| hip Skills / plugin hooks | yes | no | no |
| hip MCP (merged into session) | yes | no (planned: opt-in forward) | no (planned: opt-in forward) |
| Client FS bridge | n/a | no (stub only; real bridge planned) | no (stub only; real bridge planned) |
| dispatch / task / task_batch | yes | no | no |
| Memory inject (cross-session) | yes | no (config flag reserved; prefix planned) | no |
| Memory extract | yes | no | no |
| hip model picker | yes | no (agent configOptions / agent model UI) | no |
| HITL permission | hip tools | ACP \`requestPermission\` | same as ACP primary |
| permissionMode | hip tool gates | auto-resolve safe kinds (read/fetch/other) in chat/edit; else HITL (\`full\` also HITL on ACP path) | parent session mode |

**Takeaway:** choosing ACP as primary is a peer coding agent with its own stack—not hip’s built-in tools/skills/MCP. Subagent dispatch uses the same agent stack; neither primary nor subagent currently gets hip memory inject or hip MCP.

## Delegation tools (main agent)

| Tool | Use |
|------|-----|
| \`task\` | One sub-task (foreground or background) |
| \`dispatch_agent\` | Named roster agent; blocking unless parallel tool-calls |
| \`task_batch\` | **Preferred** for 2+ independent sub-tasks (true parallel) |

Do not claim work ran "in parallel" if only sequential dispatch was used.

## Plugins

- Installed under \`~/.hip/plugins/\`; registry in \`~/.hip/config/hip-plugins.json\`.
- A plugin may ship skills, agents, MCP server configs, and hooks.
- Disable a plugin to drop its contributions from the session.

### Plugin directory structure

Every plugin **must** contain a \`.plugin/plugin.json\` manifest file. Without it, hip will not discover the plugin:

\`\`\`
~/.hip/plugins/<plugin-id>/
  .plugin/
    plugin.json          ← REQUIRED manifest (name, version, skills, etc.)
  skills/                ← optional, referenced by manifest "skills" field
    <skill-id>/
      SKILL.md
\`\`\`

### \`.plugin/plugin.json\` manifest

**Required fields:**

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0"
}
\`\`\`

**Full example** (all optional fields):

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0",
  "id": "my-plugin",
  "description": "A sample hip plugin",
  "author": { "name": "Author Name" },
  "license": "MIT",
  "keywords": ["ai", "tools"],
  "skills": ["./skills/tdd", "./skills/debug"],
  "mcpServers": "./mcp-config.json",
  "agents": "./agents.json",
  "hooks": "./hooks.json"
}
\`\`\`

- \`skills\` — a path (or array of paths) to directories containing \`SKILL.md\` files. Paths are relative to the plugin root and must not use \`..\`.
- \`mcpServers\`, \`agents\`, \`hooks\` — can be specified inline as JSON arrays/objects, or as a path to an external JSON file under the plugin root.

### \`hip-plugins.json\` registry format

The registry maps plugin IDs to absolute paths. Two formats are supported:

**String array format** (recommended for new plugins):
\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

**Legacy object format** (uses \`"dir"\` key):
\`\`\`json
{
  "plugins": [
    { "dir": "/absolute/path/to/plugin", "enabled": true }
  ]
}
\`\`\`

To install a plugin:

1. Clone/download the plugin under \`~/.hip/plugins/<plugin-id>/\`.
2. Ensure \`.plugin/plugin.json\` exists with at least \`name\` and \`version\`.
3. Add the absolute path to \`hip-plugins.json\` → \`plugins\` array (string format).
4. The plugin will be discovered on next session start or after \`plugin:reload\`.

## MCP

- Server configs come from hip.toml / plugin synthesis.
- Code surface may inject a short catalog; discover with \`mcp_search\`.
- Call tools as \`mcp__<server>__<tool>\`.
- Network policy (if configured) may block outbound MCP/web tools.

## Skills scopes

| Scope | Location |
|-------|----------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\` (wins over global same id) |
| plugin | plugin-owned skill dirs |
| builtin product | \`~/.hip/builtin-skills/hip/\` (lowest priority; overridable by same id) |
`,
  }
  ],
},
  'zh-CN': {
  description: 'hip 桌面智能体产品帮助：Chat/Code 界面、权限模式、设置、技能、插件、MCP、记忆、智能体、CLI、故障排查与本地数据布局。当用户询问 hip 如何工作或如何配置时加载。',
  capabilityMap: `产品要点（hip）：
- 版本：0.1.0。
- 桌面 AI 工作台智能体，在用户项目中使用真实文件工具，并可委派子智能体。
- 界面：Code（完整工作台）与 Chat（更轻；可预览交付物请 write_file 到工件面板）。
- 权限：chat = 只读；edit = 项目沙箱（默认）；full = 用户授权的整机文件系统。
- API 密钥：~/.hip/config/auth.json（按设计为 0600 明文）。
- 跨会话记忆：默认关闭（设置 → 记忆）。
- 本地数据：~/.hip/（配置、数据库、技能、插件、日志）。`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip 是一款**桌面 AI 工作台**（Tauri 壳 + React UI + Node sidecar），产品版本 **0.1.0**。每个 UI 标签页是独立会话。默认产品回路是 **Supervisor ReAct** 智能体：用工具完成工作，并可通过 \`task\` / \`dispatch_agent\` / \`task_batch\` 委派——普通轮次**不会**强制 Planner → Coder → Reviewer 流水线。

本技能是 *hip 产品本身* 的权威指南。用户项目中的普通编码任务**不要**加载本技能。

用**用户的语言**回答产品问题（例如用户用中文提问则用中文答），但配置路径与标识符请保持原文准确。

## 渐进式披露

- **Level 1**（系统提示 Skills 列表）：仅名称 + 描述
- **Level 2**（本文件）：下方概览，通过 \`use_skill({ name: "hip" })\` 加载
- **Level 3**：\`references/\` 中的深入主题——需要时用 \`read_file\` 读绝对路径

若某产品细节未写在此处，请如实说明，不要编造 UI 文案或配置键。

## 界面（Surfaces）

| 界面 | 用途 |
|------|------|
| **Code** | 项目工作台：文件工具、git 指导、MCP 目录、完整智能体工具 |
| **Chat** | 更轻的会话面：更短提示、无 git 提交指导；可预览交付物（\`page.html\`、\`notes.md\`、SVG 等）请 \`write_file\` 到工作区以便工件面板展示 |

界面在 UI 中选择；系统提示会反映当前界面。

## 权限模式

| 模式 | 效果 |
|------|------|
| **edit**（默认） | 文件系统工具限制在项目根沙箱内 |
| **chat** | 只读：不能写/改文件，不能跑脚本 |
| **full** | 未沙箱的文件系统（用户明确授权）；优先绝对路径 |

edit/chat 下的路径约定：以 \`/\` 开头的项目根相对形式（如 \`/src/index.ts\` 映射到 \`<cwd>/src/index.ts\`）。不要发明 shell 工具名——有则用 \`run_script\`。

## 设置（桌面 UI）

常见入口（具体文案可能随 UI 微调）：

- **提供商 / API 密钥** — 明文保存在 \`~/.hip/config/auth.json\`（按设计为 0600）
- **记忆** — 跨会话记忆**默认关闭**；在 设置 → 记忆 开启（见 \`references/memory.md\`）
- **技能** — 启用/禁用已安装技能（\`hip.toml\` + 技能目录）
- **插件** — 安装/启用插件（技能、智能体、MCP、钩子）
- **智能体** — 固定配置（supervisor / plan / explore / coder）与自定义内部或外部智能体
- **网络策略** — 可选的出站工具允许/拒绝

## 技能、插件、MCP

- **技能**：Claude 格式 \`SKILL.md\` 文件夹。全局：\`~/.hip/skills/<id>/\`。项目：\`.hip/skills/<id>/\`。渐进披露：L1 元数据 → \`use_skill\` 正文 → \`references/\` + \`assets/\`。
- **插件**：位于 \`~/.hip/plugins/\`；可贡献技能、智能体、MCP 与钩子。见 \`references/agents-and-plugins.md\`。
- **MCP**：配置的服务器暴露工具。Code 面系统提示可能列出目录；用 \`mcp_search\` 查找，再调用 \`mcp__<server>__<tool>\`。

## 智能体与委派

- 默认会话智能体决定何时用工具或委派。
- 有专用花名册时优先：**explore**（只读搜索）、**plan**（仅设计）、**coder**（带脚本实现）。
- 多个独立子任务 → 一次 \`task_batch\`（不要顺序多个 \`dispatch_agent\`）。
- 显式工作流 / 多智能体 handoff **不是**普通产品路径。
- 深入：\`references/agents-and-plugins.md\`。

## CLI（\`@hip/cli\`）

仅附着到**已运行**的 hip 应用（共享 sidecar 与 \`~/.hip\` 数据）。不会启动产品 sidecar。

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

应用未运行时 CLI 失败并返回 \`APP_NOT_RUNNING\`。

## 项目指导文件

项目中若存在 \`AGENTS.md\` / \`Claude.md\` / \`.hip\` 配置等，hip 可能注入。**项目**约定优先遵循那些文件；本技能描述**产品**行为。

## Level 3 参考

加载本技能后，\`use_skill\` 会返回绝对路径。需要深度时：

- 记忆启用、注入、抽取、隐私 → \`references/memory.md\`
- 本地数据布局、配置、环境变量 → \`references/config-and-data.md\`
- 常见故障（无密钥、CLI 未运行、记忆为空） → \`references/troubleshooting.md\`
- 智能体、插件、MCP → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip 记忆（Level 3）

跨会话记忆**默认关闭**（隐私 / 成本）。

## 启用

1. 打开 **设置 → 记忆**。
2. 开启 **使用** 和/或 **生成**。
3. 冷安装时若同时开启两者，可能在门控仍为默认时应用 dogfood 预设（更短空闲 / 抽取间隔）。
4. 确保已配置提供商 API 密钥（设置 → 提供商）。抽取需要 API 密钥。

## 存什么

SQLite（\`memory_items\`）中的结构化条目：偏好、约定、教训、工作流、档案 — 范围可为 **global**、**project** 或 **session**。

**真相源是 SQLite。** \`~/.hip/memories/\` 下 Markdown 是导出镜像。项目 \`MEMORY.md\` / \`.hip/MEMORY.md\` 是独立的项目笔记注入，不会自动导入 SQLite。

## 运行时行为

| 路径 | 行为 |
|------|------|
| **使用** | 核心快照 + 每轮预取 + \`memory_*\` 工具 |
| **生成** | 空闲后 → Phase1 抽取 → Phase2 巩固 |
| **隐身** | 会话标志：不注入、不抽取 |
| **立即学习** | 设置中的控件，dogfood 时强制抽取/巩固 |

托管子智能体可能只读注入核心；外部 ACP 智能体默认关闭。

## 隐私

- 冷默认：使用/生成关闭
- 混合检索（可选）可能向嵌入服务发送片段
- 写入时威胁扫描 + 密钥脱敏
- 软删除回收站 + 保留期
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip 配置与本地数据（Level 3）

## 布局（\`~/.hip/\`）

| 路径 | 用途 |
|------|------|
| \`~/.hip/config/auth.json\` | 提供商 API 密钥（0600 明文，按设计） |
| \`~/.hip/config/hip.toml\` | 全局产品配置（技能、agent loop、langsmith 等） |
| \`~/.hip/config/memory.json\` | 记忆功能开关 / 流水线参数 |
| \`~/.hip/config/network.json\` | 可选网络策略 |
| \`~/.hip/config/hip-plugins.json\` | 已安装插件注册表 |
| \`~/.hip/db/hip.db\` | SQLite 会话、消息、记忆、事件 |
| \`~/.hip/data/tool-output/\` | 大型工具输出（不进 DB） |
| \`~/.hip/logs/\` | Sidecar / 壳日志 |
| \`~/.hip/skills/\` | 全局技能 |
| \`~/.hip/plugins/\` | 已安装插件 |
| \`~/.hip/memories/\` | 记忆 Markdown 镜像 |
| \`~/.hip/builtin-skills/\` | 内置渐进产品技能（如 \`hip\`） |
| \`~/.hip/scratch/\`、worktrees | 临时区 / 并行 worktree |

项目覆盖常在 \`<project>/.hip/\`（如 \`.hip/skills/\`、\`.hip/hip.toml\`）。

## 环境 / 隔离（进阶）

| 变量 | 作用 |
|------|------|
| \`HIP_DATA_DIR\` | 重定向数据/配置根（测试 / 隔离） |
| \`HIP_SKILLS_DIR\` | 覆盖全局技能根 |
| \`HIP_PLUGINS_DIR\` | 覆盖插件根 |
| \`HIP_AUTH_PATH\` | 覆盖 auth.json 路径 |
| \`HIP_CONFIG_PATH\` | 覆盖 hip.toml 路径 |
| \`HIP_MEMORY_CONFIG_PATH\` | 覆盖 memory.json 路径 |
| \`LANGSMITH_*\` | 可选 LangSmith 追踪（也可用 hip.toml \`[langsmith]\`） |

**不要**把 \`~/.hip/config/\` 同步到公开云或公开 dotfile 仓库——可能含 API 密钥。

## 鉴权模型

密钥在应用设置中填写并写入 \`auth.json\`。桌面应用、独立 sidecar 与测试都从该存储读取。这是有意的磁盘明文 + 紧文件权限，不是钥匙串迁移目标。
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip 故障排查（Level 3）

## API / 模型调用失败

1. 打开 **设置 → 提供商**，确认已保存密钥。
2. 密钥在 \`~/.hip/config/auth.json\`（切勿向用户打印密钥）。
3. 在 UI 外改鉴权后请重启应用。
4. 查看 \`~/.hip/logs/\` 下 sidecar 日志。

## CLI：\`APP_NOT_RUNNING\`

产品 CLI 附着到**正在运行**的 hip 桌面应用。请先启动应用（\`yarn tauri dev\` 或已安装应用），再 \`yarn cli:dev doctor\`。

## 开启记忆后列表仍空

1. 确认 **设置 → 记忆** 中 **使用** / **生成** 符合预期。
2. 需要足够对话轮次 + API 密钥才能抽取；可试 **立即学习**。
3. 状态可能显示 \`no_llm\`、\`rate_limited\` 或空抽取 — 检查密钥 / 配额 / 等待。
4. SQLite 是真相源；\`~/.hip/memories/\` 镜像陈旧不等于库空。

## 智能体无法写文件

- 权限 **chat** 为只读。
- 默认 **edit** 沙箱在项目根 — 根外路径会失败。
- 仅当用户明确授权整机 FS 时使用 **full**。

## 技能未列出 / use_skill 失败

- 可能在 \`hip.toml\` 或插件中被禁用。
- 项目技能 \`paths\` 通配可能排除当前 cwd。
- 内置产品技能 id 为 \`hip\`，目录 \`~/.hip/builtin-skills/hip/\`。

## Sidecar / 连接问题

- 桌面壳启动 sidecar 并暴露其 WebSocket 端口。
- UI 连不上时重启应用；查看 \`~/.hip/logs/\`。
- 开发：工具链变更后用 \`yarn sidecar:dev-bin\` 重新生成 sidecar 包装。

## macOS 构建 DMG 残留

陈旧的 \`rw.*.dmg\` 挂载可能导致 \`yarn tauri build\` 失败；删除它们并卸除 \`/Volumes/hip\`（如有）。
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip 智能体、插件与 MCP（Level 3）

## 内置智能体配置

常见固定配置（在智能体 UI 中启用/禁用）：

| 配置 | 角色 |
|------|------|
| **supervisor** | 默认编排：工具、提交、脚本、委派 |
| **plan** | 偏设计 / 规划（写权限视配置收窄） |
| **explore** | 只读代码库搜索 |
| **coder** | 偏实现，可带脚本 |

自定义 **internal** 智能体：人设提示 + 绑定模型 + 工具授权。  
**外部 / ACP** 智能体：独立进程；产品记忆默认关闭（除非配置开启）。

支持的 ACP preset（设置 → 智能体 → 新增 ACP）：**OpenCode**、**Grok Build**（\`grok agent stdio\`）、**Pi**、**Claude Code**、**Codex**。Grok Build 为原生 ACP（安装见 \`https://x.ai/cli\`）；认证用 \`grok login\` 或可选 \`XAI_API_KEY\`。

ACP 智能体的认证与模型为**自管**：hip **不会**把自身 provider 的 API key 注入 ACP 子进程。请使用智能体自身登录 / 环境变量 / 预设可选的 \`authEnvVar\`。

## 能力矩阵（内置 vs ACP）

hip 可运行 **内置** LangGraph 智能体、将 **ACP 作为会话主智能体**，或 **派发 ACP 作为子智能体**。能力不同（当前产品；规划中的 host 能力另行标注）：

| 能力 | 内置主智能体 | ACP 主智能体 | ACP 子智能体（dispatch） |
|------|--------------|--------------|--------------------------|
| hip 内置工具（read / write / run_script …） | 有 | 无（智能体自有工具） | 无（智能体自有工具） |
| hip Skills / 插件钩子 | 有 | 无 | 无 |
| hip MCP（会话内合并） | 有 | 无（规划：opt-in 转发） | 无（规划：opt-in 转发） |
| 客户端 FS bridge | 不适用 | 无（仅 stub；真实 bridge 规划中） | 无（仅 stub；真实 bridge 规划中） |
| dispatch / task / task_batch | 有 | 无 | 无 |
| 跨会话 Memory 注入 | 有 | 无（配置项预留；前缀规划中） | 无 |
| Memory 抽取 | 有 | 无 | 无 |
| hip 模型选择器 | 有 | 无（用 agent configOptions / 智能体侧模型 UI） | 无 |
| HITL 权限 | hip 工具门禁 | ACP \`requestPermission\` | 同 ACP 主智能体 |
| permissionMode | hip 工具门禁 | chat/edit 下安全 kind（read/fetch/other）自动放行；其余 HITL（ACP 路径上 \`full\` 亦为 HITL） | 继承父会话 mode |

**要点：** 选 ACP 作主智能体时，它是对等的编程智能体栈，**不是** hip 内置工具/技能/MCP。子智能体派发使用同一工具栈；主智能体与子智能体目前均无 hip memory 注入或 hip MCP。

## 委派工具（主智能体）

| 工具 | 用途 |
|------|------|
| \`task\` | 单个子任务（前台或后台） |
| \`dispatch_agent\` | 命名花名册智能体；阻塞，除非同批多个调用 |
| \`task_batch\` | **2+ 独立子任务的首选**（真并行） |

若只用顺序 dispatch，不要声称「并行」完成。

## 插件

- 安装于 \`~/.hip/plugins/\`；注册表在 \`~/.hip/config/hip-plugins.json\`。
- 插件可附带技能、智能体、MCP 配置与钩子。
- 禁用插件会从会话中移除其贡献。

### 插件目录结构

每个插件**必须**包含 \`.plugin/plugin.json\` 清单文件。缺少此文件 hip 无法发现插件：

\`\`\`
~/.hip/plugins/<plugin-id>/
  .plugin/
    plugin.json          ← 必需：清单文件（名称、版本、技能等）
  skills/                ← 可选，由清单中 "skills" 字段引用
    <skill-id>/
      SKILL.md
\`\`\`

### \`.plugin/plugin.json\` 清单

**必填字段：**

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0"
}
\`\`\`

**完整示例**（含所有可选字段）：

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0",
  "id": "my-plugin",
  "description": "一个 hip 插件示例",
  "author": { "name": "作者名" },
  "license": "MIT",
  "keywords": ["ai", "tools"],
  "skills": ["./skills/tdd", "./skills/debug"],
  "mcpServers": "./mcp-config.json",
  "agents": "./agents.json",
  "hooks": "./hooks.json"
}
\`\`\`

- \`skills\` — 指向包含 \`SKILL.md\` 文件的目录的路径（或路径数组）。路径相对于插件根目录，不可使用 \`..\`。
- \`mcpServers\`、\`agents\`、\`hooks\` — 可内联指定为 JSON 数组/对象，或指定为插件根目录下外部 JSON 文件的路径。

### \`hip-plugins.json\` 注册表格式

注册表将插件 ID 映射到绝对路径。支持两种格式：

**字符串数组格式**（新插件推荐使用）：
\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

**旧版对象格式**（使用 \`"dir"\` 键）：
\`\`\`json
{
  "plugins": [
    { "dir": "/absolute/path/to/plugin", "enabled": true }
  ]
}
\`\`\`

安装插件的步骤：

1. 将插件克隆/下载到 \`~/.hip/plugins/<plugin-id>/\`。
2. 确保 \`.plugin/plugin.json\` 存在，至少包含 \`name\` 和 \`version\`。
3. 将绝对路径添加到 \`hip-plugins.json\` → \`plugins\` 数组（字符串格式）。
4. 插件将在下次会话启动或执行 \`plugin:reload\` 后被加载。

## MCP

- 服务器配置来自 hip.toml / 插件合成。
- Code 面可能注入短目录；用 \`mcp_search\` 发现。
- 调用形式：\`mcp__<server>__<tool>\`。
- 若配置了网络策略，可能拦截出站 MCP/web 工具。

## 技能作用域

| 作用域 | 位置 |
|--------|------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\`（同 id 覆盖 global） |
| plugin | 插件自有技能目录 |
| 内置产品 | \`~/.hip/builtin-skills/hip/\`（优先级最低；可被同 id 覆盖） |
`,
  }
  ],
},
  'zh-TW': {
  description: 'hip 桌面智能體產品說明：Chat/Code 介面、權限模式、設定、技能、外掛、MCP、記憶、智能體、CLI、故障排除與本機資料配置。當使用者詢問 hip 如何運作或如何設定時載入。',
  capabilityMap: `產品要點（hip）：
- 版本：0.1.0。
- 桌面 AI 工作台智能體，在使用者專案中使用真實檔案工具，並可委派子智能體。
- 介面：Code（完整工作台）與 Chat（較輕；可預覽交付物請 write_file 到工件面板）。
- 權限：chat = 唯讀；edit = 專案沙箱（預設）；full = 使用者授權的整機檔案系統。
- API 金鑰：~/.hip/config/auth.json（依設計為 0600 明文）。
- 跨工作階段記憶：預設關閉（設定 → 記憶）。
- 本機資料：~/.hip/（設定、資料庫、技能、外掛、日誌）。`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip 是一款**桌面 AI 工作台**（Tauri 殼 + React UI + Node sidecar），產品版本 **0.1.0**。每個 UI 分頁是獨立工作階段。預設產品迴路是 **Supervisor ReAct** 智能體：用工具完成工作，並可透過 \`task\` / \`dispatch_agent\` / \`task_batch\` 委派——一般回合**不會**強制 Planner → Coder → Reviewer 流水線。

本技能是 *hip 產品本身* 的權威指南。使用者專案中的一般編碼任務**不要**載入本技能。

用**使用者的語言**回答產品問題，但設定路徑與識別符請保持原文準確。

## 漸進式揭露

- **Level 1**（系統提示 Skills 列表）：僅名稱 + 描述
- **Level 2**（本檔）：下方概覽，透過 \`use_skill({ name: "hip" })\` 載入
- **Level 3**：\`references/\` 中的深入主題——需要時用 \`read_file\` 讀絕對路徑

若某產品細節未寫在此處，請如實說明，不要編造 UI 文案或設定鍵。

## 介面（Surfaces）

| 介面 | 用途 |
|------|------|
| **Code** | 專案工作台：檔案工具、git 指導、MCP 目錄、完整智能體工具 |
| **Chat** | 較輕的對話面：更短提示、無 git 提交指導；可預覽交付物請 \`write_file\` 到工作區以便工件面板展示 |

介面在 UI 中選擇；系統提示會反映目前介面。

## 權限模式

| 模式 | 效果 |
|------|------|
| **edit**（預設） | 檔案系統工具限制在專案根沙箱內 |
| **chat** | 唯讀：不能寫/改檔案，不能跑腳本 |
| **full** | 未沙箱的檔案系統（使用者明確授權）；優先絕對路徑 |

edit/chat 下的路徑約定：以 \`/\` 開頭的專案根相對形式。不要發明 shell 工具名——有則用 \`run_script\`。

## 設定（桌面 UI）

常見入口（具體文案可能隨 UI 微調）：

- **提供者 / API 金鑰** — 明文保存在 \`~/.hip/config/auth.json\`（依設計為 0600）
- **記憶** — 跨工作階段記憶**預設關閉**；在 設定 → 記憶 開啟（見 \`references/memory.md\`）
- **技能** — 啟用/停用已安裝技能
- **外掛** — 安裝/啟用外掛（技能、智能體、MCP、掛鉤）
- **智能體** — 固定設定（supervisor / plan / explore / coder）與自訂內部或外部智能體
- **網路原則** — 可選的出站工具允許/拒絕

## 技能、外掛、MCP

- **技能**：Claude 格式 \`SKILL.md\`。全域：\`~/.hip/skills/<id>/\`。專案：\`.hip/skills/<id>/\`。
- **外掛**：位於 \`~/.hip/plugins/\`。見 \`references/agents-and-plugins.md\`。
- **MCP**：用 \`mcp_search\` 尋找，再呼叫 \`mcp__<server>__<tool>\`。

## 智能體與委派

- 預設工作階段智能體決定何時用工具或委派。
- 有專用名冊時優先：**explore**、**plan**、**coder**。
- 多個獨立子任務 → 一次 \`task_batch\`。
- 深入：\`references/agents-and-plugins.md\`。

## CLI（\`@hip/cli\`）

僅附著到**已執行**的 hip 應用。應用未執行時 CLI 失敗並回傳 \`APP_NOT_RUNNING\`。

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

## 專案指導檔

專案中的 \`AGENTS.md\` / \`Claude.md\` / \`.hip\` 等描述**專案**約定；本技能描述**產品**行為。

## Level 3 參考

- 記憶 → \`references/memory.md\`
- 本機資料與設定 → \`references/config-and-data.md\`
- 故障排除 → \`references/troubleshooting.md\`
- 智能體與外掛 → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip 記憶（Level 3）

跨工作階段記憶**預設關閉**（隱私 / 成本）。

## 啟用

1. 開啟 **設定 → 記憶**。
2. 開啟 **使用** 和/或 **產生**。
3. 冷安裝時若同時開啟兩者，可能套用 dogfood 預設（更短閒置 / 抽取間隔）。
4. 確保已設定提供者 API 金鑰。抽取需要 API 金鑰。

## 存什麼

SQLite（\`memory_items\`）結構化條目：偏好、約定、教訓、工作流程、檔案 — 範圍 **global** / **project** / **session**。

**真相來源是 SQLite。** \`~/.hip/memories/\` 下 Markdown 是匯出鏡像。

## 執行時行為

| 路徑 | 行為 |
|------|------|
| **使用** | 核心快照 + 每輪預取 + \`memory_*\` 工具 |
| **產生** | 閒置後 → Phase1 抽取 → Phase2 鞏固 |
| **隱身** | 工作階段旗標：不注入、不抽取 |
| **立即學習** | 設定中的控制項，強制抽取/鞏固 |

## 隱私

- 冷預設：使用/產生關閉
- 混合檢索（可選）可能向嵌入服務傳送片段
- 寫入時威脅掃描 + 金鑰脫敏
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip 設定與本機資料（Level 3）

## 配置（\`~/.hip/\`）

| 路徑 | 用途 |
|------|------|
| \`~/.hip/config/auth.json\` | 提供者 API 金鑰（0600 明文，依設計） |
| \`~/.hip/config/hip.toml\` | 全域產品設定 |
| \`~/.hip/config/memory.json\` | 記憶功能開關 |
| \`~/.hip/config/network.json\` | 可選網路原則 |
| \`~/.hip/config/hip-plugins.json\` | 已安裝外掛登錄 |
| \`~/.hip/db/hip.db\` | SQLite 工作階段、訊息、記憶、事件 |
| \`~/.hip/data/tool-output/\` | 大型工具輸出 |
| \`~/.hip/logs/\` | Sidecar / 殼日誌 |
| \`~/.hip/skills/\` | 全域技能 |
| \`~/.hip/plugins/\` | 已安裝外掛 |
| \`~/.hip/memories/\` | 記憶 Markdown 鏡像 |
| \`~/.hip/builtin-skills/\` | 內建漸進產品技能（如 \`hip\`） |

**不要**把 \`~/.hip/config/\` 同步到公開雲或公開 dotfile 倉庫。

## 環境變數（進階）

\`HIP_DATA_DIR\`、\`HIP_SKILLS_DIR\`、\`HIP_PLUGINS_DIR\`、\`HIP_AUTH_PATH\`、\`HIP_CONFIG_PATH\`、\`HIP_MEMORY_CONFIG_PATH\`、\`LANGSMITH_*\`。
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip 故障排除（Level 3）

## API / 模型呼叫失敗

1. 開啟 **設定 → 提供者**，確認已儲存金鑰。
2. 金鑰在 \`~/.hip/config/auth.json\`（切勿向使用者列印金鑰）。
3. 在 UI 外改鑑權後請重新啟動應用。
4. 查看 \`~/.hip/logs/\`。

## CLI：\`APP_NOT_RUNNING\`

請先啟動 hip 桌面應用，再執行 \`yarn cli:dev doctor\`。

## 開啟記憶後列表仍空

確認使用/產生開關、對話輪次、API 金鑰；可試 **立即學習**。SQLite 是真相來源。

## 智能體無法寫檔

- **chat** 唯讀；**edit** 沙箱在專案根；**full** 需使用者明確授權。

## 技能未列出

可能在 \`hip.toml\` 停用；內建產品技能 id 為 \`hip\`（\`~/.hip/builtin-skills/hip/\`）。

## Sidecar 連線

重新啟動應用；開發時工具鏈變更後執行 \`yarn sidecar:dev-bin\`。
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip 智能體、外掛與 MCP（Level 3）

## 內建智能體設定

| 設定 | 角色 |
|------|------|
| **supervisor** | 預設編排：工具、提交、腳本、委派 |
| **plan** | 偏設計 / 規劃 |
| **explore** | 唯讀程式庫搜尋 |
| **coder** | 偏實作，可帶腳本 |

**內部**智能體：人設 + 綁定模型 + 工具授權。  
**外部 / ACP**：獨立行程；產品記憶預設關閉。

支援的 ACP preset（設定 → 智能體 → 新增 ACP）：**OpenCode**、**Grok Build**（\`grok agent stdio\`）、**Pi**、**Claude Code**、**Codex**。Grok Build 為原生 ACP（安裝見 \`https://x.ai/cli\`）；認證用 \`grok login\` 或可選 \`XAI_API_KEY\`。

ACP 智能體的認證與模型為**自管**：hip **不會**將自身 provider 的 API key 注入 ACP 子行程。請使用智能體自身登入 / 環境變數 / 預設可選的 \`authEnvVar\`。

## 能力矩陣（內建 vs ACP）

hip 可執行 **內建** LangGraph 智能體、將 **ACP 作為工作階段主智能體**，或 **派發 ACP 作為子智能體**。能力不同（目前產品；規劃中的 host 能力另行標註）：

| 能力 | 內建主智能體 | ACP 主智能體 | ACP 子智能體（dispatch） |
|------|--------------|--------------|--------------------------|
| hip 內建工具（read / write / run_script …） | 有 | 無（智能體自有工具） | 無（智能體自有工具） |
| hip Skills / 外掛鉤子 | 有 | 無 | 無 |
| hip MCP（工作階段內合併） | 有 | 無（規劃：opt-in 轉發） | 無（規劃：opt-in 轉發） |
| 用戶端 FS bridge | 不適用 | 無（僅 stub；真實 bridge 規劃中） | 無（僅 stub；真實 bridge 規劃中） |
| dispatch / task / task_batch | 有 | 無 | 無 |
| 跨工作階段 Memory 注入 | 有 | 無（設定項預留；前綴規劃中） | 無 |
| Memory 擷取 | 有 | 無 | 無 |
| hip 模型選擇器 | 有 | 無（用 agent configOptions / 智能體側模型 UI） | 無 |
| HITL 權限 | hip 工具門禁 | ACP \`requestPermission\` | 同 ACP 主智能體 |
| permissionMode | hip 工具門禁 | chat/edit 下安全 kind（read/fetch/other）自動放行；其餘 HITL（ACP 路徑上 \`full\` 亦為 HITL） | 繼承父工作階段 mode |

**重點：** 選 ACP 作主智能體時，它是對等的程式智能體堆疊，**不是** hip 內建工具／技能／MCP。子智能體派發使用同一工具堆疊；主智能體與子智能體目前均無 hip memory 注入或 hip MCP。

## 委派工具

| 工具 | 用途 |
|------|------|
| \`task\` | 單個子任務 |
| \`dispatch_agent\` | 名冊智能體（通常阻塞） |
| \`task_batch\` | **2+ 獨立子任務首選**（真平行） |

## 外掛與 MCP

- 外掛：\`~/.hip/plugins/\`；登錄 \`~/.hip/config/hip-plugins.json\`。
- MCP：\`mcp_search\` 後呼叫 \`mcp__<server>__<tool>\`。

## 技能作用域

全域 \`~/.hip/skills/\`、專案 \`.hip/skills/\`、外掛目錄、內建 \`~/.hip/builtin-skills/hip/\`（優先權最低）。
`,
  }
  ],
},
  ja: {
  description: 'hip デスクトップエージェントの製品ヘルプ：Chat/Code サーフェス、権限モード、設定、スキル、プラグイン、MCP、メモリ、エージェント、CLI、トラブルシューティング、ローカルデータ。ユーザーが hip の仕組みや設定方法を尋ねたときに読み込みます。',
  capabilityMap: `製品要点（hip）：
- バージョン：0.1.0。
- ユーザーのプロジェクト内で実ファイルツールと任意のサブエージェントを使うデスクトップ AI ワークベンチエージェント。
- サーフェス：Code（フルワークベンチ）と Chat（軽量；プレビュー可能な成果物は write_file でアーティファクトへ）。
- Code のみのツールゲート（UI ラベル）：chat = 読み取り専用；edit = プロジェクトサンドボックス（既定）；full = ユーザー許可のファイルシステム全体。Chat サーフェスは Code の「編集モード」ではない。
- API キー：~/.hip/config/auth.json（設計上 0600 平文）。
- セッション横断メモリ：既定オフ（設定 → メモリ）。
- ローカルデータ：~/.hip/（設定、DB、スキル、プラグイン、ログ）。`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hipは**デスクトップAIワークベンチ**（Tauriシェル + React UI + Nodeサイドカー）であり、製品バージョンは**0.1.0**です。各UIタブは独立したセッションです。デフォルトの製品ループは、ツールを使用し、\`task\` / \`dispatch_agent\` / \`task_batch\` で委譲を行う可能性のある**Supervisor ReAct**エージェントです。通常のターンで強制的なPlanner → Coder → Reviewerパイプラインはありません。

このスキルは、*hip自体*のための信頼できる製品ガイドです。ユーザーのプロジェクトでの通常のコーディング作業には、このスキルを**ロードしないでください**。

製品に関する質問には**ユーザーの言語**（例：ユーザーが中国語で書いた場合は中国語）で回答しますが、設定パスと識別子は正確に保ちます。

## 段階的な開示

- **レベル1**（システムプロンプトのスキル一覧）：名前と説明のみ
- **レベル2**（このファイル）：以下の概要。\`use_skill({ name: "hip" })\` でロード
- **レベル3**：\`references/\` 内のより深いトピック。必要に応じて \`read_file\` でこれらの絶対パスを読み取ります

製品の詳細がここに文書化されていない場合は、UIラベルや設定キーをでっち上げるのではなく、その旨を伝えてください。

## サーフェス

| サーフェス | 意図 |
|---------|--------|
| **コード** | プロジェクトワークベンチ：ファイルツール、gitガイダンス、MCPカタログ、完全なエージェントツール |
| **チャット** | より軽量な会話サーフェス：短いプロンプト、git-commitガイダンスなし、プレビュー可能な成果物（\`page.html\`、\`notes.md\`、SVGなど）を作業スペースに書き込んでアーティファクトパネルに表示することを推奨 |

サーフェスはUIで選択されます。システムプロンプトは既にアクティブなサーフェスを反映しています。

## 権限モード

| モード | 効果 |
|------|--------|
| **編集**（デフォルト） | ファイルシステムツールはプロジェクトルートにサンドボックス化されます |
| **チャット** | 読み取り専用：書き込み/編集/スクリプト/gitの変更は不可 |
| **フル** | サンドボックス化されていないファイルシステム（ユーザー許可済み）。絶対パスを推奨 |

編集/チャットでのパス規則：\`/\` で始まるプロジェクトルート形式（例：\`/src/index.ts\` は \`<cwd>/src/index.ts\` にマッピングされます）。シェルツール名をでっち上げないでください。利用可能な場合は \`run_script\` を使用してください。

## 設定（デスクトップUI）

一般的な設定項目（UIでの表記は若干異なる場合があります）：

- **プロバイダー / APIキー** — \`~/.hip/config/auth.json\` に平文で保存（設計上、モード0600）
- **メモリ** — セッション間メモリは**デフォルトでオフ**。設定 → メモリで有効化（\`references/memory.md\` を参照）
- **スキル** — インストール済みスキルの有効/無効化（\`hip.toml\` + スキルフォルダ）
- **プラグイン** — プラグインのインストール/有効化（スキル、エージェント、MCP、フック）
- **エージェント** — 固定プロファイル（supervisor / plan / explore / coder）とカスタムの内部または外部エージェント
- **ネットワークポリシー** — アウトバウンドツールのオプションの許可/拒否

## スキル、プラグイン、MCP

- **スキル**：\`SKILL.md\` を含むClaude形式のフォルダ。グローバル：\`~/.hip/skills/<id>/\`。プロジェクト：\`.hip/skills/<id>/\`。段階的な開示：L1メタデータ → \`use_skill\` 本文 → \`references/\` + \`assets/\`。
- **プラグイン**：\`~/.hip/plugins/\` 以下。スキル、エージェント、MCPサーバー、フックを提供できます。\`references/agents-and-plugins.md\` を参照。
- **MCP**：設定されたサーバーがツールを公開します。コードサーフェスでは、システムプロンプトがカタログを一覧表示する場合があります。\`mcp_search\` を使用してから、名前空間付きツール \`mcp__<server>__<tool>\` を呼び出します。

## エージェントと委譲

- デフォルトのセッションエージェントは、ツールを使用するか委譲するかを決定します。
- 利用可能な場合は、専門化されたロスターエージェントを優先します：**explore**（読み取り専用検索）、**plan**（設計のみ）、**coder**（実装）。
- 並列の独立したサブタスク → 1つの \`task_batch\`（順次 \`dispatch_agent\` ではありません）。
- 明示的なワークフロー/マルチエージェントハンドオフは存在しますが、通常の製品パスでは**ありません**。
- 詳細：\`references/agents-and-plugins.md\`。

## CLI（\`@hip/cli\`）

**実行中の** hipアプリにアタッチするだけのコンパニオン（共有サイドカー + \`~/.hip\` データ）。製品サイドカーを起動しません。

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

アプリが実行されていない場合、CLIは \`APP_NOT_RUNNING\` で失敗します。

## プロジェクトガイダンスファイル

プロジェクトに存在する場合、hipは \`AGENTS.md\` / \`Claude.md\` / \`.hip\` 設定などのガイダンスを注入することがあります。**プロジェクト**の規約についてはこれらに従うことを優先します。このスキルは**製品**の動作に関するものです。

## レベル3のリファレンス

このスキルをロードした後、\`use_skill\` は絶対パスを返します。ユーザーが詳細を必要とする場合：

- メモリの有効化、注入、抽出、プライバシー → \`references/memory.md\`
- ローカルデータレイアウト、設定ファイル、環境変数の上書き → \`references/config-and-data.md\`
- 一般的な障害（キーがない、CLIが実行されていない、メモリが空） → \`references/troubleshooting.md\`
- エージェント、プラグイン、MCPの配線 → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip メモリ (レベル 3)

セッションをまたぐメモリは**デフォルトで無効**です（プライバシー/コストのため）。

## 有効化

1. **設定 → メモリ** を開きます。
2. **使用** および/または **生成** を有効にします。
3. クリーンインストールから両方を有効にすると、ゲートがデフォルトのままの場合、ドッグフードプリセット（より短いアイドル時間/抽出間隔）が適用されることがあります。
4. プロバイダのAPIキーが設定されていることを確認します（設定 → プロバイダ）。抽出にはAPIキーが必要です。

## 保存される内容

SQLite（\`memory_items\`）内の構造化アイテム：設定、慣習、教訓、ワークフロー、プロファイル — スコープは**グローバル**、**プロジェクト**、または**セッション**です。

**信頼できる情報源はSQLiteです。** \`~/.hip/memories/\` 配下のMarkdownはエクスポートミラーです。プロジェクトの \`MEMORY.md\` / \`.hip/MEMORY.md\` は別のプロジェクトノート注入であり、SQLiteに自動インポートされません。

## ランタイムの動作

| パス | 動作 |
|------|----------|
| **使用** | コアスナップショット + ターンごとのプリフェッチ + \`memory_*\` ツール |
| **生成** | アイドル後 → フェーズ1抽出 → フェーズ2統合 |
| **シークレットモード** | セッションフラグ：注入も抽出も行わない |
| **今すぐ学習** | ドッグフーディング時に抽出/統合を強制する設定コントロール |

管理対象サブエージェントは読み取り専用のコア注入を受け取る場合があります。外部ACPエージェントはデフォルトでオフです。

## プライバシーに関する注意事項

- コールドデフォルト：使用/生成はオフ
- ハイブリッド検索（オプション）は、スニペットを埋め込みプロバイダに送信する場合があります
- 書き込み時の脅威スキャン + シークレット編集
- ソフトデリートのゴミ箱 + 保持期間
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip 設定 & ローカルデータ (レベル 3)

## レイアウト (\`~/.hip/\`)

| パス | 目的 |
|------|---------|
| \`~/.hip/config/auth.json\` | プロバイダAPIキー (設計上0600のプレーンテキスト) |
| \`~/.hip/config/hip.toml\` | グローバル製品設定 (スキル、エージェントループ、LangSmithなど) |
| \`~/.hip/config/memory.json\` | メモリ機能フラグ / パイプラインノブ |
| \`~/.hip/config/network.json\` | オプションのネットワークポリシー |
| \`~/.hip/config/hip-plugins.json\` | インストール済みプラグインレジストリ |
| \`~/.hip/db/hip.db\` | SQLiteセッション、メッセージ、メモリ項目、イベント |
| \`~/.hip/data/tool-output/\` | 大きなツール出力 (DB外に保持) |
| \`~/.hip/logs/\` | サイドカー / シェルログ |
| \`~/.hip/skills/\` | グローバルスキル |
| \`~/.hip/plugins/\` | インストール済みプラグイン |
| \`~/.hip/memories/\` | メモリマークダウンミラー |
| \`~/.hip/builtin-skills/\` | 組み込みプログレッシブ製品スキル (例: この \`hip\` スキル) |
| \`~/.hip/scratch/\`, worktrees | スクラッチ / 並列ワークツリーヘルパー |
| \`~/.hip/trash/\` | 製品ごみ箱 (知識FS隔離; セッションはSQLite経由でソフトデリート) |

### ごみ箱とソフトデリート

| 動作 | 備考 |
|----------|--------|
| UI削除 (チャット / コード / 知識) | ソフトデリート → サイドバー **ごみ箱** (履歴の上) |
| 保持期間 | デフォルト **7** 日; **設定 → 一般** または \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **完全な** ハードデリート (ごみ箱を経由しない) |
| メモリごみ箱 | 引き続き **設定 → メモリ** (別の保持期間、デフォルト30日) |

プロジェクトのオーバーライドは多くの場合 \`<プロジェクト>/.hip/\` に配置されます (例: \`.hip/skills/\`、\`.hip/hip.toml\`)。

## 環境変数 / 分離 (上級者向け)

| 変数 | 役割 |
|----------|------|
| \`HIP_DATA_DIR\` | データ/設定ルートのリダイレクト (テスト / 分離) |
| \`HIP_SKILLS_DIR\` | グローバルスキルルートのオーバーライド |
| \`HIP_PLUGINS_DIR\` | プラグルートのオーバーライド |
| \`HIP_AUTH_PATH\` | auth.jsonパスのオーバーライド |
| \`HIP_CONFIG_PATH\` | hip.tomlパスのオーバーライド |
| \`HIP_MEMORY_CONFIG_PATH\` | memory.jsonパスのオーバーライド |
| \`LANGSMITH_*\` | オプションのLangSmithトレーシング (\`hip.toml\`の\`[langsmith]\`も参照) |

\`~/.hip/config/\` をパブリッククラウドや公開ドットファイルリポジトリに同期**しないでください** — APIキーが含まれている可能性があります。

## 認証モデル

キーはアプリの設定パネルで入力され、\`auth.json\` に保存されます。デスクトップアプリ、スタンドアロンサイドカー、テストはすべてそのストアから読み取ります。これは意図的な設計で、厳格なファイルモードでディスク上にプレーンテキストとして保存されます — キーチェーンへの移行は対象外です。
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip トラブルシューティング (レベル 3)

## API / モデル呼び出しが動作しない

1. **設定 → プロバイダー** を開き、キーが保存されていることを確認します。
2. キーは \`~/.hip/config/auth.json\` に保存されています（シークレットをユーザーに表示しないでください）。
3. UI 外で認証情報を変更した場合は、アプリを再起動します。
4. \`~/.hip/logs/\` のサイドカーログを確認します。

## CLI: \`APP_NOT_RUNNING\`

製品 CLI は **実行中** の hip デスクトップアプリにアタッチします。最初にアプリを起動し（\`yarn tauri dev\` またはインストール済みアプリ）、その後 \`yarn cli:dev doctor\` を実行します。

## メモリ一覧が有効化後に空になる

1. **設定 → メモリ** で **使用** と **生成** が意図した通りに設定されていることを確認します。
2. 抽出には十分なチャットターン数と API キーが必要です。「今すぐ学習」を試してください。
3. ステータスが \`no_llm\`、\`rate_limited\`、または空の抽出結果を示す場合があります — キー/クォータを修正するか、待機してください。
4. SQLite が信頼できる情報源です。\`~/.hip/memories/\` 配下の古いミラーはデータベースではありません。

## エージェントがファイルを書き込めない

- **チャット** 権限モードは読み取り専用です。
- デフォルトの **編集** モードはプロジェクトルートにサンドボックス化されています — 外部のパスは失敗します。
- **フル** モードは、ユーザーが明示的にマシン全体のファイルシステムアクセスを許可した場合のみ使用します。

## スキルが一覧に表示されない / use_skill が失敗する

- スキルが \`hip.toml\` で無効化されているか、プラグインが無効化されている可能性があります。
- プロジェクトスキルの \`paths\` グロブがカレントワーキングディレクトリを除外している可能性があります。
- 組み込み製品スキル ID は \`hip\` で、\`~/.hip/builtin-skills/hip/\` にあります。

## サイドカー / 接続の問題

- デスクトップシェルがサイドカーを起動し、その WS ポートを公開します。
- UI が接続できない場合は、アプリを再起動し、\`~/.hip/logs/\` を確認します。
- 開発時: ツールチェーン変更後、\`yarn sidecar:dev-bin\` でサイドカーバイナリラッパーを再生成します。

## 古い DMG / ビルド (macOS)

古い \`rw.*.dmg\` マウントが \`yarn tauri build\` を妨げる可能性があります。それらを削除し、必要に応じて \`/Volumes/hip\` をアンマウントしてください。
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip エージェント、プラグイン & MCP (レベル 3)

## 組み込みエージェントプロファイル

典型的な固定プロファイル（エージェントUIで有効化/無効化）：

| プロファイル | 役割 |
|---------|------|
| **supervisor** | デフォルトオーケストレーター：ツール、コミット、スクリプト、委任 |
| **plan** | 設計/計画指向（設定によって書き込み姿勢が狭まる） |
| **explore** | 読み取り専用のコードベース検索 |
| **coder** | スクリプトを使用した実装重視 |

カスタム **内部** エージェント：ペルソナプロンプト + バインドモデル + ツール権限。  
**外部 / ACP** エージェント：別プロセス；設定されていない限り、製品メモリはデフォルトでオフ。

サポートされているACPプリセット（設定 → エージェント → ACPエージェント追加）：**OpenCode**、**Grok Build**（\`grok agent stdio\`）、**Pi**、**Claude Code**、**Codex**。Grok BuildはネイティブACPを使用（\`https://x.ai/cli\`からインストール）；認証は\`grok login\`またはオプションの\`XAI_API_KEY\`を介して行います。

ACPエージェントは認証とモデルを**自己管理**します：hipはACP子プロセスに自身のプロバイダAPIキーを注入しません。エージェント設定で、エージェント自身のログイン/環境変数/オプションのプリセット\`authEnvVar\`を使用します。

## 機能マトリックス（組み込み vs ACP）

hipは**組み込み**のLangGraphエージェント、セッションのプライマリとしての**ACPエージェント**、またはサブエージェントとしての**ACPエージェントのディスパッチ**を実行できます。機能は異なります（現在の製品；関連する計画中のホスト作業は注記）：

| 機能 | 組み込みプライマリ | ACPプライマリ | ACPサブエージェント（ディスパッチ） |
|------------|------------------|-------------|-------------------------|
| hipツール（read / write / run_script / …） | はい | いいえ（エージェント自身のツール） | いいえ（エージェント自身のツール） |
| hipスキル / プラグインフック | はい | いいえ | いいえ |
| hip MCP（セッションにマージ） | はい | いいえ（計画中：オプトイン転送） | いいえ（計画中：オプトイン転送） |
| クライアントFSブリッジ | 該当なし | いいえ（スタブのみ；実際のブリッジは計画中） | いいえ（スタブのみ；実際のブリッジは計画中） |
| dispatch / task / task_batch | はい | いいえ | いいえ |
| メモリ注入（セッション間） | はい | いいえ（設定フラグは予約済み；プレフィックスは計画中） | いいえ |
| メモリ抽出 | はい | いいえ | いいえ |
| hipモデルピッカー | はい | いいえ（エージェントconfigOptions / エージェントモデルUI） | いいえ |
| HITL許可 | hipツール | ACP \`requestPermission\` | ACPプライマリと同じ |
| permissionMode | hipツールゲート | チャット/編集で安全な種類（read/fetch/other）を自動解決；それ以外はHITL（\`full\`はACPパスでもHITL） | 親セッションモード |

**要点：** ACPをプライマリとして選択することは、独自のスタックを持つピアコーディングエージェントであり、hipの組み込みツール/スキル/MCPではありません。サブエージェントディスパッチは同じエージェントスタックを使用します；プライマリもサブエージェントも現在、hipメモリ注入またはhip MCPを取得しません。

## 委任ツール（メインエージェント）

| ツール | 使用法 |
|------|-----|
| \`task\` | 1つのサブタスク（フォアグラウンドまたはバックグラウンド） |
| \`dispatch_agent\` | 名前付きロスターエージェント；並列ツール呼び出しがない限りブロッキング |
| \`task_batch\` | **推奨** 2つ以上の独立したサブタスク（真の並列処理） |

逐次ディスパッチのみを使用した場合、作業が「並列に」実行されたと主張しないでください。

## プラグイン

- \`~/.hip/plugins/\` の下にインストール；レジストリは \`~/.hip/config/hip-plugins.json\`。
- プラグインはスキル、エージェント、MCPサーバー設定、フックを提供できます。
- プラグインを無効にすると、その貢献がセッションから削除されます。

## MCP

- サーバー設定は hip.toml / プラグイン合成から取得されます。
- コードサーフェスは短いカタログを注入する場合があります；\`mcp_search\` で発見します。
- ツールは \`mcp__<server>__<tool>\` として呼び出します。
- ネットワークポリシー（設定されている場合）は、アウトバウンドMCP/Webツールをブロックする場合があります。

## スキルスコープ

| スコープ | 場所 |
|-------|------|
| グローバル | \`~/.hip/skills/<id>/\` |
| プロジェクト | \`.hip/skills/<id>/\`（同じIDのグローバルより優先） |
| プラグイン | プラグイン所有のスキルディレクトリ |
| 組み込み製品 | \`~/.hip/builtin-skills/hip/\`（最低優先度；同じIDで上書き可能） |
`,
  }
  ],
},
  ko: {
  description: 'hip 데스크톱 에이전트 제품 도움말: Chat/Code 서피스, 권한 모드, 설정, 스킬, 플러그인, MCP, 메모리, 에이전트, CLI, 문제 해결, 로컬 데이터. 사용자가 hip 작동 방식이나 설정 방법을 물을 때 로드합니다.',
  capabilityMap: `제품 요점(hip):
- 버전: 0.1.0.
- 사용자 프로젝트에서 실제 파일 도구와 선택적 서브 에이전트를 쓰는 데스크톱 AI 워크벤치 에이전트.
- 서피스: Code(전체 워크벤치) vs Chat(가벼움; 미리보기 가능한 결과물은 write_file로 아티팩트).
- Code 전용 도구 게이트(UI 라벨): chat = 읽기 전용; edit = 프로젝트 샌드박스(기본); full = 사용자가 허용한 전체 파일시스템. Chat 서피스는 Code의 "편집 모드"가 아님.
- API 키: ~/.hip/config/auth.json (설계상 0600 평문).
- 세션 간 메모리: 기본 꺼짐(설정 → 메모리).
- 로컬 데이터: ~/.hip/(설정, DB, 스킬, 플러그인, 로그).`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip은 **데스크톱 AI 작업대**(Tauri 셸 + React UI + Node 사이드카)이며, 제품 버전은 **0.1.0**입니다. 각 UI 탭은 독립적인 세션입니다. 기본 제품 루프는 도구를 사용하고 \`task\` / \`dispatch_agent\` / \`task_batch\`로 위임할 수 있는 **Supervisor ReAct** 에이전트입니다. 일반적인 턴에서 Planner → Coder → Reviewer 파이프라인이 강제되지 않습니다.

이 스킬은 *hip 자체*에 대한 권위 있는 제품 가이드입니다. 사용자 프로젝트의 일반 코딩 작업에는 이 스킬을 **로드하지 마십시오**.

제품 질문은 **사용자의 언어**(예: 사용자가 중국어로 작성한 경우 중국어)로 답변하되, 설정 경로와 식별자는 정확하게 유지하십시오.

## 점진적 공개

- **레벨 1**(시스템 프롬프트 Skills 목록): 이름 + 설명만
- **레벨 2**(이 파일): 아래 개요, \`use_skill({ name: "hip" })\`를 통해 로드됨
- **레벨 3**: \`references/\`의 심화 주제 — 필요 시 \`read_file\`로 해당 절대 경로를 읽으십시오

제품 세부 사항이 여기에 문서화되지 않은 경우, UI 레이블이나 설정 키를 임의로 만들지 말고 그렇게 명시하십시오.

## 표면

| 표면 | 의도 |
|---------|--------|
| **Code** | 프로젝트 작업대: 파일 도구, git 안내, MCP 카탈로그, 전체 에이전트 도구 |
| **Chat** | 가벼운 대화 표면: 짧은 프롬프트, git-커밋 안내 없음, 아티팩트 패널을 위해 미리보기 가능한 결과물(\`page.html\`, \`notes.md\`, SVG 등)을 작업 공간에 작성 선호 |

표면은 UI에서 선택되며, 시스템 프롬프트는 이미 활성 표면을 반영합니다.

## 권한 모드

| 모드 | 효과 |
|------|--------|
| **edit** (기본값) | 파일시스템 도구가 프로젝트 루트로 샌드박싱됨 |
| **chat** | 읽기 전용: 쓰기/편집/스크립트/git 변형 없음 |
| **full** | 샌드박스 해제된 파일시스템(사용자 승인); 절대 경로 선호 |

edit/chat의 경로 규칙: \`/\`로 시작하는 프로젝트 루트 형식(예: \`/src/index.ts\`는 \`<cwd>/src/index.ts\`에 매핑). 셸 도구 이름을 임의로 만들지 마십시오 — 사용 가능한 경우 \`run_script\`를 사용하십시오.

## 설정 (데스크톱 UI)

일반적인 위치(UI에서 표현이 약간 다를 수 있음):

- **Providers / API keys** — \`~/.hip/config/auth.json\`에 일반 텍스트로 저장됨(설계상 모드 0600)
- **Memory** — 교차 세션 메모리는 **기본적으로 꺼져 있음**; Settings → Memory에서 활성화(\`references/memory.md\` 참조)
- **Skills** — 설치된 스킬 활성화/비활성화(\`hip.toml\` + 스킬 폴더)
- **Plugins** — 플러그인 설치/활성화(스킬, 에이전트, MCP, 훅)
- **Agents** — 고정 프로필(supervisor / plan / explore / coder) 및 사용자 정의 내부 또는 외부 에이전트
- **Network policy** — 아웃바운드 도구에 대한 선택적 허용/거부

## 스킬, 플러그인, MCP

- **스킬**: \`SKILL.md\`가 포함된 Claude 형식 폴더. 전역: \`~/.hip/skills/<id>/\`. 프로젝트: \`.hip/skills/<id>/\`. 점진적 공개: L1 메타데이터 → \`use_skill\` 본문 → \`references/\` + \`assets/\`.
- **플러그인**: \`~/.hip/plugins/\` 아래; 스킬, 에이전트, MCP 서버 및 훅을 제공할 수 있음. \`references/agents-and-plugins.md\` 참조.
- **MCP**: 구성된 서버가 도구를 노출함. Code 표면에서 시스템 프롬프트가 카탈로그를 나열할 수 있음; \`mcp_search\`를 사용한 후 네임스페이스된 도구 \`mcp__<server>__<tool>\`을 호출하십시오.

## 에이전트 및 위임

- 기본 세션 에이전트는 도구 사용 또는 위임 시기를 결정합니다.
- 사용 가능한 경우 전문 로스터 에이전트를 선호하십시오: **explore**(읽기 전용 검색), **plan**(설계 전용), **coder**(구현).
- 병렬 독립 하위 작업 → 하나의 \`task_batch\`(순차적 \`dispatch_agent\` 아님).
- 명시적 워크플로우 / 다중 에이전트 핸드오프가 존재하지만 **일반적인 제품 경로는 아닙니다**.
- 심화: \`references/agents-and-plugins.md\`.

## CLI (\`@hip/cli\`)

**실행 중인** hip 앱에 연결 전용 동반자(공유 사이드카 + \`~/.hip\` 데이터). 제품 사이드카를 시작하지 않습니다.

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

앱이 실행 중이지 않으면 CLI는 \`APP_NOT_RUNNING\`으로 실패합니다.

## 프로젝트 안내 파일

프로젝트 아래에 있을 때, hip은 \`AGENTS.md\` / \`Claude.md\` / \`.hip\` 설정과 같은 안내를 주입할 수 있습니다. **프로젝트** 규칙에 대해서는 이를 따르는 것을 선호하십시오; 이 스킬은 **제품** 동작을 위한 것입니다.

## 레벨 3 참조

이 스킬을 로드한 후, \`use_skill\`은 절대 경로를 반환합니다. 사용자가 심화가 필요할 때:

- 메모리 활성화, 주입, 추출, 개인정보 → \`references/memory.md\`
- 로컬 데이터 레이아웃, 설정 파일, 환경 변수 재정의 → \`references/config-and-data.md\`
- 일반적인 실패(키 없음, CLI 실행 중 아님, 빈 메모리) → \`references/troubleshooting.md\`
- 에이전트, 플러그인, MCP 연결 → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip 메모리 (레벨 3)

세션 간 메모리는 **기본적으로 비활성화**되어 있습니다 (개인정보 보호 / 비용).

## 활성화

1. **설정 → 메모리**를 엽니다.
2. **사용** 및/또는 **생성**을 활성화합니다.
3. 처음 설치 상태에서 둘 다 활성화하면 게이트가 기본값일 때 도그푸드 프리셋(더 짧은 유휴/추출 간격)이 적용될 수 있습니다.
4. 제공자 API 키가 설정되어 있는지 확인합니다 (설정 → 제공자). 추출에는 API 키가 필요합니다.

## 저장되는 내용

SQLite의 구조화된 항목(\`memory_items\`): 선호도, 규칙, 학습 내용, 워크플로우, 프로필 — 범위는 **전역**, **프로젝트**, 또는 **세션**입니다.

**진실 공급원은 SQLite입니다.** \`~/.hip/memories/\` 아래의 Markdown은 내보내기 미러입니다. 프로젝트 \`MEMORY.md\` / \`.hip/MEMORY.md\`는 별도의 프로젝트 노트 주입이며, SQLite로 자동 가져오지 않습니다.

## 런타임 동작

| 경로 | 동작 |
|------|----------|
| **사용** | 코어 스냅샷 + 턴별 프리페치 + \`memory_*\` 도구 |
| **생성** | 유휴 후 → 1단계 추출 → 2단계 통합 |
| **시크릿 모드** | 세션 플래그: 주입 및 추출 없음 |
| **지금 학습** | 도그푸딩 시 추출/통합을 강제하는 설정 제어 |

관리되는 하위 에이전트는 읽기 전용 코어 주입을 받을 수 있으며, 외부 ACP 에이전트는 기본적으로 꺼져 있습니다.

## 개인정보 보호 참고 사항

- 기본 설정: 사용/생성 꺼짐
- 하이브리드 검색(선택 사항)은 임베딩 제공자에게 스니펫을 보낼 수 있음
- 쓰기 시 위협 검사 + 비밀 정보 편집
- 소프트 삭제 휴지통 + 보존 기간
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip 설정 및 로컬 데이터 (레벨 3)

## 디렉터리 구조 (\`~/.hip/\`)

| 경로 | 용도 |
|------|---------|
| \`~/.hip/config/auth.json\` | 제공자 API 키 (설계상 0600 일반 텍스트) |
| \`~/.hip/config/hip.toml\` | 전역 제품 설정 (스킬, 에이전트 루프, LangSmith 등) |
| \`~/.hip/config/memory.json\` | 메모리 기능 플래그 / 파이프라인 설정값 |
| \`~/.hip/config/network.json\` | 선택적 네트워크 정책 |
| \`~/.hip/config/hip-plugins.json\` | 설치된 플러그인 레지스트리 |
| \`~/.hip/db/hip.db\` | SQLite 세션, 메시지, 메모리 항목, 이벤트 |
| \`~/.hip/data/tool-output/\` | 대용량 도구 출력 (DB 외부 보관) |
| \`~/.hip/logs/\` | 사이드카 / 셸 로그 |
| \`~/.hip/skills/\` | 전역 스킬 |
| \`~/.hip/plugins/\` | 설치된 플러그인 |
| \`~/.hip/memories/\` | 메모리 마크다운 미러 |
| \`~/.hip/builtin-skills/\` | 내장 점진적 제품 스킬 (예: 이 \`hip\` 스킬) |
| \`~/.hip/scratch/\`, 작업 트리 | 임시 / 병렬 작업 트리 도우미 |
| \`~/.hip/trash/\` | 제품 휴지통 (지식 FS 격리, 세션은 SQLite를 통해 소프트 삭제) |

### 휴지통 및 소프트 삭제

| 동작 | 참고 |
|----------|--------|
| UI 삭제 (채팅 / 코드 / 지식) | 소프트 삭제 → 사이드바 **휴지통** (기록 위) |
| 보관 기간 | 기본 **7**일, **설정 → 일반** 또는 \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **영구** 하드 삭제 (휴지통 미사용) |
| 메모리 휴지통 | 여전히 **설정 → 메모리** (별도 보관 기간, 기본 30일) |

프로젝트 재정의는 보통 \`<프로젝트>/.hip/\` 아래에 위치합니다 (예: \`.hip/skills/\`, \`.hip/hip.toml\`).

## 환경 변수 / 격리 (고급)

| 변수 | 역할 |
|----------|------|
| \`HIP_DATA_DIR\` | 데이터/설정 루트 리디렉션 (테스트 / 격리) |
| \`HIP_SKILLS_DIR\` | 전역 스킬 루트 재정의 |
| \`HIP_PLUGINS_DIR\` | 플러그인 루트 재정의 |
| \`HIP_AUTH_PATH\` | auth.json 경로 재정의 |
| \`HIP_CONFIG_PATH\` | hip.toml 경로 재정의 |
| \`HIP_MEMORY_CONFIG_PATH\` | memory.json 경로 재정의 |
| \`LANGSMITH_*\` | 선택적 LangSmith 추적 (hip.toml의 \`[langsmith]\`도 함께) |

**\`~/.hip/config/\`를** 퍼블릭 클라우드나 공개 dotfile 저장소에 동기화하지 마십시오 — API 키가 포함될 수 있습니다.

## 인증 모델

키는 앱 설정 패널에서 입력되며 \`auth.json\`에 저장됩니다. 데스크톱 앱, 독립형 사이드카, 테스트 모두 해당 저장소에서 읽습니다. 이는 의도적인 일반 텍스트 디스크 저장 방식이며 엄격한 파일 모드가 적용됩니다 — 키체인 마이그레이션 대상이 아닙니다.
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip 문제 해결 (레벨 3)

## API / 모델 호출이 작동하지 않음

1. **설정 → 제공자**를 열고 키가 저장되어 있는지 확인하세요.
2. 키는 \`~/.hip/config/auth.json\`에 저장됩니다 (사용자에게 비밀을 출력하지 않음).
3. UI 외부에서 인증을 변경한 후 앱을 다시 시작하세요.
4. \`~/.hip/logs/\`에서 사이드카 로그를 확인하세요.

## CLI: \`APP_NOT_RUNNING\`

제품 CLI는 **실행 중인** hip 데스크톱 앱에 연결됩니다. 먼저 앱을 시작한 후(\`yarn tauri dev\` 또는 설치된 앱), \`yarn cli:dev doctor\`를 실행하세요.

## 메모리 목록 활성화 후 비어 있음

1. **설정 → 메모리**에서 **사용** 및 **생성**이 의도한 대로 설정되어 있는지 확인하세요.
2. 추출을 위해 충분한 채팅 횟수와 API 키가 필요합니다. **지금 학습**을 시도해보세요.
3. 상태가 \`no_llm\`, \`rate_limited\` 또는 빈 추출을 표시할 수 있습니다 — 키/할당량을 수정하거나 대기하세요.
4. SQLite가 진실 공급원이며, \`~/.hip/memories/\` 아래의 오래된 미러는 DB가 아닙니다.

## 에이전트가 파일을 쓸 수 없음

- **채팅** 권한 모드는 읽기 전용입니다.
- 기본 **편집** 모드는 프로젝트 루트로 샌드박싱됩니다 — 외부 경로는 실패합니다.
- 사용자가 명시적으로 전체 시스템 파일 시스템 접근을 허용한 경우에만 **전체**를 사용하세요.

## 스킬이 나열되지 않음 / use_skill 실패

- \`hip.toml\`에서 스킬이 비활성화되었거나 플러그인이 비활성화되었을 수 있습니다.
- 프로젝트 스킬 \`paths\` 글로브가 현재 작업 디렉토리를 제외할 수 있습니다.
- 내장 제품 스킬 ID는 \`~/.hip/builtin-skills/hip/\` 아래의 \`hip\`입니다.

## 사이드카 / 연결 문제

- 데스크톱 셸이 사이드카를 생성하고 WS 포트를 노출합니다.
- UI가 연결할 수 없는 경우 앱을 다시 시작하고 \`~/.hip/logs/\`를 확인하세요.
- 개발: 도구 체인 변경 후 \`yarn sidecar:dev-bin\`으로 사이드카 바이너리 래퍼를 다시 생성하세요.

## 오래된 DMG / 빌드 (macOS)

오래된 \`rw.*.dmg\` 마운트가 \`yarn tauri build\`를 중단시킬 수 있습니다. 필요한 경우 이를 제거하고 \`/Volumes/hip\`을 분리하세요.
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip 에이전트, 플러그인 및 MCP (레벨 3)

## 내장 에이전트 프로필

일반적인 고정 프로필 (에이전트 UI에서 활성화/비활성화):

| 프로필 | 역할 |
|---------|------|
| **supervisor** | 기본 오케스트레이터: 도구, 커밋, 스크립트, 위임 |
| **plan** | 설계/계획 중심 (구성에 따라 더 좁은 쓰기 자세) |
| **explore** | 읽기 전용 코드베이스 검색 |
| **coder** | 스크립트를 사용한 구현 중심 |

사용자 정의 **내부** 에이전트: 페르소나 프롬프트 + 바인딩된 모델 + 도구 권한.  
**외부 / ACP** 에이전트: 별도 프로세스; 구성되지 않으면 제품 메모리는 기본적으로 꺼짐.

지원되는 ACP 프리셋 (설정 → 에이전트 → ACP 에이전트 추가): **OpenCode**, **Grok Build** (\`grok agent stdio\`), **Pi**, **Claude Code**, **Codex**. Grok Build는 네이티브 ACP 사용 (\`https://x.ai/cli\` 통해 설치); \`grok login\` 또는 선택적 \`XAI_API_KEY\`를 통해 인증.

ACP 에이전트는 인증 및 모델에 대해 **자체 관리**됩니다: hip은 ACP 하위 프로세스에 자체 제공자 API 키를 주입하지 않습니다. 에이전트 구성에서 에이전트 자체 로그인 / 환경 변수 / 선택적 프리셋 \`authEnvVar\`를 사용하세요.

## 기능 매트릭스 (내장 vs ACP)

hip은 **내장** LangGraph 에이전트, **세션 기본 ACP 에이전트**를 실행하거나 **ACP 에이전트를 하위 에이전트로 디스패치**할 수 있습니다. 기능이 다릅니다 (현재 제품; 계획된 호스트 작업은 해당 위치에 명시):

| 기능 | 내장 기본 | ACP 기본 | ACP 하위 에이전트 (디스패치) |
|------------|------------------|-------------|-------------------------|
| hip 도구 (읽기/쓰기/run_script/…) | 예 | 아니요 (에이전트 자체 도구) | 아니요 (에이전트 자체 도구) |
| hip 스킬 / 플러그인 훅 | 예 | 아니요 | 아니요 |
| hip MCP (세션에 병합) | 예 | 아니요 (계획: 옵트인 전달) | 아니요 (계획: 옵트인 전달) |
| 클라이언트 FS 브리지 | 해당 없음 | 아니요 (스텁만; 실제 브리지 계획됨) | 아니요 (스텁만; 실제 브리지 계획됨) |
| 디스패치 / task / task_batch | 예 | 아니요 | 아니요 |
| 메모리 주입 (세션 간) | 예 | 아니요 (구성 플래그 예약됨; 접두사 계획됨) | 아니요 |
| 메모리 추출 | 예 | 아니요 | 아니요 |
| hip 모델 선택기 | 예 | 아니요 (에이전트 configOptions / 에이전트 모델 UI) | 아니요 |
| HITL 권한 | hip 도구 | ACP \`requestPermission\` | ACP 기본과 동일 |
| permissionMode | hip 도구 게이트 | 채팅/편집에서 안전한 종류(읽기/가져오기/기타) 자동 해결; 그 외 HITL (\`full\`은 ACP 경로에서도 HITL) | 상위 세션 모드 |

**결론:** ACP를 기본으로 선택하는 것은 자체 스택을 가진 피어 코딩 에이전트입니다—hip의 내장 도구/스킬/MCP가 아닙니다. 하위 에이전트 디스패치는 동일한 에이전트 스택을 사용합니다; 기본 및 하위 에이전트 모두 현재 hip 메모리 주입 또는 hip MCP를 받지 않습니다.

## 위임 도구 (주 에이전트)

| 도구 | 사용 |
|------|-----|
| \`task\` | 하나의 하위 작업 (포그라운드 또는 백그라운드) |
| \`dispatch_agent\` | 명명된 로스터 에이전트; 병렬 도구 호출이 아니면 차단 |
| \`task_batch\` | **권장** 2개 이상의 독립적인 하위 작업 (진정한 병렬) |

순차적 디스패치만 사용된 경우 작업이 "병렬로" 실행되었다고 주장하지 마십시오.

## 플러그인

- \`~/.hip/plugins/\` 아래에 설치됨; 레지스트리는 \`~/.hip/config/hip-plugins.json\`에 있음.
- 플러그인은 스킬, 에이전트, MCP 서버 구성 및 훅을 제공할 수 있음.
- 플러그인을 비활성화하면 세션에서 해당 기여가 제거됨.

## MCP

- 서버 구성은 hip.toml / 플러그인 합성에서 가져옴.
- 코드 표면은 짧은 카탈로그를 주입할 수 있음; \`mcp_search\`로 검색.
- 도구를 \`mcp__<server>__<tool>\`로 호출.
- 네트워크 정책 (구성된 경우)은 아웃바운드 MCP/웹 도구를 차단할 수 있음.

## 스킬 범위

| 범위 | 위치 |
|-------|------|
| 전역 | \`~/.hip/skills/<id>/\` |
| 프로젝트 | \`.hip/skills/<id>/\` (동일한 id의 전역보다 우선) |
| 플러그인 | 플러그인 소유 스킬 디렉토리 |
| 내장 제품 | \`~/.hip/builtin-skills/hip/\` (최하위 우선순위; 동일한 id로 재정의 가능) |
`,
  }
  ],
},
}

/** Map app language / BCP-47 tag → product help locale. */
export function resolveProductHelpLocale(lang: string | null | undefined): ProductHelpLocale {
  const raw = (lang ?? '').trim()
  if (raw === 'zh-CN' || raw === 'zh-TW' || raw === 'en' || raw === 'ja' || raw === 'ko') return raw
  if (raw.startsWith('zh-TW') || raw.startsWith('zh-HK') || raw === 'zh-Hant') return 'zh-TW'
  if (raw.startsWith('zh')) return 'zh-CN'
  if (raw === 'ja' || raw.startsWith('ja-') || raw.startsWith('ja_')) return 'ja'
  if (raw === 'ko' || raw.startsWith('ko-') || raw.startsWith('ko_')) return 'ko'
  if (raw.startsWith('en')) return 'en'
  return 'en'
}

/** Locale pack for Settings Help; falls back to English. */
export function getProductHelpPack(lang: string | null | undefined): ProductHelpLocalePack {
  return PRODUCT_HELP_LOCALES[resolveProductHelpLocale(lang)]
}
