/**
 * AUTO-GENERATED by scripts/generate-product-content.mjs — DO NOT EDIT BY HAND.
 * Source of truth: packages/product-content/
 * Regenerate: yarn product:content
 * Check:      yarn product:content:check
 *
 * contentHash=451755b81ed37030 skillVersion=3 productVersion=1.0.1
 */

export type ProductHelpSectionId = 'overview' | 'memory' | 'config' | 'troubleshooting' | 'agents'

/** UI product-help locale ids (matches app language tags). */
export type ProductHelpLocale = 'en' | 'zh-CN' | 'zh-TW' | 'ja' | 'ko'

export interface ProductHelpSection {
  id: ProductHelpSectionId
  /** i18n key for the tab / nav label */
  titleKey: string
  /** Markdown body for this locale. */
  markdown: string
}

export interface ProductHelpLocalePack {
  description: string
  capabilityMap: string
  sections: readonly ProductHelpSection[]
}

/** App version from root package.json. */
export const HIP_PRODUCT_VERSION = '1.0.1'

/** Content schema version from packages/product-content/meta.json. */
export const PRODUCT_SKILL_VERSION = '3'

/** English defaults (agent-aligned). Prefer getProductHelpPack(lang) in UI. */
export const HIP_SKILL_DESCRIPTION = 'Product help for the hip desktop agent: Chat/Code/Knowledge surfaces, permission modes, Agents+Runtime panel, Settings, skills, plugins, MCP, memory, agents, CLI, troubleshooting, and local data. Load when the user asks how hip works or how to configure it.'

/** L0 capability map English (agent + default UI). */
export const PRODUCT_CAPABILITY_MAP = `Product facts (hip):
- Version: 1.0.1.
- Desktop workbench agent in the user's project with real file tools and optional sub-agents.
- Surfaces: Code (full workbench) vs Chat (lighter; previewable files → write_file for artifacts) vs Knowledge (notes spaces).
- On Code only, tool gates (UI labels): chat = read-only; edit = project sandbox (default); full = user-granted whole FS. Chat surface is not Code "edit mode".
- Right panel (session): Agents (roster / sub-agents) + Runtime (background shell, monitors, schedules) combined view.
- API keys: ~/.hip/config/auth.json (0600 plaintext by design).
- Cross-session memory: off by default (Settings → Memory).
- Local data: ~/.hip/ (config, db, skills, plugins, logs).`

/** English help sections (backward compatible). */
export const PRODUCT_HELP_SECTIONS: readonly ProductHelpSection[] = [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip is a **desktop AI workbench** (Tauri shell + React UI + Node sidecar), product version **1.0.1**. Each UI tab is an independent session. The default product loop is a **Supervisor ReAct** agent that uses tools and may delegate with \`task\` / \`dispatch_agent\` / \`task_batch\` — there is no forced Planner → Coder → Reviewer pipeline on ordinary turns.

This skill is the authoritative product guide for *hip itself*. For ordinary coding work in the user's project, do **not** load this skill.

Answer product questions in the **user's language** (e.g. Chinese if they wrote in Chinese), but keep config paths and identifiers exact.

## Progressive disclosure

- **Level 1** (system prompt Skills list): name + description only
- **Level 2** (this file): overview below, loaded via \`use_skill({ name: "hip" })\`
- **Level 3**: deeper topics in \`references/\` — read those absolute paths with \`read_file\` when needed

If a product detail is not documented here, say so rather than inventing UI labels or config keys.

## Surfaces

| Surface | Intent |
|---------|--------|
| **Code** | Project workbench: file tools, git guidance, MCP catalog, full agent tools, async TaskRuntime |
| **Chat** | Lighter conversation surface: shorter prompt, no git-commit guidance, prefer writing previewable deliverables (\`page.html\`, \`notes.md\`, SVG, etc.) into the workspace for the artifacts panel |
| **Knowledge** | Notes / knowledge-space assistant: grounded answers in the user's notes workspace; not a coding agent for a software project |

Surface is chosen in the UI; the system prompt already reflects the active surface.

## Permission modes

| Mode | Effect |
|------|--------|
| **edit** (default) | Filesystem tools sandboxed to the project root |
| **chat** | Read-only: no write/edit/script/git mutations |
| **full** | Un-sandboxed filesystem (user-granted); prefer absolute paths |

Path convention in edit/chat: project-root form starting with \`/\` (e.g. \`/src/index.ts\` maps to \`<cwd>/src/index.ts\`). Never invent shell tool names — use \`run_script\` when available.

## Settings (desktop UI)

Typical destinations (wording may vary slightly in the UI):

- **Providers / API keys** — stored as plaintext under \`~/.hip/config/auth.json\` (mode 0600 by design)
- **Memory** — cross-session memory is **off by default**; enable under Settings → Memory (see \`references/memory.md\`)
- **Skills** — enable/disable installed skills (\`hip.toml\` + skill folders)
- **Plugins** — install/enable plugins (skills, agents, MCP, hooks); Plugin Market under Settings
- **Agents** — fixed profiles (supervisor / plan / explore / coder) and custom internal or external agents
- **Network policy** — optional allow/deny for outbound tools

## Right panel: Agents + Runtime

Each session’s right panel combines:

- **Agents** — roster, active sub-agents, delegation status
- **Runtime** — background shell jobs, monitors, and schedules (TaskRuntime). Still-running work shows a chip; open the panel to inspect output and stop tasks.

Long shell, log watches, and recurring checks should use TaskRuntime tools (see \`references/agents-and-plugins.md\` and the \`hip-coding\` skill for policy). Do not sleep-poll in the main turn.

## Skills, plugins, MCP

- **Skills**: Claude-format folders with \`SKILL.md\`. Global: \`~/.hip/skills/<id>/\`. Project: \`.hip/skills/<id>/\`. Progressive disclosure: L1 metadata → \`use_skill\` body → \`references/\` + \`assets/\`.
- **Plugins**: under \`~/.hip/plugins/\`; can contribute skills, agents, MCP servers, and hooks. See \`references/agents-and-plugins.md\`.
- **MCP**: configured servers expose tools. In Code surface the system prompt may list a catalog; use \`mcp_search\` then call namespaced tools \`mcp__<server>__<tool>\`.

## Agents & delegation

- Default session agent decides when to use tools or delegate.
- Prefer specialized roster agents when available: **explore** (read-only search), **plan** (design-only), **coder** (implementation).
- Parallel independent sub-tasks → one \`task_batch\` (not sequential \`dispatch_agent\`).
- Long-running shell / CI / periodic work → TaskRuntime (\`run_script\` background, \`monitor\`, \`scheduler_*\`) rather than blocking the main turn.
- Explicit workflows / multi-agent handoff exist but are **not** the ordinary product path.
- Depth: \`references/agents-and-plugins.md\`.

## CLI (\`@hip/cli\`)

Attach-only companion to a **running** hip app (shared sidecar + \`~/.hip\` data). Does not start the product sidecar.

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

If the app is not running, CLI fails with \`APP_NOT_RUNNING\`.

## Project guidance files

When present under the project, hip may inject guidance such as \`AGENTS.md\` / \`Claude.md\` / \`.hip\` config. Prefer following those for **project** conventions; this skill is for **product** behavior.

## Level 3 references

After loading this skill, \`use_skill\` returns absolute paths. When the user needs depth:

- Memory enablement, inject, extract, privacy → \`references/memory.md\`
- Local data layout, config files, env overrides → \`references/config-and-data.md\`
- Common failures (no key, CLI not running, empty memory) → \`references/troubleshooting.md\`
- Agents, plugins, MCP, TaskRuntime tools → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip memory (Level 3)

Cross-session memory is **disabled by default** (privacy / cost).

## Enable

1. Open **Settings → Memory**.
2. Enable **use** and/or **generate**.
3. Enabling both from a cold install may apply a dogfood preset (shorter idle / extract interval) when gates are still defaults.
4. Ensure a provider API key is configured (Settings → Providers). Extraction needs an API key.

## What is stored

Structured items in SQLite (\`memory_items\`): preferences, conventions, lessons, workflows, profiles — scoped **global**, **project**, or **session**.

**Source of truth is SQLite.** Markdown under \`~/.hip/memories/\` is an export mirror. Project \`MEMORY.md\` / \`.hip/MEMORY.md\` is separate project-notes injection, not auto-imported into SQLite.

## Runtime behavior

| Path | Behavior |
|------|----------|
| **Use** | Core snapshot + per-turn prefetch + \`memory_*\` tools |
| **Generate** | After idle → Phase1 extract → Phase2 consolidate |
| **Incognito** | Session flag: no inject and no extract |
| **Learn now** | Settings control to force extract/consolidate when dogfooding |

Managed sub-agents may get read-only core injection; external ACP agents default off.

## Privacy notes

- Cold defaults: use/generate off
- Threat-scan + secret redact on write
- Soft-delete trash + retention
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip config & local data (Level 3)

## Layout (\`~/.hip/\`)

| Path | Purpose |
|------|---------|
| \`~/.hip/config/auth.json\` | Provider API keys (0600 plaintext by design) |
| \`~/.hip/config/hip.toml\` | Global product config (skills, agent loop, …) |
| \`~/.hip/config/memory.json\` | Memory feature flags / pipeline knobs |
| \`~/.hip/config/network.json\` | Optional network policy |
| \`~/.hip/config/hip-plugins.json\` | Installed plugins registry |
| \`~/.hip/db/hip.db\` | SQLite sessions, messages, memory items, events |
| \`~/.hip/data/tool-output/\` | Large tool outputs (kept out of the DB) |
| \`~/.hip/logs/\` | Sidecar / shell logs |
| \`~/.hip/skills/\` | Global skills |
| \`~/.hip/plugins/\` | Installed plugins |
| \`~/.hip/memories/\` | Memory markdown mirrors |
| \`~/.hip/builtin-skills/\` | Built-in progressive product skills (e.g. this \`hip\` skill) |
| \`~/.hip/scratch/\` | Scratch helpers |
| \`~/.hip/trash/\` | Product recycle bin (knowledge FS quarantine; sessions soft-delete via SQLite) |

### Recycle bin & soft-delete

| Behavior | Notes |
|----------|--------|
| UI delete (Chat / Code / Knowledge) | Soft-delete → sidebar **Recycle bin** (above History) |
| Retention | Default **7** days; **Settings → General** or \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **Permanent** hard-delete (not the recycle bin) |
| Memory trash | Still **Settings → Memory** (separate retention, default 30 days) |

Project overrides often live under \`<project>/.hip/\` (e.g. \`.hip/skills/\`, \`.hip/hip.toml\`).

## Env / isolation (advanced)

| Variable | Role |
|----------|------|
| \`HIP_DATA_DIR\` | Redirect data/config roots (tests / isolation) |
| \`HIP_SKILLS_DIR\` | Override global skills root |
| \`HIP_PLUGINS_DIR\` | Override plugins root |
| \`HIP_AUTH_PATH\` | Override auth.json path |
| \`HIP_CONFIG_PATH\` | Override hip.toml path |
| \`HIP_MEMORY_CONFIG_PATH\` | Override memory.json path |

**Do not** sync \`~/.hip/config/\` to public cloud or public dotfile repos — it may contain API keys.

## Auth model (BYOK)

Keys are entered in the app **Settings → Providers** panel and stored in \`auth.json\`. Desktop app, standalone sidecar, and tests all resolve from that store. This is intentional plaintext-on-disk with tight file modes — not a keychain migration target.

Design detail: \`docs/design/byok-spec.md\`.

### Resolution order

When resolving an API key for a provider:

1. **auth.json** entry for \`HIP_MODEL_<PROVIDER>_API_KEY\` (if the key name is present in the file)
   - Non-empty → use it
   - Empty string → **cleared** (tombstone); do **not** fall back to env
2. **Standard environment variables** (e.g. \`ANTHROPIC_API_KEY\`, \`OPENAI_API_KEY\`, \`DEEPSEEK_API_KEY\`, \`MINIMAX_API_KEY\`)
3. **\`HIP_MODEL_<PROVIDER>_API_KEY\`** env (legacy / Tauri inject / tests)

Saving or clearing a key does **not** require restarting the sidecar; the next request re-reads auth.json.

### Do not put LLM keys in hip.toml

\`[[providers]] api_key\` / \`apiKey\` is **not** used for chat. Use \`auth.json\` or env only.

### Custom providers (\`apiKind\`)

\`\`\`toml
[[providers]]
id = "my-minimax"
name = "My MiniMax"
baseUrl = "https://api.minimaxi.com/anthropic/v1"
apiKind = "anthropic"   # or "openai" (default)
enabled = true
\`\`\`

- \`openai\` — OpenAI Chat Completions compatible  
- \`anthropic\` — Anthropic Messages API (also used by MiniMax / Kimi gateways)

Set in **Settings → Add custom provider**, or edit the provider detail pane. Keys still go in \`auth.json\`.

### Key expressions in auth.json

\`\`\`json
{
  "HIP_MODEL_ANTHROPIC_API_KEY": "$ANTHROPIC_API_KEY",
  "HIP_MODEL_OPENAI_API_KEY": "!op read 'op://vault/openai/credential'"
}
\`\`\`

| Form | Meaning |
|------|---------|
| literal | Used as-is |
| \`$VAR\` / \`\${VAR}\` | Process environment |
| \`!command\` | Shell stdout (cached for process life). Disable with \`HIP_AUTH_ALLOW_CMD=0\` |
| \`$!…\` | Literal string starting with \`!\` (no shell) |

### Typed credentials (optional)

\`\`\`json
{
  "credentials": {
    "anthropic": {
      "type": "oauth",
      "access": "…",
      "refresh": "…",
      "expires": 1893456000000
    },
    "cloudflare-ai-gateway": {
      "type": "api_key",
      "key": "cf-token",
      "env": { "CLOUDFLARE_ACCOUNT_ID": "…", "CLOUDFLARE_GATEWAY_ID": "…" }
    }
  }
}
\`\`\`

Flat \`HIP_MODEL_*\` keys remain fully supported. When both exist, \`credentials[provider]\` wins. Expired OAuth does **not** fall back to env.

### ACP: optional hip key forward

\`\`\`toml
[acp]
forward_hip_keys = true   # default false — inject hip keys as ANTHROPIC_API_KEY / OPENAI_API_KEY / …
\`\`\`

Default remains self-managed ACP (no hip key injection).
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip troubleshooting (Level 3)

## No API / model calls work

1. Open **Settings → Providers** and confirm a key is saved.
2. Keys live in \`~/.hip/config/auth.json\` (never print secrets to the user).
3. Restart the app after changing auth outside the UI.
4. Check sidecar logs under \`~/.hip/logs/\`.

## CLI: \`APP_NOT_RUNNING\`

The product CLI attaches to a **running** hip desktop app. Start the app first (\`yarn tauri dev\` or installed app), then \`yarn cli:dev doctor\`.

## Memory list empty after enabling

1. Confirm **Settings → Memory** has **use** and **generate** as intended.
2. Need enough chat turns + API key for extract; try **Learn now**.
3. Status may show \`no_llm\`, \`rate_limited\`, or empty extract — fix key / quota / wait.
4. SQLite is source of truth; stale mirrors under \`~/.hip/memories/\` are not the DB.

## Agent cannot write files

- Permission mode **chat** is read-only.
- Default **edit** is sandboxed to the project root — paths outside fail.
- Use **full** only when the user explicitly granted whole-machine FS access.

## Skill not listed / use_skill fails

- Skill may be disabled in \`hip.toml\` or plugin disabled.
- Project skill \`paths\` globs may exclude the cwd.
- Built-in product skill id is \`hip\` under \`~/.hip/builtin-skills/hip/\`.

## Sidecar / connection issues

- Desktop shell spawns the sidecar and exposes its WS port.
- If the UI cannot connect, restart the app; check \`~/.hip/logs/\`.
- Dev: regenerate sidecar binary wrapper with \`yarn sidecar:dev-bin\` after toolchain changes.

## Stale DMG / build (macOS)

Stale \`rw.*.dmg\` mounts can break \`yarn tauri build\`; remove them and detach \`/Volumes/hip\` if needed.
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip agents, plugins & MCP (Level 3)

## Built-in agent profiles

Typical fixed profiles (enable/disable in Agents UI):

| Profile | Role |
|---------|------|
| **supervisor** | Default orchestrator: tools, commit, scripts, delegation |
| **plan** | Design / planning oriented (narrower write posture depending on config) |
| **explore** | Read-only codebase search |
| **coder** | Implementation-focused with scripts |

Custom **internal** agents: persona prompt + bound model + tool grants.  
**External / ACP** agents: separate process; product memory defaults off unless configured.

Supported ACP presets (Settings → Agents → Add ACP agent): **OpenCode**, **Grok Build** (\`grok agent stdio\`), **Pi**, **Claude Code**, **Codex**. Grok Build uses native ACP (install via \`https://x.ai/cli\`); auth via \`grok login\` or optional \`XAI_API_KEY\`.

ACP agents are **self-managed** for auth and models by default: hip does not inject its provider API keys into the ACP child process. Use the agent’s own login / ambient env / optional preset \`authEnvVar\` on the agent config.

Opt-in bridge (BYOK Phase E): set \`[acp] forward_hip_keys = true\` in \`hip.toml\` to inject resolved hip keys under standard env names (\`ANTHROPIC_API_KEY\`, \`OPENAI_API_KEY\`, …) for ACP spawns. Agent \`env\` and ambient process env still take precedence when already set.

## Capability matrix (Built-in vs ACP)

hip can run a **built-in** LangGraph agent, an **ACP agent as the session primary**, or **dispatch an ACP agent as a subagent**. Capabilities differ (current product; planned host work noted where relevant):

| Capability | Built-in primary | ACP primary | ACP subagent (dispatch) |
|------------|------------------|-------------|-------------------------|
| hip tools (read / write / run_script / …) | yes | no (agent’s own tools) | no (agent’s own tools) |
| hip Skills / plugin hooks | yes | no | no |
| hip MCP (merged into session) | yes | no (planned: opt-in forward) | no (planned: opt-in forward) |
| Client FS bridge | n/a | no (stub only; real bridge planned) | no (stub only; real bridge planned) |
| dispatch / task / task_batch | yes | no | no |
| TaskRuntime (bg shell / monitor / scheduler) | yes | no | no |
| Memory inject (cross-session) | yes | no (config flag reserved; prefix planned) | no |
| Memory extract | yes | no | no |
| hip model picker | yes | no (agent configOptions / agent model UI) | no |
| HITL permission | hip tools | ACP \`requestPermission\` | same as ACP primary |
| permissionMode | hip tool gates | auto-resolve safe kinds (read/fetch/other) in chat/edit; else HITL (\`full\` also HITL on ACP path) | parent session mode |

**Takeaway:** choosing ACP as primary is a peer coding agent with its own stack—not hip’s built-in tools/skills/MCP. Subagent dispatch uses the same agent stack; neither primary nor subagent currently gets hip memory inject or hip MCP.

## Delegation & TaskRuntime tools (main agent)

| Tool | Use |
|------|-----|
| \`task\` | One sub-task (foreground or background) |
| \`dispatch_agent\` | Named roster agent; blocking unless parallel tool-calls |
| \`task_batch\` | **Preferred** for 2+ independent sub-tasks (true parallel) |
| \`run_script\` (+ \`background:true\`) | Shell; long work returns \`task_id\` |
| \`wait_tasks\` | Wait for one or more background task ids |
| \`task_output\` | Read output so far (shell / agent / monitor) |
| \`task_stop\` | Stop a running background task |
| \`monitor\` | Stream stdout as UI events (not auto-injected into the model) |
| \`scheduler_create\` / \`scheduler_list\` / \`scheduler_delete\` | Recurring prompt wakes (min interval 60s) |

Do not claim work ran "in parallel" if only sequential dispatch was used.  
Do not sleep-poll the main turn for long shell or CI — use TaskRuntime tools above.

### Runtime panel (UI)

Session right panel combines **Agents** (roster / sub-agents) and **Runtime** (background shell, monitors, schedules). Still-running work shows a chip; open Runtime to inspect or stop tasks.

## Plugins

- Installed under \`~/.hip/plugins/\`; registry in \`~/.hip/config/hip-plugins.json\`.
- A plugin may ship skills, agents, MCP server configs, and hooks.
- Disable a plugin to drop its contributions from the session.

### Plugin Market (Settings)

hip’s Plugin Market page integrates **only** the official catalogs:

| Source id | Catalog |
|-----------|---------|
| \`grok-official\` | [xai-org/plugin-marketplace](https://github.com/xai-org/plugin-marketplace) |
| \`claude-official\` | [anthropics/claude-plugins-official](https://github.com/anthropics/claude-plugins-official) |

UI tabs: **Grok market** · **Claude market** · **Custom plugins** (local installs without official provenance).

- Catalog cache: \`~/.hip/cache/marketplaces/<sourceId>/\`
- Source toggles: \`~/.hip/config/marketplace-sources.json\`
- Marketplace **download** registers the plugin with \`enabled: false\` by default (downloaded but not on).
- On download, sidecar **reviews** agent \`boundModel\` fields; unavailable models are rewritten to the product default (\`activeModel\` in hip.toml).
- Enable the plugin switch to inject skills/MCP/agents into sessions (\`plugin:reload\`).

### Plugin directory structure

Every plugin **must** contain a \`.plugin/plugin.json\` manifest file. Without it, hip will not discover the plugin:

\`\`\`
~/.hip/plugins/<plugin-id>/
  .plugin/
    plugin.json          ← REQUIRED manifest (name, version, skills, etc.)
  skills/                ← optional, referenced by manifest "skills" field
    <skill-id>/
      SKILL.md
\`\`\`

### \`.plugin/plugin.json\` manifest

**Required fields:**

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0"
}
\`\`\`

**Full example** (all optional fields):

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0",
  "id": "my-plugin",
  "description": "A sample hip plugin",
  "author": { "name": "Author Name" },
  "license": "MIT",
  "keywords": ["ai", "tools"],
  "skills": ["./skills/tdd", "./skills/debug"],
  "mcpServers": "./mcp-config.json",
  "agents": "./agents.json",
  "hooks": "./hooks.json"
}
\`\`\`

- \`skills\` — a path (or array of paths) to directories containing \`SKILL.md\` files. Paths are relative to the plugin root and must not use \`..\`.
- \`mcpServers\`, \`agents\`, \`hooks\` — can be specified inline as JSON arrays/objects, or as a path to an external JSON file under the plugin root.

### \`hip-plugins.json\` registry format

The registry maps plugin IDs to absolute paths. Two formats are supported:

**String array format** (recommended for new plugins):
\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

**Legacy object format** (uses \`"dir"\` key):
\`\`\`json
{
  "plugins": [
    { "dir": "/absolute/path/to/plugin", "enabled": true }
  ]
}
\`\`\`

To install a plugin:

1. Clone/download the plugin under \`~/.hip/plugins/<plugin-id>/\`.
2. Ensure \`.plugin/plugin.json\` exists with at least \`name\` and \`version\`.
3. Add the absolute path to \`hip-plugins.json\` → \`plugins\` array (string format).
4. The plugin will be discovered on next session start or after \`plugin:reload\`.

## MCP

- Server configs come from hip.toml / plugin synthesis.
- Code surface may inject a short catalog; discover with \`mcp_search\`.
- Call tools as \`mcp__<server>__<tool>\`.
- Network policy (if configured) may block outbound MCP/web tools.

## Skills scopes

| Scope | Location |
|-------|----------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\` (wins over global same id) |
| plugin | plugin-owned skill dirs |
| builtin product | \`~/.hip/builtin-skills/hip/\` (lowest priority; overridable by same id) |
`,
  }
] as const

/** All UI locales for Settings → Product help. Agent embeds stay English. */
export const PRODUCT_HELP_LOCALES: Record<ProductHelpLocale, ProductHelpLocalePack> = {
  en: {
  description: 'Product help for the hip desktop agent: Chat/Code/Knowledge surfaces, permission modes, Agents+Runtime panel, Settings, skills, plugins, MCP, memory, agents, CLI, troubleshooting, and local data. Load when the user asks how hip works or how to configure it.',
  capabilityMap: `Product facts (hip):
- Version: 1.0.1.
- Desktop workbench agent in the user's project with real file tools and optional sub-agents.
- Surfaces: Code (full workbench) vs Chat (lighter; previewable files → write_file for artifacts) vs Knowledge (notes spaces).
- On Code only, tool gates (UI labels): chat = read-only; edit = project sandbox (default); full = user-granted whole FS. Chat surface is not Code "edit mode".
- Right panel (session): Agents (roster / sub-agents) + Runtime (background shell, monitors, schedules) combined view.
- API keys: ~/.hip/config/auth.json (0600 plaintext by design).
- Cross-session memory: off by default (Settings → Memory).
- Local data: ~/.hip/ (config, db, skills, plugins, logs).`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip is a **desktop AI workbench** (Tauri shell + React UI + Node sidecar), product version **1.0.1**. Each UI tab is an independent session. The default product loop is a **Supervisor ReAct** agent that uses tools and may delegate with \`task\` / \`dispatch_agent\` / \`task_batch\` — there is no forced Planner → Coder → Reviewer pipeline on ordinary turns.

This skill is the authoritative product guide for *hip itself*. For ordinary coding work in the user's project, do **not** load this skill.

Answer product questions in the **user's language** (e.g. Chinese if they wrote in Chinese), but keep config paths and identifiers exact.

## Progressive disclosure

- **Level 1** (system prompt Skills list): name + description only
- **Level 2** (this file): overview below, loaded via \`use_skill({ name: "hip" })\`
- **Level 3**: deeper topics in \`references/\` — read those absolute paths with \`read_file\` when needed

If a product detail is not documented here, say so rather than inventing UI labels or config keys.

## Surfaces

| Surface | Intent |
|---------|--------|
| **Code** | Project workbench: file tools, git guidance, MCP catalog, full agent tools, async TaskRuntime |
| **Chat** | Lighter conversation surface: shorter prompt, no git-commit guidance, prefer writing previewable deliverables (\`page.html\`, \`notes.md\`, SVG, etc.) into the workspace for the artifacts panel |
| **Knowledge** | Notes / knowledge-space assistant: grounded answers in the user's notes workspace; not a coding agent for a software project |

Surface is chosen in the UI; the system prompt already reflects the active surface.

## Permission modes

| Mode | Effect |
|------|--------|
| **edit** (default) | Filesystem tools sandboxed to the project root |
| **chat** | Read-only: no write/edit/script/git mutations |
| **full** | Un-sandboxed filesystem (user-granted); prefer absolute paths |

Path convention in edit/chat: project-root form starting with \`/\` (e.g. \`/src/index.ts\` maps to \`<cwd>/src/index.ts\`). Never invent shell tool names — use \`run_script\` when available.

## Settings (desktop UI)

Typical destinations (wording may vary slightly in the UI):

- **Providers / API keys** — stored as plaintext under \`~/.hip/config/auth.json\` (mode 0600 by design)
- **Memory** — cross-session memory is **off by default**; enable under Settings → Memory (see \`references/memory.md\`)
- **Skills** — enable/disable installed skills (\`hip.toml\` + skill folders)
- **Plugins** — install/enable plugins (skills, agents, MCP, hooks); Plugin Market under Settings
- **Agents** — fixed profiles (supervisor / plan / explore / coder) and custom internal or external agents
- **Network policy** — optional allow/deny for outbound tools

## Right panel: Agents + Runtime

Each session’s right panel combines:

- **Agents** — roster, active sub-agents, delegation status
- **Runtime** — background shell jobs, monitors, and schedules (TaskRuntime). Still-running work shows a chip; open the panel to inspect output and stop tasks.

Long shell, log watches, and recurring checks should use TaskRuntime tools (see \`references/agents-and-plugins.md\` and the \`hip-coding\` skill for policy). Do not sleep-poll in the main turn.

## Skills, plugins, MCP

- **Skills**: Claude-format folders with \`SKILL.md\`. Global: \`~/.hip/skills/<id>/\`. Project: \`.hip/skills/<id>/\`. Progressive disclosure: L1 metadata → \`use_skill\` body → \`references/\` + \`assets/\`.
- **Plugins**: under \`~/.hip/plugins/\`; can contribute skills, agents, MCP servers, and hooks. See \`references/agents-and-plugins.md\`.
- **MCP**: configured servers expose tools. In Code surface the system prompt may list a catalog; use \`mcp_search\` then call namespaced tools \`mcp__<server>__<tool>\`.

## Agents & delegation

- Default session agent decides when to use tools or delegate.
- Prefer specialized roster agents when available: **explore** (read-only search), **plan** (design-only), **coder** (implementation).
- Parallel independent sub-tasks → one \`task_batch\` (not sequential \`dispatch_agent\`).
- Long-running shell / CI / periodic work → TaskRuntime (\`run_script\` background, \`monitor\`, \`scheduler_*\`) rather than blocking the main turn.
- Explicit workflows / multi-agent handoff exist but are **not** the ordinary product path.
- Depth: \`references/agents-and-plugins.md\`.

## CLI (\`@hip/cli\`)

Attach-only companion to a **running** hip app (shared sidecar + \`~/.hip\` data). Does not start the product sidecar.

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

If the app is not running, CLI fails with \`APP_NOT_RUNNING\`.

## Project guidance files

When present under the project, hip may inject guidance such as \`AGENTS.md\` / \`Claude.md\` / \`.hip\` config. Prefer following those for **project** conventions; this skill is for **product** behavior.

## Level 3 references

After loading this skill, \`use_skill\` returns absolute paths. When the user needs depth:

- Memory enablement, inject, extract, privacy → \`references/memory.md\`
- Local data layout, config files, env overrides → \`references/config-and-data.md\`
- Common failures (no key, CLI not running, empty memory) → \`references/troubleshooting.md\`
- Agents, plugins, MCP, TaskRuntime tools → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip memory (Level 3)

Cross-session memory is **disabled by default** (privacy / cost).

## Enable

1. Open **Settings → Memory**.
2. Enable **use** and/or **generate**.
3. Enabling both from a cold install may apply a dogfood preset (shorter idle / extract interval) when gates are still defaults.
4. Ensure a provider API key is configured (Settings → Providers). Extraction needs an API key.

## What is stored

Structured items in SQLite (\`memory_items\`): preferences, conventions, lessons, workflows, profiles — scoped **global**, **project**, or **session**.

**Source of truth is SQLite.** Markdown under \`~/.hip/memories/\` is an export mirror. Project \`MEMORY.md\` / \`.hip/MEMORY.md\` is separate project-notes injection, not auto-imported into SQLite.

## Runtime behavior

| Path | Behavior |
|------|----------|
| **Use** | Core snapshot + per-turn prefetch + \`memory_*\` tools |
| **Generate** | After idle → Phase1 extract → Phase2 consolidate |
| **Incognito** | Session flag: no inject and no extract |
| **Learn now** | Settings control to force extract/consolidate when dogfooding |

Managed sub-agents may get read-only core injection; external ACP agents default off.

## Privacy notes

- Cold defaults: use/generate off
- Threat-scan + secret redact on write
- Soft-delete trash + retention
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip config & local data (Level 3)

## Layout (\`~/.hip/\`)

| Path | Purpose |
|------|---------|
| \`~/.hip/config/auth.json\` | Provider API keys (0600 plaintext by design) |
| \`~/.hip/config/hip.toml\` | Global product config (skills, agent loop, …) |
| \`~/.hip/config/memory.json\` | Memory feature flags / pipeline knobs |
| \`~/.hip/config/network.json\` | Optional network policy |
| \`~/.hip/config/hip-plugins.json\` | Installed plugins registry |
| \`~/.hip/db/hip.db\` | SQLite sessions, messages, memory items, events |
| \`~/.hip/data/tool-output/\` | Large tool outputs (kept out of the DB) |
| \`~/.hip/logs/\` | Sidecar / shell logs |
| \`~/.hip/skills/\` | Global skills |
| \`~/.hip/plugins/\` | Installed plugins |
| \`~/.hip/memories/\` | Memory markdown mirrors |
| \`~/.hip/builtin-skills/\` | Built-in progressive product skills (e.g. this \`hip\` skill) |
| \`~/.hip/scratch/\` | Scratch helpers |
| \`~/.hip/trash/\` | Product recycle bin (knowledge FS quarantine; sessions soft-delete via SQLite) |

### Recycle bin & soft-delete

| Behavior | Notes |
|----------|--------|
| UI delete (Chat / Code / Knowledge) | Soft-delete → sidebar **Recycle bin** (above History) |
| Retention | Default **7** days; **Settings → General** or \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **Permanent** hard-delete (not the recycle bin) |
| Memory trash | Still **Settings → Memory** (separate retention, default 30 days) |

Project overrides often live under \`<project>/.hip/\` (e.g. \`.hip/skills/\`, \`.hip/hip.toml\`).

## Env / isolation (advanced)

| Variable | Role |
|----------|------|
| \`HIP_DATA_DIR\` | Redirect data/config roots (tests / isolation) |
| \`HIP_SKILLS_DIR\` | Override global skills root |
| \`HIP_PLUGINS_DIR\` | Override plugins root |
| \`HIP_AUTH_PATH\` | Override auth.json path |
| \`HIP_CONFIG_PATH\` | Override hip.toml path |
| \`HIP_MEMORY_CONFIG_PATH\` | Override memory.json path |

**Do not** sync \`~/.hip/config/\` to public cloud or public dotfile repos — it may contain API keys.

## Auth model (BYOK)

Keys are entered in the app **Settings → Providers** panel and stored in \`auth.json\`. Desktop app, standalone sidecar, and tests all resolve from that store. This is intentional plaintext-on-disk with tight file modes — not a keychain migration target.

Design detail: \`docs/design/byok-spec.md\`.

### Resolution order

When resolving an API key for a provider:

1. **auth.json** entry for \`HIP_MODEL_<PROVIDER>_API_KEY\` (if the key name is present in the file)
   - Non-empty → use it
   - Empty string → **cleared** (tombstone); do **not** fall back to env
2. **Standard environment variables** (e.g. \`ANTHROPIC_API_KEY\`, \`OPENAI_API_KEY\`, \`DEEPSEEK_API_KEY\`, \`MINIMAX_API_KEY\`)
3. **\`HIP_MODEL_<PROVIDER>_API_KEY\`** env (legacy / Tauri inject / tests)

Saving or clearing a key does **not** require restarting the sidecar; the next request re-reads auth.json.

### Do not put LLM keys in hip.toml

\`[[providers]] api_key\` / \`apiKey\` is **not** used for chat. Use \`auth.json\` or env only.

### Custom providers (\`apiKind\`)

\`\`\`toml
[[providers]]
id = "my-minimax"
name = "My MiniMax"
baseUrl = "https://api.minimaxi.com/anthropic/v1"
apiKind = "anthropic"   # or "openai" (default)
enabled = true
\`\`\`

- \`openai\` — OpenAI Chat Completions compatible  
- \`anthropic\` — Anthropic Messages API (also used by MiniMax / Kimi gateways)

Set in **Settings → Add custom provider**, or edit the provider detail pane. Keys still go in \`auth.json\`.

### Key expressions in auth.json

\`\`\`json
{
  "HIP_MODEL_ANTHROPIC_API_KEY": "$ANTHROPIC_API_KEY",
  "HIP_MODEL_OPENAI_API_KEY": "!op read 'op://vault/openai/credential'"
}
\`\`\`

| Form | Meaning |
|------|---------|
| literal | Used as-is |
| \`$VAR\` / \`\${VAR}\` | Process environment |
| \`!command\` | Shell stdout (cached for process life). Disable with \`HIP_AUTH_ALLOW_CMD=0\` |
| \`$!…\` | Literal string starting with \`!\` (no shell) |

### Typed credentials (optional)

\`\`\`json
{
  "credentials": {
    "anthropic": {
      "type": "oauth",
      "access": "…",
      "refresh": "…",
      "expires": 1893456000000
    },
    "cloudflare-ai-gateway": {
      "type": "api_key",
      "key": "cf-token",
      "env": { "CLOUDFLARE_ACCOUNT_ID": "…", "CLOUDFLARE_GATEWAY_ID": "…" }
    }
  }
}
\`\`\`

Flat \`HIP_MODEL_*\` keys remain fully supported. When both exist, \`credentials[provider]\` wins. Expired OAuth does **not** fall back to env.

### ACP: optional hip key forward

\`\`\`toml
[acp]
forward_hip_keys = true   # default false — inject hip keys as ANTHROPIC_API_KEY / OPENAI_API_KEY / …
\`\`\`

Default remains self-managed ACP (no hip key injection).
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip troubleshooting (Level 3)

## No API / model calls work

1. Open **Settings → Providers** and confirm a key is saved.
2. Keys live in \`~/.hip/config/auth.json\` (never print secrets to the user).
3. Restart the app after changing auth outside the UI.
4. Check sidecar logs under \`~/.hip/logs/\`.

## CLI: \`APP_NOT_RUNNING\`

The product CLI attaches to a **running** hip desktop app. Start the app first (\`yarn tauri dev\` or installed app), then \`yarn cli:dev doctor\`.

## Memory list empty after enabling

1. Confirm **Settings → Memory** has **use** and **generate** as intended.
2. Need enough chat turns + API key for extract; try **Learn now**.
3. Status may show \`no_llm\`, \`rate_limited\`, or empty extract — fix key / quota / wait.
4. SQLite is source of truth; stale mirrors under \`~/.hip/memories/\` are not the DB.

## Agent cannot write files

- Permission mode **chat** is read-only.
- Default **edit** is sandboxed to the project root — paths outside fail.
- Use **full** only when the user explicitly granted whole-machine FS access.

## Skill not listed / use_skill fails

- Skill may be disabled in \`hip.toml\` or plugin disabled.
- Project skill \`paths\` globs may exclude the cwd.
- Built-in product skill id is \`hip\` under \`~/.hip/builtin-skills/hip/\`.

## Sidecar / connection issues

- Desktop shell spawns the sidecar and exposes its WS port.
- If the UI cannot connect, restart the app; check \`~/.hip/logs/\`.
- Dev: regenerate sidecar binary wrapper with \`yarn sidecar:dev-bin\` after toolchain changes.

## Stale DMG / build (macOS)

Stale \`rw.*.dmg\` mounts can break \`yarn tauri build\`; remove them and detach \`/Volumes/hip\` if needed.
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip agents, plugins & MCP (Level 3)

## Built-in agent profiles

Typical fixed profiles (enable/disable in Agents UI):

| Profile | Role |
|---------|------|
| **supervisor** | Default orchestrator: tools, commit, scripts, delegation |
| **plan** | Design / planning oriented (narrower write posture depending on config) |
| **explore** | Read-only codebase search |
| **coder** | Implementation-focused with scripts |

Custom **internal** agents: persona prompt + bound model + tool grants.  
**External / ACP** agents: separate process; product memory defaults off unless configured.

Supported ACP presets (Settings → Agents → Add ACP agent): **OpenCode**, **Grok Build** (\`grok agent stdio\`), **Pi**, **Claude Code**, **Codex**. Grok Build uses native ACP (install via \`https://x.ai/cli\`); auth via \`grok login\` or optional \`XAI_API_KEY\`.

ACP agents are **self-managed** for auth and models by default: hip does not inject its provider API keys into the ACP child process. Use the agent’s own login / ambient env / optional preset \`authEnvVar\` on the agent config.

Opt-in bridge (BYOK Phase E): set \`[acp] forward_hip_keys = true\` in \`hip.toml\` to inject resolved hip keys under standard env names (\`ANTHROPIC_API_KEY\`, \`OPENAI_API_KEY\`, …) for ACP spawns. Agent \`env\` and ambient process env still take precedence when already set.

## Capability matrix (Built-in vs ACP)

hip can run a **built-in** LangGraph agent, an **ACP agent as the session primary**, or **dispatch an ACP agent as a subagent**. Capabilities differ (current product; planned host work noted where relevant):

| Capability | Built-in primary | ACP primary | ACP subagent (dispatch) |
|------------|------------------|-------------|-------------------------|
| hip tools (read / write / run_script / …) | yes | no (agent’s own tools) | no (agent’s own tools) |
| hip Skills / plugin hooks | yes | no | no |
| hip MCP (merged into session) | yes | no (planned: opt-in forward) | no (planned: opt-in forward) |
| Client FS bridge | n/a | no (stub only; real bridge planned) | no (stub only; real bridge planned) |
| dispatch / task / task_batch | yes | no | no |
| TaskRuntime (bg shell / monitor / scheduler) | yes | no | no |
| Memory inject (cross-session) | yes | no (config flag reserved; prefix planned) | no |
| Memory extract | yes | no | no |
| hip model picker | yes | no (agent configOptions / agent model UI) | no |
| HITL permission | hip tools | ACP \`requestPermission\` | same as ACP primary |
| permissionMode | hip tool gates | auto-resolve safe kinds (read/fetch/other) in chat/edit; else HITL (\`full\` also HITL on ACP path) | parent session mode |

**Takeaway:** choosing ACP as primary is a peer coding agent with its own stack—not hip’s built-in tools/skills/MCP. Subagent dispatch uses the same agent stack; neither primary nor subagent currently gets hip memory inject or hip MCP.

## Delegation & TaskRuntime tools (main agent)

| Tool | Use |
|------|-----|
| \`task\` | One sub-task (foreground or background) |
| \`dispatch_agent\` | Named roster agent; blocking unless parallel tool-calls |
| \`task_batch\` | **Preferred** for 2+ independent sub-tasks (true parallel) |
| \`run_script\` (+ \`background:true\`) | Shell; long work returns \`task_id\` |
| \`wait_tasks\` | Wait for one or more background task ids |
| \`task_output\` | Read output so far (shell / agent / monitor) |
| \`task_stop\` | Stop a running background task |
| \`monitor\` | Stream stdout as UI events (not auto-injected into the model) |
| \`scheduler_create\` / \`scheduler_list\` / \`scheduler_delete\` | Recurring prompt wakes (min interval 60s) |

Do not claim work ran "in parallel" if only sequential dispatch was used.  
Do not sleep-poll the main turn for long shell or CI — use TaskRuntime tools above.

### Runtime panel (UI)

Session right panel combines **Agents** (roster / sub-agents) and **Runtime** (background shell, monitors, schedules). Still-running work shows a chip; open Runtime to inspect or stop tasks.

## Plugins

- Installed under \`~/.hip/plugins/\`; registry in \`~/.hip/config/hip-plugins.json\`.
- A plugin may ship skills, agents, MCP server configs, and hooks.
- Disable a plugin to drop its contributions from the session.

### Plugin Market (Settings)

hip’s Plugin Market page integrates **only** the official catalogs:

| Source id | Catalog |
|-----------|---------|
| \`grok-official\` | [xai-org/plugin-marketplace](https://github.com/xai-org/plugin-marketplace) |
| \`claude-official\` | [anthropics/claude-plugins-official](https://github.com/anthropics/claude-plugins-official) |

UI tabs: **Grok market** · **Claude market** · **Custom plugins** (local installs without official provenance).

- Catalog cache: \`~/.hip/cache/marketplaces/<sourceId>/\`
- Source toggles: \`~/.hip/config/marketplace-sources.json\`
- Marketplace **download** registers the plugin with \`enabled: false\` by default (downloaded but not on).
- On download, sidecar **reviews** agent \`boundModel\` fields; unavailable models are rewritten to the product default (\`activeModel\` in hip.toml).
- Enable the plugin switch to inject skills/MCP/agents into sessions (\`plugin:reload\`).

### Plugin directory structure

Every plugin **must** contain a \`.plugin/plugin.json\` manifest file. Without it, hip will not discover the plugin:

\`\`\`
~/.hip/plugins/<plugin-id>/
  .plugin/
    plugin.json          ← REQUIRED manifest (name, version, skills, etc.)
  skills/                ← optional, referenced by manifest "skills" field
    <skill-id>/
      SKILL.md
\`\`\`

### \`.plugin/plugin.json\` manifest

**Required fields:**

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0"
}
\`\`\`

**Full example** (all optional fields):

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0",
  "id": "my-plugin",
  "description": "A sample hip plugin",
  "author": { "name": "Author Name" },
  "license": "MIT",
  "keywords": ["ai", "tools"],
  "skills": ["./skills/tdd", "./skills/debug"],
  "mcpServers": "./mcp-config.json",
  "agents": "./agents.json",
  "hooks": "./hooks.json"
}
\`\`\`

- \`skills\` — a path (or array of paths) to directories containing \`SKILL.md\` files. Paths are relative to the plugin root and must not use \`..\`.
- \`mcpServers\`, \`agents\`, \`hooks\` — can be specified inline as JSON arrays/objects, or as a path to an external JSON file under the plugin root.

### \`hip-plugins.json\` registry format

The registry maps plugin IDs to absolute paths. Two formats are supported:

**String array format** (recommended for new plugins):
\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

**Legacy object format** (uses \`"dir"\` key):
\`\`\`json
{
  "plugins": [
    { "dir": "/absolute/path/to/plugin", "enabled": true }
  ]
}
\`\`\`

To install a plugin:

1. Clone/download the plugin under \`~/.hip/plugins/<plugin-id>/\`.
2. Ensure \`.plugin/plugin.json\` exists with at least \`name\` and \`version\`.
3. Add the absolute path to \`hip-plugins.json\` → \`plugins\` array (string format).
4. The plugin will be discovered on next session start or after \`plugin:reload\`.

## MCP

- Server configs come from hip.toml / plugin synthesis.
- Code surface may inject a short catalog; discover with \`mcp_search\`.
- Call tools as \`mcp__<server>__<tool>\`.
- Network policy (if configured) may block outbound MCP/web tools.

## Skills scopes

| Scope | Location |
|-------|----------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\` (wins over global same id) |
| plugin | plugin-owned skill dirs |
| builtin product | \`~/.hip/builtin-skills/hip/\` (lowest priority; overridable by same id) |
`,
  }
  ],
},
  'zh-CN': {
  description: 'hip 桌面智能体产品帮助：Chat/Code/Knowledge 界面、权限模式、Agents+Runtime 面板、设置、技能、插件、MCP、记忆、智能体、CLI、故障排查与本地数据布局。当用户询问 hip 如何工作或如何配置时加载。',
  capabilityMap: `产品要点（hip）：
- 版本：1.0.1。
- 桌面 AI 工作台智能体，在用户项目中使用真实文件工具，并可委派子智能体。
- 界面：Code（完整工作台）与 Chat（更轻；可预览交付物请 write_file 到工件面板）与 Knowledge（笔记空间）。
- 仅在 Code 上，工具门禁（UI 标签）：chat = 只读；edit = 项目沙箱（默认）；full = 用户授权的整机文件系统。Chat 界面不是 Code 的「edit 模式」。
- 会话右侧面板：Agents（花名册 / 子智能体）与 Runtime（后台 shell、monitor、定时任务）合并视图。
- API 密钥：~/.hip/config/auth.json（按设计为 0600 明文）。
- 跨会话记忆：默认关闭（设置 → 记忆）。
- 本地数据：~/.hip/（配置、数据库、技能、插件、日志）。`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip 是一款**桌面 AI 工作台**（Tauri 壳 + React UI + Node sidecar），产品版本 **1.0.1**。每个 UI 标签页是独立会话。默认产品回路是 **Supervisor ReAct** 智能体：用工具完成工作，并可通过 \`task\` / \`dispatch_agent\` / \`task_batch\` 委派——普通轮次**不会**强制 Planner → Coder → Reviewer 流水线。

本技能是 *hip 产品本身* 的权威指南。用户项目中的普通编码任务**不要**加载本技能。

用**用户的语言**回答产品问题（例如用户用中文提问则用中文答），但配置路径与标识符请保持原文准确。

## 渐进式披露

- **Level 1**（系统提示 Skills 列表）：仅名称 + 描述
- **Level 2**（本文件）：下方概览，通过 \`use_skill({ name: "hip" })\` 加载
- **Level 3**：\`references/\` 中的深入主题——需要时用 \`read_file\` 读绝对路径

若某产品细节未写在此处，请如实说明，不要编造 UI 文案或配置键。

## 界面（Surfaces）

| 界面 | 用途 |
|------|------|
| **Code** | 项目工作台：文件工具、git 指导、MCP 目录、完整智能体工具、异步 TaskRuntime |
| **Chat** | 更轻的会话面：更短提示、无 git 提交指导；可预览交付物（\`page.html\`、\`notes.md\`、SVG 等）请 \`write_file\` 到工作区以便工件面板展示 |
| **Knowledge** | 笔记 / 知识空间助手：基于用户笔记作答；不是软件项目的编码智能体 |

界面在 UI 中选择；系统提示会反映当前界面。

## 权限模式

| 模式 | 效果 |
|------|------|
| **edit**（默认） | 文件系统工具限制在项目根沙箱内 |
| **chat** | 只读：不能写/改文件，不能跑脚本 |
| **full** | 未沙箱的文件系统（用户明确授权）；优先绝对路径 |

edit/chat 下的路径约定：以 \`/\` 开头的项目根相对形式（如 \`/src/index.ts\` 映射到 \`<cwd>/src/index.ts\`）。不要发明 shell 工具名——有则用 \`run_script\`。

## 设置（桌面 UI）

常见入口（具体文案可能随 UI 微调）：

- **提供商 / API 密钥** — 明文保存在 \`~/.hip/config/auth.json\`（按设计为 0600）
- **记忆** — 跨会话记忆**默认关闭**；在 设置 → 记忆 开启（见 \`references/memory.md\`）
- **技能** — 启用/禁用已安装技能（\`hip.toml\` + 技能目录）
- **插件** — 安装/启用插件（技能、智能体、MCP、钩子）；设置中有插件市场
- **智能体** — 固定配置（supervisor / plan / explore / coder）与自定义内部或外部智能体
- **网络策略** — 可选的出站工具允许/拒绝

## 右侧面板：Agents + Runtime

每个会话的右侧面板合并：

- **Agents** — 花名册、活跃子智能体、委派状态
- **Runtime** — 后台 shell、monitor、定时任务（TaskRuntime）。仍在运行的工作显示 chip；打开面板可查看输出或停止任务

长时间 shell、日志监视与周期检查应使用 TaskRuntime 工具（见 \`references/agents-and-plugins.md\` 与 \`hip-coding\` 技能）。不要在主回合里 sleep 轮询。

## 技能、插件、MCP

- **技能**：Claude 格式 \`SKILL.md\` 文件夹。全局：\`~/.hip/skills/<id>/\`。项目：\`.hip/skills/<id>/\`。渐进披露：L1 元数据 → \`use_skill\` 正文 → \`references/\` + \`assets/\`。
- **插件**：位于 \`~/.hip/plugins/\`；可贡献技能、智能体、MCP 与钩子。见 \`references/agents-and-plugins.md\`。
- **MCP**：配置的服务器暴露工具。Code 面系统提示可能列出目录；用 \`mcp_search\` 查找，再调用 \`mcp__<server>__<tool>\`。

## 智能体与委派

- 默认会话智能体决定何时用工具或委派。
- 有专用花名册时优先：**explore**（只读搜索）、**plan**（仅设计）、**coder**（带脚本实现）。
- 多个独立子任务 → 一次 \`task_batch\`（不要顺序多个 \`dispatch_agent\`）。
- 长时间 shell / CI / 周期工作 → TaskRuntime（\`run_script\` background、\`monitor\`、\`scheduler_*\`），避免阻塞主回合。
- 显式工作流 / 多智能体 handoff **不是**普通产品路径。
- 深入：\`references/agents-and-plugins.md\`。

## CLI（\`@hip/cli\`）

仅附着到**已运行**的 hip 应用（共享 sidecar 与 \`~/.hip\` 数据）。不会启动产品 sidecar。

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

应用未运行时 CLI 失败并返回 \`APP_NOT_RUNNING\`。

## 项目指导文件

项目中若存在 \`AGENTS.md\` / \`Claude.md\` / \`.hip\` 配置等，hip 可能注入。**项目**约定优先遵循那些文件；本技能描述**产品**行为。

## Level 3 参考

加载本技能后，\`use_skill\` 会返回绝对路径。需要深度时：

- 记忆启用、注入、抽取、隐私 → \`references/memory.md\`
- 本地数据布局、配置、环境变量 → \`references/config-and-data.md\`
- 常见故障（无密钥、CLI 未运行、记忆为空） → \`references/troubleshooting.md\`
- 智能体、插件、MCP、TaskRuntime 工具 → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip 记忆（Level 3）

跨会话记忆**默认关闭**（隐私 / 成本）。

## 启用

1. 打开 **设置 → 记忆**。
2. 开启 **使用** 和/或 **生成**。
3. 冷安装时若同时开启两者，可能在门控仍为默认时应用 dogfood 预设（更短空闲 / 抽取间隔）。
4. 确保已配置提供商 API 密钥（设置 → 提供商）。抽取需要 API 密钥。

## 存什么

SQLite（\`memory_items\`）中的结构化条目：偏好、约定、教训、工作流、档案 — 范围可为 **global**、**project** 或 **session**。

**真相源是 SQLite。** \`~/.hip/memories/\` 下 Markdown 是导出镜像。项目 \`MEMORY.md\` / \`.hip/MEMORY.md\` 是独立的项目笔记注入，不会自动导入 SQLite。

## 运行时行为

| 路径 | 行为 |
|------|------|
| **使用** | 核心快照 + 每轮预取 + \`memory_*\` 工具 |
| **生成** | 空闲后 → Phase1 抽取 → Phase2 巩固 |
| **隐身** | 会话标志：不注入、不抽取 |
| **立即学习** | 设置中的控件，dogfood 时强制抽取/巩固 |

托管子智能体可能只读注入核心；外部 ACP 智能体默认关闭。

## 隐私

- 冷默认：使用/生成关闭
- 混合检索（可选）可能向嵌入服务发送片段
- 写入时威胁扫描 + 密钥脱敏
- 软删除回收站 + 保留期
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip 配置与本地数据（Level 3）

## 布局（\`~/.hip/\`）

| 路径 | 用途 |
|------|------|
| \`~/.hip/config/auth.json\` | 提供商 API 密钥（0600 明文，按设计） |
| \`~/.hip/config/hip.toml\` | 全局产品配置（技能、agent loop 等） |
| \`~/.hip/config/memory.json\` | 记忆功能开关 / 流水线参数 |
| \`~/.hip/config/network.json\` | 可选网络策略 |
| \`~/.hip/config/hip-plugins.json\` | 已安装插件注册表 |
| \`~/.hip/db/hip.db\` | SQLite 会话、消息、记忆、事件 |
| \`~/.hip/data/tool-output/\` | 大型工具输出（不进 DB） |
| \`~/.hip/logs/\` | Sidecar / 壳日志 |
| \`~/.hip/skills/\` | 全局技能 |
| \`~/.hip/plugins/\` | 已安装插件 |
| \`~/.hip/memories/\` | 记忆 Markdown 镜像 |
| \`~/.hip/builtin-skills/\` | 内置渐进产品技能（如 \`hip\`） |
| | \`~/.hip/scratch/\` | 临时区助手 |

项目覆盖常在 \`<project>/.hip/\`（如 \`.hip/skills/\`、\`.hip/hip.toml\`）。

## 环境 / 隔离（进阶）

| 变量 | 作用 |
|------|------|
| \`HIP_DATA_DIR\` | 重定向数据/配置根（测试 / 隔离） |
| \`HIP_SKILLS_DIR\` | 覆盖全局技能根 |
| \`HIP_PLUGINS_DIR\` | 覆盖插件根 |
| \`HIP_AUTH_PATH\` | 覆盖 auth.json 路径 |
| \`HIP_CONFIG_PATH\` | 覆盖 hip.toml 路径 |
| \`HIP_MEMORY_CONFIG_PATH\` | 覆盖 memory.json 路径 |

**不要**把 \`~/.hip/config/\` 同步到公开云或公开 dotfile 仓库——可能含 API 密钥。

## 鉴权模型

密钥在应用设置中填写并写入 \`auth.json\`。桌面应用、独立 sidecar 与测试都从该存储读取。这是有意的磁盘明文 + 紧文件权限，不是钥匙串迁移目标。
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip 故障排查（Level 3）

## API / 模型调用失败

1. 打开 **设置 → 提供商**，确认已保存密钥。
2. 密钥在 \`~/.hip/config/auth.json\`（切勿向用户打印密钥）。
3. 在 UI 外改鉴权后请重启应用。
4. 查看 \`~/.hip/logs/\` 下 sidecar 日志。

## CLI：\`APP_NOT_RUNNING\`

产品 CLI 附着到**正在运行**的 hip 桌面应用。请先启动应用（\`yarn tauri dev\` 或已安装应用），再 \`yarn cli:dev doctor\`。

## 开启记忆后列表仍空

1. 确认 **设置 → 记忆** 中 **使用** / **生成** 符合预期。
2. 需要足够对话轮次 + API 密钥才能抽取；可试 **立即学习**。
3. 状态可能显示 \`no_llm\`、\`rate_limited\` 或空抽取 — 检查密钥 / 配额 / 等待。
4. SQLite 是真相源；\`~/.hip/memories/\` 镜像陈旧不等于库空。

## 智能体无法写文件

- 权限 **chat** 为只读。
- 默认 **edit** 沙箱在项目根 — 根外路径会失败。
- 仅当用户明确授权整机 FS 时使用 **full**。

## 技能未列出 / use_skill 失败

- 可能在 \`hip.toml\` 或插件中被禁用。
- 项目技能 \`paths\` 通配可能排除当前 cwd。
- 内置产品技能 id 为 \`hip\`，目录 \`~/.hip/builtin-skills/hip/\`。

## Sidecar / 连接问题

- 桌面壳启动 sidecar 并暴露其 WebSocket 端口。
- UI 连不上时重启应用；查看 \`~/.hip/logs/\`。
- 开发：工具链变更后用 \`yarn sidecar:dev-bin\` 重新生成 sidecar 包装。

## macOS 构建 DMG 残留

陈旧的 \`rw.*.dmg\` 挂载可能导致 \`yarn tauri build\` 失败；删除它们并卸除 \`/Volumes/hip\`（如有）。
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip 智能体、插件与 MCP（Level 3）

## 内置智能体配置

常见固定配置（在智能体 UI 中启用/禁用）：

| 配置 | 角色 |
|------|------|
| **supervisor** | 默认编排：工具、提交、脚本、委派 |
| **plan** | 偏设计 / 规划（写权限视配置收窄） |
| **explore** | 只读代码库搜索 |
| **coder** | 偏实现，可带脚本 |

自定义 **internal** 智能体：人设提示 + 绑定模型 + 工具授权。  
**外部 / ACP** 智能体：独立进程；产品记忆默认关闭（除非配置开启）。

支持的 ACP preset（设置 → 智能体 → 新增 ACP）：**OpenCode**、**Grok Build**（\`grok agent stdio\`）、**Pi**、**Claude Code**、**Codex**。Grok Build 为原生 ACP（安装见 \`https://x.ai/cli\`）；认证用 \`grok login\` 或可选 \`XAI_API_KEY\`。

ACP 智能体的认证与模型为**自管**：hip **不会**把自身 provider 的 API key 注入 ACP 子进程。请使用智能体自身登录 / 环境变量 / 预设可选的 \`authEnvVar\`。

## 能力矩阵（内置 vs ACP）

hip 可运行 **内置** LangGraph 智能体、将 **ACP 作为会话主智能体**，或 **派发 ACP 作为子智能体**。能力不同（当前产品；规划中的 host 能力另行标注）：

| 能力 | 内置主智能体 | ACP 主智能体 | ACP 子智能体（dispatch） |
|------|--------------|--------------|--------------------------|
| hip 内置工具（read / write / run_script …） | 有 | 无（智能体自有工具） | 无（智能体自有工具） |
| hip Skills / 插件钩子 | 有 | 无 | 无 |
| hip MCP（会话内合并） | 有 | 无（规划：opt-in 转发） | 无（规划：opt-in 转发） |
| 客户端 FS bridge | 不适用 | 无（仅 stub；真实 bridge 规划中） | 无（仅 stub；真实 bridge 规划中） |
| dispatch / task / task_batch | 有 | 无 | 无 |
| TaskRuntime（后台 shell / monitor / scheduler） | 有 | 无 | 无 |
| 跨会话 Memory 注入 | 有 | 无（配置项预留；前缀规划中） | 无 |
| Memory 抽取 | 有 | 无 | 无 |
| hip 模型选择器 | 有 | 无（用 agent configOptions / 智能体侧模型 UI） | 无 |
| HITL 权限 | hip 工具门禁 | ACP \`requestPermission\` | 同 ACP 主智能体 |
| permissionMode | hip 工具门禁 | chat/edit 下安全 kind（read/fetch/other）自动放行；其余 HITL（ACP 路径上 \`full\` 亦为 HITL） | 继承父会话 mode |

**要点：** 选 ACP 作主智能体时，它是对等的编程智能体栈，**不是** hip 内置工具/技能/MCP。子智能体派发使用同一工具栈；主智能体与子智能体目前均无 hip memory 注入或 hip MCP。

## 委派与 TaskRuntime 工具（主智能体）

| 工具 | 用途 |
|------|------|
| \`task\` | 单个子任务（前台或后台） |
| \`dispatch_agent\` | 命名花名册智能体；阻塞，除非同批多个调用 |
| \`task_batch\` | **2+ 独立子任务的首选**（真并行） |
| \`run_script\`（+ \`background:true\`） | Shell；长任务返回 \`task_id\` |
| \`wait_tasks\` | 等待一个或多个后台 task id |
| \`task_output\` | 读取目前输出（shell / agent / monitor） |
| \`task_stop\` | 停止运行中的后台任务 |
| \`monitor\` | 将 stdout 流式到 UI 事件（**不会**自动注入模型上下文） |
| \`scheduler_create\` / \`scheduler_list\` / \`scheduler_delete\` | 周期唤醒（最短间隔 60s） |

若只用顺序 dispatch，不要声称「并行」完成。  
长 shell / CI 不要在主回合 sleep 轮询——使用上表 TaskRuntime 工具。

### Runtime 面板（UI）

会话右侧面板合并 **Agents**（花名册 / 子智能体）与 **Runtime**（后台 shell、monitor、定时任务）。仍在运行的工作显示 chip；打开 Runtime 可查看或停止任务。

## 插件

- 安装于 \`~/.hip/plugins/\`；注册表在 \`~/.hip/config/hip-plugins.json\`。
- 插件可附带技能、智能体、MCP 配置与钩子。
- 禁用插件会从会话中移除其贡献。

### 插件市场（设置）

hip 的插件市场页**仅**集成官方目录：

| Source id | 目录 |
|-----------|------|
| \`grok-official\` | [xai-org/plugin-marketplace](https://github.com/xai-org/plugin-marketplace) |
| \`claude-official\` | [anthropics/claude-plugins-official](https://github.com/anthropics/claude-plugins-official) |

UI 标签：**Grok market** · **Claude market** · **Custom plugins**（无官方来源的本地安装）。

- 目录缓存：\`~/.hip/cache/marketplaces/<sourceId>/\`
- 源开关：\`~/.hip/config/marketplace-sources.json\`
- 市场**下载**默认 \`enabled: false\`（已下载未启用）。
- 下载时 sidecar **审查** agent \`boundModel\`；不可用模型会改写为产品默认（hip.toml 的 \`activeModel\`）。
- 打开插件开关后注入技能/MCP/智能体（\`plugin:reload\`）。

### 插件目录结构

每个插件**必须**包含 \`.plugin/plugin.json\` 清单文件。缺少此文件 hip 无法发现插件：

\`\`\`
~/.hip/plugins/<plugin-id>/
  .plugin/
    plugin.json          ← 必需：清单文件（名称、版本、技能等）
  skills/                ← 可选，由清单中 "skills" 字段引用
    <skill-id>/
      SKILL.md
\`\`\`

### \`.plugin/plugin.json\` 清单

**必填字段：**

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0"
}
\`\`\`

**完整示例**（含所有可选字段）：

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0",
  "id": "my-plugin",
  "description": "一个 hip 插件示例",
  "author": { "name": "作者名" },
  "license": "MIT",
  "keywords": ["ai", "tools"],
  "skills": ["./skills/tdd", "./skills/debug"],
  "mcpServers": "./mcp-config.json",
  "agents": "./agents.json",
  "hooks": "./hooks.json"
}
\`\`\`

- \`skills\` — 指向包含 \`SKILL.md\` 文件的目录的路径（或路径数组）。路径相对于插件根目录，不可使用 \`..\`。
- \`mcpServers\`、\`agents\`、\`hooks\` — 可内联指定为 JSON 数组/对象，或指定为插件根目录下外部 JSON 文件的路径。

### \`hip-plugins.json\` 注册表格式

注册表将插件 ID 映射到绝对路径。支持两种格式：

**字符串数组格式**（新插件推荐使用）：
\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

**旧版对象格式**（使用 \`"dir"\` 键）：
\`\`\`json
{
  "plugins": [
    { "dir": "/absolute/path/to/plugin", "enabled": true }
  ]
}
\`\`\`

安装插件的步骤：

1. 将插件克隆/下载到 \`~/.hip/plugins/<plugin-id>/\`。
2. 确保 \`.plugin/plugin.json\` 存在，至少包含 \`name\` 和 \`version\`。
3. 将绝对路径添加到 \`hip-plugins.json\` → \`plugins\` 数组（字符串格式）。
4. 插件将在下次会话启动或执行 \`plugin:reload\` 后被加载。

## MCP

- 服务器配置来自 hip.toml / 插件合成。
- Code 面可能注入短目录；用 \`mcp_search\` 发现。
- 调用形式：\`mcp__<server>__<tool>\`。
- 若配置了网络策略，可能拦截出站 MCP/web 工具。

## 技能作用域

| 作用域 | 位置 |
|--------|------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\`（同 id 覆盖 global） |
| plugin | 插件自有技能目录 |
| 内置产品 | \`~/.hip/builtin-skills/hip/\`（优先级最低；可被同 id 覆盖） |
`,
  }
  ],
},
  'zh-TW': {
  description: 'hip 桌面智能體產品說明：Chat/Code/Knowledge 介面、權限模式、Agents+Runtime 面板、設定、技能、外掛、MCP、記憶、智能體、CLI、故障排除與本機資料配置。當使用者詢問 hip 如何運作或如何設定時載入。',
  capabilityMap: `產品要點（hip）：
- 版本：1.0.1。
- 桌面 AI 工作台智能體，在使用者專案中使用真實檔案工具，並可委派子智能體。
- 介面：Code（完整工作台）與 Chat（較輕；可預覽交付物請 write_file 到工件面板）與 Knowledge（筆記空間）。
- 僅在 Code 上，工具門禁（UI 標籤）：chat = 唯讀；edit = 專案沙箱（預設）；full = 使用者授權的整機檔案系統。Chat 介面不是 Code 的「edit 模式」。
- 工作階段右側面板：Agents（名冊 / 子智能體）與 Runtime（後台 shell、monitor、排程）合併檢視。
- API 金鑰：~/.hip/config/auth.json（依設計為 0600 明文）。
- 跨工作階段記憶：預設關閉（設定 → 記憶）。
- 本機資料：~/.hip/（設定、資料庫、技能、外掛、日誌）。`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip 是一款**桌面 AI 工作台**（Tauri 殼 + React UI + Node sidecar），產品版本 **1.0.1**。每個 UI 分頁是獨立工作階段。預設產品迴路是 **Supervisor ReAct** 智能體：用工具完成工作，並可透過 \`task\` / \`dispatch_agent\` / \`task_batch\` 委派——一般回合**不會**強制 Planner → Coder → Reviewer 流水線。

本技能是 *hip 產品本身* 的權威指南。使用者專案中的一般編碼任務**不要**載入本技能。

用**使用者的語言**回答產品問題，但設定路徑與識別符請保持原文準確。

## 漸進式揭露

- **Level 1**（系統提示 Skills 列表）：僅名稱 + 描述
- **Level 2**（本檔）：下方概覽，透過 \`use_skill({ name: "hip" })\` 載入
- **Level 3**：\`references/\` 中的深入主題——需要時用 \`read_file\` 讀絕對路徑

若某產品細節未寫在此處，請如實說明，不要編造 UI 文案或設定鍵。

## 介面（Surfaces）

| 介面 | 用途 |
|------|------|
| **Code** | 專案工作台：檔案工具、git 指導、MCP 目錄、完整智能體工具、非同步 TaskRuntime |
| **Chat** | 較輕的對話面：更短提示、無 git 提交指導；可預覽交付物請 \`write_file\` 到工作區以便工件面板展示 |
| **Knowledge** | 筆記 / 知識空間助手：依使用者筆記作答；不是軟體專案的編碼智能體 |

介面在 UI 中選擇；系統提示會反映目前介面。

## 權限模式

| 模式 | 效果 |
|------|------|
| **edit**（預設） | 檔案系統工具限制在專案根沙箱內 |
| **chat** | 唯讀：不能寫/改檔案，不能跑腳本 |
| **full** | 未沙箱的檔案系統（使用者明確授權）；優先絕對路徑 |

edit/chat 下的路徑約定：以 \`/\` 開頭的專案根相對形式。不要發明 shell 工具名——有則用 \`run_script\`。

## 設定（桌面 UI）

常見入口（具體文案可能隨 UI 微調）：

- **提供者 / API 金鑰** — 明文保存在 \`~/.hip/config/auth.json\`（依設計為 0600）
- **記憶** — 跨工作階段記憶**預設關閉**；在 設定 → 記憶 開啟（見 \`references/memory.md\`）
- **技能** — 啟用/停用已安裝技能
- **外掛** — 安裝/啟用外掛（技能、智能體、MCP、掛鉤）；設定中有外掛市集
- **智能體** — 固定設定（supervisor / plan / explore / coder）與自訂內部或外部智能體
- **網路原則** — 可選的出站工具允許/拒絕

## 右側面板：Agents + Runtime

每個工作階段的右側面板合併：

- **Agents** — 名冊、活躍子智能體、委派狀態
- **Runtime** — 後台 shell、monitor、排程（TaskRuntime）。仍在執行的工作顯示 chip；開啟面板可檢視輸出或停止任務

長時間 shell、日誌監視與週期檢查應使用 TaskRuntime 工具。不要在主回合 sleep 輪詢。

## 技能、外掛、MCP

- **技能**：Claude 格式 \`SKILL.md\` 資料夾。全域：\`~/.hip/skills/<id>/\`。專案：\`.hip/skills/<id>/\`。
- **外掛**：位於 \`~/.hip/plugins/\`；可貢獻技能、智能體、MCP 與掛鉤。見 \`references/agents-and-plugins.md\`。
- **MCP**：用 \`mcp_search\` 後呼叫 \`mcp__<server>__<tool>\`。

## 智能體與委派

- 預設工作階段智能體決定何時用工具或委派。
- 有專用名冊時優先：**explore**、**plan**、**coder**。
- 多個獨立子任務 → 一次 \`task_batch\`。
- 長時間 shell / CI / 週期工作 → TaskRuntime（\`run_script\` background、\`monitor\`、\`scheduler_*\`）。
- 深入：\`references/agents-and-plugins.md\`。

## CLI（\`@hip/cli\`）

僅附著到**已執行**的 hip 應用（共享 sidecar 與 \`~/.hip\` 資料）。不會啟動產品 sidecar。

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

應用未執行時 CLI 失敗並回傳 \`APP_NOT_RUNNING\`。

## 專案指導檔

專案中若存在 \`AGENTS.md\` / \`Claude.md\` / \`.hip\` 等，hip 可能注入。**專案**約定優先；本技能描述**產品**行為。

## Level 3 參考

- 記憶 → \`references/memory.md\`
- 本機資料與設定 → \`references/config-and-data.md\`
- 疑難排解 → \`references/troubleshooting.md\`
- 智能體、外掛、MCP、TaskRuntime → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip 記憶（Level 3）

跨工作階段記憶**預設關閉**（隱私 / 成本）。

## 啟用

1. 開啟 **設定 → 記憶**。
2. 開啟 **使用** 和/或 **產生**。
3. 冷安裝時若同時開啟兩者，可能套用 dogfood 預設（更短閒置 / 抽取間隔）。
4. 確保已設定提供者 API 金鑰。抽取需要 API 金鑰。

## 存什麼

SQLite（\`memory_items\`）結構化條目：偏好、約定、教訓、工作流程、檔案 — 範圍 **global** / **project** / **session**。

**真相來源是 SQLite。** \`~/.hip/memories/\` 下 Markdown 是匯出鏡像。

## 執行時行為

| 路徑 | 行為 |
|------|------|
| **使用** | 核心快照 + 每輪預取 + \`memory_*\` 工具 |
| **產生** | 閒置後 → Phase1 抽取 → Phase2 鞏固 |
| **隱身** | 工作階段旗標：不注入、不抽取 |
| **立即學習** | 設定中的控制項，強制抽取/鞏固 |

## 隱私

- 冷預設：使用/產生關閉
- 混合檢索（可選）可能向嵌入服務傳送片段
- 寫入時威脅掃描 + 金鑰脫敏
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip 設定與本機資料（Level 3）

## 配置（\`~/.hip/\`）

| 路徑 | 用途 |
|------|------|
| \`~/.hip/config/auth.json\` | 提供者 API 金鑰（0600 明文，依設計） |
| \`~/.hip/config/hip.toml\` | 全域產品設定 |
| \`~/.hip/config/memory.json\` | 記憶功能開關 |
| \`~/.hip/config/network.json\` | 可選網路原則 |
| \`~/.hip/config/hip-plugins.json\` | 已安裝外掛登錄 |
| \`~/.hip/db/hip.db\` | SQLite 工作階段、訊息、記憶、事件 |
| \`~/.hip/data/tool-output/\` | 大型工具輸出 |
| \`~/.hip/logs/\` | Sidecar / 殼日誌 |
| \`~/.hip/skills/\` | 全域技能 |
| \`~/.hip/plugins/\` | 已安裝外掛 |
| \`~/.hip/memories/\` | 記憶 Markdown 鏡像 |
| \`~/.hip/builtin-skills/\` | 內建漸進產品技能（如 \`hip\`） |

**不要**把 \`~/.hip/config/\` 同步到公開雲或公開 dotfile 倉庫。

## 環境變數（進階）

\`HIP_DATA_DIR\`、\`HIP_SKILLS_DIR\`、\`HIP_PLUGINS_DIR\`、\`HIP_AUTH_PATH\`、\`HIP_CONFIG_PATH\`、\`HIP_MEMORY_CONFIG_PATH\`。
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip 故障排除（Level 3）

## API / 模型呼叫失敗

1. 開啟 **設定 → 提供者**，確認已儲存金鑰。
2. 金鑰在 \`~/.hip/config/auth.json\`（切勿向使用者列印金鑰）。
3. 在 UI 外改鑑權後請重新啟動應用。
4. 查看 \`~/.hip/logs/\`。

## CLI：\`APP_NOT_RUNNING\`

請先啟動 hip 桌面應用，再執行 \`yarn cli:dev doctor\`。

## 開啟記憶後列表仍空

確認使用/產生開關、對話輪次、API 金鑰；可試 **立即學習**。SQLite 是真相來源。

## 智能體無法寫檔

- **chat** 唯讀；**edit** 沙箱在專案根；**full** 需使用者明確授權。

## 技能未列出

可能在 \`hip.toml\` 停用；內建產品技能 id 為 \`hip\`（\`~/.hip/builtin-skills/hip/\`）。

## Sidecar 連線

重新啟動應用；開發時工具鏈變更後執行 \`yarn sidecar:dev-bin\`。
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip 智能體、外掛與 MCP（Level 3）

## 內建智能體設定

常見固定設定（在智能體 UI 中啟用/停用）：

| 設定 | 角色 |
|------|------|
| **supervisor** | 預設編排：工具、提交、腳本、委派 |
| **plan** | 偏設計 / 規劃 |
| **explore** | 唯讀程式庫搜尋 |
| **coder** | 偏實作，可帶腳本 |

**內部**智能體：人設 + 綁定模型 + 工具授權。  
**外部 / ACP**：獨立行程；產品記憶預設關閉。

支援的 ACP preset（設定 → 智能體 → 新增 ACP）：**OpenCode**、**Grok Build**（\`grok agent stdio\`）、**Pi**、**Claude Code**、**Codex**。Grok Build 為原生 ACP（安裝見 \`https://x.ai/cli\`）；認證用 \`grok login\` 或可選 \`XAI_API_KEY\`。

ACP 智能體的認證與模型為**自管**：hip **不會**將自身 provider 的 API key 注入 ACP 子行程。

## 能力矩陣（內建 vs ACP）

| 能力 | 內建主智能體 | ACP 主智能體 | ACP 子智能體（dispatch） |
|------|--------------|--------------|--------------------------|
| hip 內建工具（read / write / run_script …） | 有 | 無（智能體自有工具） | 無 |
| hip Skills / 外掛鉤子 | 有 | 無 | 無 |
| hip MCP | 有 | 無（規劃：opt-in 轉發） | 無 |
| 用戶端 FS bridge | 不適用 | 無（僅 stub） | 無 |
| dispatch / task / task_batch | 有 | 無 | 無 |
| TaskRuntime（後台 shell / monitor / scheduler） | 有 | 無 | 無 |
| 跨工作階段 Memory 注入 | 有 | 無 | 無 |
| Memory 擷取 | 有 | 無 | 無 |
| hip 模型選擇器 | 有 | 無 | 無 |
| HITL 權限 | hip 工具門禁 | ACP \`requestPermission\` | 同 ACP 主智能體 |
| permissionMode | hip 工具門禁 | chat/edit 安全 kind 自動放行；其餘 HITL | 繼承父工作階段 |

**重點：** 選 ACP 作主智能體時，它是對等程式智能體堆疊，**不是** hip 內建工具／技能／MCP。

## 委派與 TaskRuntime 工具（主智能體）

| 工具 | 用途 |
|------|------|
| \`task\` | 單個子任務（前台或後台） |
| \`dispatch_agent\` | 名冊智能體（通常阻塞） |
| \`task_batch\` | **2+ 獨立子任務首選**（真平行） |
| \`run_script\`（+ \`background:true\`） | Shell；長任務回傳 \`task_id\` |
| \`wait_tasks\` | 等待一個或多個後台 task id |
| \`task_output\` | 讀取目前輸出 |
| \`task_stop\` | 停止後台任務 |
| \`monitor\` | stdout 串流為 UI 事件（**不**自動注入模型） |
| \`scheduler_create\` / \`scheduler_list\` / \`scheduler_delete\` | 週期喚醒（最短 60s） |

不要在主回合 sleep 輪詢長 shell / CI。

### Runtime 面板（UI）

工作階段右側面板合併 **Agents** 與 **Runtime**。仍在執行的工作顯示 chip。

## 外掛

- 安裝於 \`~/.hip/plugins/\`；登錄 \`~/.hip/config/hip-plugins.json\`。
- 外掛可附帶技能、智能體、MCP、掛鉤。

### 外掛市集（設定）

僅整合官方目錄：

| Source id | 目錄 |
|-----------|------|
| \`grok-official\` | [xai-org/plugin-marketplace](https://github.com/xai-org/plugin-marketplace) |
| \`claude-official\` | [anthropics/claude-plugins-official](https://github.com/anthropics/claude-plugins-official) |

UI：**Grok market** · **Claude market** · **Custom plugins**。

- 快取：\`~/.hip/cache/marketplaces/<sourceId>/\`
- 源開關：\`~/.hip/config/marketplace-sources.json\`
- 下載預設 \`enabled: false\`；下載時會審查 \`boundModel\`。
- 開啟開關後注入貢獻（\`plugin:reload\`）。

### 外掛目錄結構

每個外掛**必須**有 \`.plugin/plugin.json\`：

\`\`\`
~/.hip/plugins/<plugin-id>/
  .plugin/
    plugin.json
  skills/
    <skill-id>/
      SKILL.md
\`\`\`

### \`.plugin/plugin.json\`

至少需要 \`name\`、\`version\`。可選：\`skills\`、\`mcpServers\`、\`agents\`、\`hooks\` 等。

### \`hip-plugins.json\`

建議字串陣列格式：

\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

## MCP

- 設定來自 hip.toml / 外掛合成。
- 用 \`mcp_search\`，再呼叫 \`mcp__<server>__<tool>\`。
- 網路原則可能封鎖出站 MCP/web。

## 技能作用域

| 作用域 | 位置 |
|--------|------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\`（同 id 覆蓋 global） |
| plugin | 外掛自有技能目錄 |
| 內建產品 | \`~/.hip/builtin-skills/hip/\`（優先權最低） |
`,
  }
  ],
},
  ja: {
  description: 'hip デスクトップエージェントの製品ヘルプ：Chat/Code/Knowledge サーフェス、権限モード、Agents+Runtime パネル、設定、スキル、プラグイン、MCP、メモリ、エージェント、CLI、トラブルシューティング、ローカルデータ。ユーザーが hip の仕組みや設定方法を尋ねたときに読み込みます。',
  capabilityMap: `製品の要点（hip）：
- バージョン：1.0.1。
- ユーザーのプロジェクトで実ファイルツールと任意のサブエージェントを使うデスクトップ作業台エージェント。
- サーフェス：Code（フル作業台）vs Chat（軽量；プレビュー可能な成果物は write_file でアーティファクト）vs Knowledge（ノート空間）。
- Code のみのツールゲート（UI ラベル）：chat = 読み取り専用；edit = プロジェクトサンドボックス（既定）；full = ユーザー許可の全 FS。Chat は Code の「edit モード」ではない。
- セッション右パネル：Agents（名簿 / サブエージェント）+ Runtime（バックグラウンド shell、monitor、スケジュール）の統合ビュー。
- API キー：~/.hip/config/auth.json（設計上 0600 平文）。
- クロスセッション記憶：既定オフ（設定 → メモリ）。
- ローカルデータ：~/.hip/（設定、DB、スキル、プラグイン、ログ）。`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip は**デスクトップ AI 作業台**（Tauri シェル + React UI + Node sidecar）、製品バージョン **1.0.1** です。各 UI タブは独立セッションです。既定の製品ループは **Supervisor ReAct** エージェントで、ツールを使い \`task\` / \`dispatch_agent\` / \`task_batch\` で委任できます。通常ターンに Planner → Coder → Reviewer 強制パイプラインはありません。

このスキルは *hip 製品そのもの* の公式ガイドです。ユーザープロジェクトの通常コーディングでは **読み込まない** でください。

製品の質問には**ユーザーの言語**で答え、設定パスと識別子は原文のまま正確に。

## 段階的開示

- **Level 1**（システムプロンプト Skills 一覧）：名前 + 説明のみ
- **Level 2**（本ファイル）：\`use_skill({ name: "hip" })\` で読み込む概要
- **Level 3**：\`references/\` — 必要時 \`read_file\` で絶対パスを読む

ここに無い製品詳細は創作せず「不明」と述べる。

## サーフェス

| サーフェス | 用途 |
|------------|------|
| **Code** | プロジェクト作業台：ファイルツール、git 指針、MCP カタログ、フルツール、非同期 TaskRuntime |
| **Chat** | 軽量会話：短いプロンプト、git コミット指針なし；プレビュー可能な成果物は \`write_file\` |
| **Knowledge** | ノート空間アシスタント；ソフトウェアプロジェクトのコーディングエージェントではない |

サーフェスは UI で選択；システムプロンプトが反映済み。

## 権限モード

| モード | 効果 |
|--------|------|
| **edit**（既定） | プロジェクトルートにサンドボックス |
| **chat** | 読み取り専用（書き込み/スクリプト不可） |
| **full** | サンドボックスなし（ユーザー許可）；絶対パス推奨 |

edit/chat のパスは \`/\` 始まりのプロジェクト相対。シェルツール名を発明せず \`run_script\` を使う。

## 設定（デスクトップ UI）

- **プロバイダ / API キー** — \`~/.hip/config/auth.json\`（0600 平文）
- **メモリ** — クロスセッションは**既定オフ**（設定 → メモリ）
- **スキル** — インストール済みスキルの有効/無効
- **プラグイン** — インストール/有効化；設定に Plugin Market
- **エージェント** — supervisor / plan / explore / coder とカスタム
- **ネットワークポリシー** — 出方向ツールの許可/拒否

## 右パネル：Agents + Runtime

セッション右パネルは次を統合：

- **Agents** — 名簿、サブエージェント、委任状態
- **Runtime** — バックグラウンド shell、monitor、スケジュール。実行中は chip 表示

長時間 shell / CI / 定期チェックは TaskRuntime ツールを使う。メインターンで sleep ポールしない。

## スキル・プラグイン・MCP

- **スキル**：\`SKILL.md\` フォルダ。グローバル \`~/.hip/skills/\`、プロジェクト \`.hip/skills/\`。
- **プラグイン**：\`~/.hip/plugins/\`。詳細は \`references/agents-and-plugins.md\`。
- **MCP**：\`mcp_search\` 後 \`mcp__<server>__<tool>\`。

## エージェントと委任

- 専用名簿を優先：explore / plan / coder。
- 独立サブタスク 2+ → 一度の \`task_batch\`。
- 長時間作業 → TaskRuntime（\`run_script\` background、\`monitor\`、\`scheduler_*\`）。
- 詳細：\`references/agents-and-plugins.md\`。

## CLI（\`@hip/cli\`）

**起動済み** hip アプリへのアタッチ専用（共有 sidecar + \`~/.hip\`）。製品 sidecar は起動しない。

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

アプリ未起動時は \`APP_NOT_RUNNING\`。

## プロジェクト指導ファイル

\`AGENTS.md\` / \`Claude.md\` / \`.hip\` があれば製品より**プロジェクト**規約を優先。

## Level 3 参照

- メモリ → \`references/memory.md\`
- 設定とデータ → \`references/config-and-data.md\`
- トラブルシュート → \`references/troubleshooting.md\`
- エージェント・プラグイン・MCP・TaskRuntime → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip メモリ (レベル 3)

セッションをまたぐメモリは**デフォルトで無効**です（プライバシー/コストのため）。

## 有効化

1. **設定 → メモリ** を開きます。
2. **使用** および/または **生成** を有効にします。
3. クリーンインストールから両方を有効にすると、ゲートがデフォルトのままの場合、ドッグフードプリセット（より短いアイドル時間/抽出間隔）が適用されることがあります。
4. プロバイダのAPIキーが設定されていることを確認します（設定 → プロバイダ）。抽出にはAPIキーが必要です。

## 保存される内容

SQLite（\`memory_items\`）内の構造化アイテム：設定、慣習、教訓、ワークフロー、プロファイル — スコープは**グローバル**、**プロジェクト**、または**セッション**です。

**信頼できる情報源はSQLiteです。** \`~/.hip/memories/\` 配下のMarkdownはエクスポートミラーです。プロジェクトの \`MEMORY.md\` / \`.hip/MEMORY.md\` は別のプロジェクトノート注入であり、SQLiteに自動インポートされません。

## ランタイムの動作

| パス | 動作 |
|------|----------|
| **使用** | コアスナップショット + ターンごとのプリフェッチ + \`memory_*\` ツール |
| **生成** | アイドル後 → フェーズ1抽出 → フェーズ2統合 |
| **シークレットモード** | セッションフラグ：注入も抽出も行わない |
| **今すぐ学習** | ドッグフーディング時に抽出/統合を強制する設定コントロール |

管理対象サブエージェントは読み取り専用のコア注入を受け取る場合があります。外部ACPエージェントはデフォルトでオフです。

## プライバシーに関する注意事項

- コールドデフォルト：使用/生成はオフ
- ハイブリッド検索（オプション）は、スニペットを埋め込みプロバイダに送信する場合があります
- 書き込み時の脅威スキャン + シークレット編集
- ソフトデリートのゴミ箱 + 保持期間
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip 設定 & ローカルデータ (レベル 3)

## レイアウト (\`~/.hip/\`)

| パス | 目的 |
|------|---------|
| \`~/.hip/config/auth.json\` | プロバイダAPIキー (設計上0600のプレーンテキスト) |
| \`~/.hip/config/hip.toml\` | グローバル製品設定 (スキル、エージェントループなど) |
| \`~/.hip/config/memory.json\` | メモリ機能フラグ / パイプラインノブ |
| \`~/.hip/config/network.json\` | オプションのネットワークポリシー |
| \`~/.hip/config/hip-plugins.json\` | インストール済みプラグインレジストリ |
| \`~/.hip/db/hip.db\` | SQLiteセッション、メッセージ、メモリ項目、イベント |
| \`~/.hip/data/tool-output/\` | 大きなツール出力 (DB外に保持) |
| \`~/.hip/logs/\` | サイドカー / シェルログ |
| \`~/.hip/skills/\` | グローバルスキル |
| \`~/.hip/plugins/\` | インストール済みプラグイン |
| \`~/.hip/memories/\` | メモリマークダウンミラー |
| \`~/.hip/builtin-skills/\` | 組み込みプログレッシブ製品スキル (例: この \`hip\` スキル) |
| | \`~/.hip/scratch/\` | スクラッチヘルパー |
| \`~/.hip/trash/\` | 製品ごみ箱 (知識FS隔離; セッションはSQLite経由でソフトデリート) |

### ごみ箱とソフトデリート

| 動作 | 備考 |
|----------|--------|
| UI削除 (チャット / コード / 知識) | ソフトデリート → サイドバー **ごみ箱** (履歴の上) |
| 保持期間 | デフォルト **7** 日; **設定 → 一般** または \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **完全な** ハードデリート (ごみ箱を経由しない) |
| メモリごみ箱 | 引き続き **設定 → メモリ** (別の保持期間、デフォルト30日) |

プロジェクトのオーバーライドは多くの場合 \`<プロジェクト>/.hip/\` に配置されます (例: \`.hip/skills/\`、\`.hip/hip.toml\`)。

## 環境変数 / 分離 (上級者向け)

| 変数 | 役割 |
|----------|------|
| \`HIP_DATA_DIR\` | データ/設定ルートのリダイレクト (テスト / 分離) |
| \`HIP_SKILLS_DIR\` | グローバルスキルルートのオーバーライド |
| \`HIP_PLUGINS_DIR\` | プラグルートのオーバーライド |
| \`HIP_AUTH_PATH\` | auth.jsonパスのオーバーライド |
| \`HIP_CONFIG_PATH\` | hip.tomlパスのオーバーライド |
| \`HIP_MEMORY_CONFIG_PATH\` | memory.jsonパスのオーバーライド |


\`~/.hip/config/\` をパブリッククラウドや公開ドットファイルリポジトリに同期**しないでください** — APIキーが含まれている可能性があります。

## 認証モデル

キーはアプリの設定パネルで入力され、\`auth.json\` に保存されます。デスクトップアプリ、スタンドアロンサイドカー、テストはすべてそのストアから読み取ります。これは意図的な設計で、厳格なファイルモードでディスク上にプレーンテキストとして保存されます — キーチェーンへの移行は対象外です。
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip トラブルシューティング (レベル 3)

## API / モデル呼び出しが動作しない

1. **設定 → プロバイダー** を開き、キーが保存されていることを確認します。
2. キーは \`~/.hip/config/auth.json\` に保存されています（シークレットをユーザーに表示しないでください）。
3. UI 外で認証情報を変更した場合は、アプリを再起動します。
4. \`~/.hip/logs/\` のサイドカーログを確認します。

## CLI: \`APP_NOT_RUNNING\`

製品 CLI は **実行中** の hip デスクトップアプリにアタッチします。最初にアプリを起動し（\`yarn tauri dev\` またはインストール済みアプリ）、その後 \`yarn cli:dev doctor\` を実行します。

## メモリ一覧が有効化後に空になる

1. **設定 → メモリ** で **使用** と **生成** が意図した通りに設定されていることを確認します。
2. 抽出には十分なチャットターン数と API キーが必要です。「今すぐ学習」を試してください。
3. ステータスが \`no_llm\`、\`rate_limited\`、または空の抽出結果を示す場合があります — キー/クォータを修正するか、待機してください。
4. SQLite が信頼できる情報源です。\`~/.hip/memories/\` 配下の古いミラーはデータベースではありません。

## エージェントがファイルを書き込めない

- **チャット** 権限モードは読み取り専用です。
- デフォルトの **編集** モードはプロジェクトルートにサンドボックス化されています — 外部のパスは失敗します。
- **フル** モードは、ユーザーが明示的にマシン全体のファイルシステムアクセスを許可した場合のみ使用します。

## スキルが一覧に表示されない / use_skill が失敗する

- スキルが \`hip.toml\` で無効化されているか、プラグインが無効化されている可能性があります。
- プロジェクトスキルの \`paths\` グロブがカレントワーキングディレクトリを除外している可能性があります。
- 組み込み製品スキル ID は \`hip\` で、\`~/.hip/builtin-skills/hip/\` にあります。

## サイドカー / 接続の問題

- デスクトップシェルがサイドカーを起動し、その WS ポートを公開します。
- UI が接続できない場合は、アプリを再起動し、\`~/.hip/logs/\` を確認します。
- 開発時: ツールチェーン変更後、\`yarn sidecar:dev-bin\` でサイドカーバイナリラッパーを再生成します。

## 古い DMG / ビルド (macOS)

古い \`rw.*.dmg\` マウントが \`yarn tauri build\` を妨げる可能性があります。それらを削除し、必要に応じて \`/Volumes/hip\` をアンマウントしてください。
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip エージェント、プラグイン & MCP（Level 3）

## 組み込みエージェントプロファイル

| プロファイル | 役割 |
|--------------|------|
| **supervisor** | 既定オーケストレータ：ツール、コミット、スクリプト、委任 |
| **plan** | 設計 / 計画向き |
| **explore** | 読み取り専用コード検索 |
| **coder** | 実装寄り（スクリプト可） |

**内部**エージェント：ペルソナ + モデル + ツール権限。  
**外部 / ACP**：別プロセス；製品メモリは既定オフ。

対応 ACP プリセット（設定 → エージェント → ACP 追加）：**OpenCode**、**Grok Build**（\`grok agent stdio\`）、**Pi**、**Claude Code**、**Codex**。Grok Build はネイティブ ACP（\`https://x.ai/cli\`）；認証は \`grok login\` または任意の \`XAI_API_KEY\`。

ACP の認証とモデルは**自己管理**：hip は provider API キーを ACP 子プロセスに注入しません。

## 機能マトリックス（組み込み vs ACP）

| 機能 | 組み込み primary | ACP primary | ACP サブ（dispatch） |
|------|------------------|-------------|----------------------|
| hip ツール（read / write / run_script …） | あり | なし | なし |
| hip Skills / プラグインフック | あり | なし | なし |
| hip MCP | あり | なし（計画: opt-in 転送） | なし |
| クライアント FS bridge | n/a | なし（stub） | なし |
| dispatch / task / task_batch | あり | なし | なし |
| TaskRuntime（bg shell / monitor / scheduler） | あり | なし | なし |
| クロスセッション Memory 注入 | あり | なし | なし |
| Memory 抽出 | あり | なし | なし |
| hip モデル選択 | あり | なし | なし |
| HITL | hip ツール | ACP \`requestPermission\` | 同 ACP primary |
| permissionMode | hip ゲート | chat/edit で安全 kind 自動；他は HITL | 親セッション継承 |

**要点:** ACP を primary にすると hip 組み込みツール/スキル/MCP ではなく、対等な別スタックになる。

## 委任 & TaskRuntime ツール（メインエージェント）

| ツール | 用途 |
|--------|------|
| \`task\` | 単一サブタスク（fg / background） |
| \`dispatch_agent\` | 名簿エージェント |
| \`task_batch\` | **2+ 独立サブタスク推奨**（真並列） |
| \`run_script\`（+ \`background:true\`） | シェル；長時間は \`task_id\` |
| \`wait_tasks\` | バックグラウンド id 待ち |
| \`task_output\` | これまでの出力を読む |
| \`task_stop\` | 実行中タスク停止 |
| \`monitor\` | stdout を UI イベントとして配信（モデルへ自動注入しない） |
| \`scheduler_create\` / \`list\` / \`delete\` | 定期起動（最短 60s） |

メインターンで長時間 shell/CI を sleep ポールしない。

### Runtime パネル（UI）

セッション右パネルは **Agents** と **Runtime** を統合。実行中は chip 表示。

## プラグイン

- 配置: \`~/.hip/plugins/\`；レジストリ \`~/.hip/config/hip-plugins.json\`。
- スキル、エージェント、MCP、フックを同梱可。

### Plugin Market（設定）

公式カタログのみ:

| Source id | Catalog |
|-----------|---------|
| \`grok-official\` | [xai-org/plugin-marketplace](https://github.com/xai-org/plugin-marketplace) |
| \`claude-official\` | [anthropics/claude-plugins-official](https://github.com/anthropics/claude-plugins-official) |

UI: **Grok market** · **Claude market** · **Custom plugins**。

- キャッシュ: \`~/.hip/cache/marketplaces/<sourceId>/\`
- ソース切替: \`~/.hip/config/marketplace-sources.json\`
- ダウンロード既定 \`enabled: false\`；\`boundModel\` をレビュー。

### プラグインディレクトリ

必須: \`.plugin/plugin.json\`（少なくとも \`name\` / \`version\`）。

### \`hip-plugins.json\`

推奨（文字列配列）:

\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

## MCP

- hip.toml / プラグイン合成。
- \`mcp_search\` 後 \`mcp__<server>__<tool>\`。
- ネットワークポリシーが出方向を遮断する場合あり。

## スキルスコープ

| スコープ | 場所 |
|----------|------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\` |
| plugin | プラグイン内 |
| builtin | \`~/.hip/builtin-skills/hip/\`（最低優先） |
`,
  }
  ],
},
  ko: {
  description: 'hip 데스크톱 에이전트 제품 도움말: Chat/Code/Knowledge 서피스, 권한 모드, Agents+Runtime 패널, 설정, 스킬, 플러그인, MCP, 메모리, 에이전트, CLI, 문제 해결, 로컬 데이터. 사용자가 hip 작동 방식이나 설정 방법을 물을 때 로드합니다.',
  capabilityMap: `제품 요약（hip）：
- 버전: 1.0.1.
- 사용자 프로젝트에서 실제 파일 도구와 선택적 서브에이전트를 쓰는 데스크톱 작업대 에이전트.
- 서피스: Code(전체 작업대) vs Chat(가벼움; 미리보기 산출물은 write_file로 아티팩트) vs Knowledge(노트 공간).
- Code에서만 도구 게이트(UI 라벨): chat = 읽기 전용; edit = 프로젝트 샌드박스(기본); full = 사용자 허용 전체 FS. Chat 서피스는 Code "edit 모드"가 아님.
- 세션 오른쪽 패널: Agents(명단/서브에이전트) + Runtime(백그라운드 shell, monitor, 스케줄) 통합 뷰.
- API 키: ~/.hip/config/auth.json (설계상 0600 평문).
- 교차 세션 메모리: 기본 꺼짐(설정 → 메모리).
- 로컬 데이터: ~/.hip/(설정, DB, 스킬, 플러그인, 로그).`,
  sections: [
  {
    id: 'overview',
    titleKey: 'settings.productHelp.sections.overview',
    markdown: `# hip

hip은 **데스크톱 AI 작업대**(Tauri 셸 + React UI + Node sidecar)이며 제품 버전 **1.0.1**입니다. 각 UI 탭은 독립 세션입니다. 기본 제품 루프는 **Supervisor ReAct** 에이전트로 도구를 쓰고 \`task\` / \`dispatch_agent\` / \`task_batch\`로 위임할 수 있습니다. 일반 턴에 Planner → Coder → Reviewer 강제 파이프라인은 없습니다.

이 스킬은 *hip 제품 자체*의 공식 가이드입니다. 사용자 프로젝트의 일반 코딩 작업에는 **로드하지 마세요**.

제품 질문은 **사용자 언어**로 답하고, 설정 경로·식별자는 원문 그대로 유지하세요.

## 점진적 공개

- **Level 1**(시스템 프롬프트 Skills 목록): 이름 + 설명만
- **Level 2**(이 파일): \`use_skill({ name: "hip" })\`로 로드
- **Level 3**: \`references/\` — 필요 시 \`read_file\`로 절대 경로 읽기

여기 없는 제품 세부사항은 지어내지 말고 모른다고 말하세요.

## 서피스

| 서피스 | 용도 |
|--------|------|
| **Code** | 프로젝트 작업대: 파일 도구, git 가이드, MCP 카탈로그, 전체 도구, 비동기 TaskRuntime |
| **Chat** | 가벼운 대화: 짧은 프롬프트, git 커밋 가이드 없음; 미리보기 산출물은 \`write_file\` |
| **Knowledge** | 노트 공간 어시스턴트; 소프트웨어 프로젝트 코딩 에이전트가 아님 |

서피스는 UI에서 선택되며 시스템 프롬프트에 반영됩니다.

## 권한 모드

| 모드 | 효과 |
|------|------|
| **edit**(기본) | 프로젝트 루트 샌드박스 |
| **chat** | 읽기 전용(쓰기/스크립트 불가) |
| **full** | 샌드박스 없음(사용자 허용); 절대 경로 권장 |

edit/chat 경로는 \`/\`로 시작하는 프로젝트 상대 형식. 셸 도구 이름을 만들지 말고 \`run_script\`를 사용.

## 설정(데스크톱 UI)

- **프로바이더 / API 키** — \`~/.hip/config/auth.json\`(0600 평문)
- **메모리** — 교차 세션 **기본 꺼짐**(설정 → 메모리)
- **스킬** — 설치된 스킬 활성/비활성
- **플러그인** — 설치/활성; 설정에 Plugin Market
- **에이전트** — supervisor / plan / explore / coder 및 커스텀
- **네트워크 정책** — 아웃바운드 도구 허용/거부

## 오른쪽 패널: Agents + Runtime

세션 오른쪽 패널은 다음을 합칩니다:

- **Agents** — 명단, 서브에이전트, 위임 상태
- **Runtime** — 백그라운드 shell, monitor, 스케줄. 실행 중 작업은 chip 표시

긴 shell / CI / 주기 작업은 TaskRuntime 도구를 쓰세요. 메인 턴에서 sleep 폴링하지 마세요.

## 스킬·플러그인·MCP

- **스킬**: \`SKILL.md\` 폴더. 전역 \`~/.hip/skills/\`, 프로젝트 \`.hip/skills/\`.
- **플러그인**: \`~/.hip/plugins/\`. 자세한 내용 \`references/agents-and-plugins.md\`.
- **MCP**: \`mcp_search\` 후 \`mcp__<server>__<tool>\`.

## 에이전트와 위임

- 전용 명단 우선: explore / plan / coder.
- 독립 서브태스크 2+ → 한 번의 \`task_batch\`.
- 장시간 작업 → TaskRuntime(\`run_script\` background, \`monitor\`, \`scheduler_*\`).
- 심화: \`references/agents-and-plugins.md\`.

## CLI（\`@hip/cli\`）

**실행 중인** hip 앱에만 연결(공유 sidecar + \`~/.hip\`). 제품 sidecar를 시작하지 않습니다.

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

앱이 없으면 \`APP_NOT_RUNNING\`.

## 프로젝트 가이드 파일

\`AGENTS.md\` / \`Claude.md\` / \`.hip\`가 있으면 **프로젝트** 규칙을 우선.

## Level 3 참고

- 메모리 → \`references/memory.md\`
- 설정과 데이터 → \`references/config-and-data.md\`
- 문제 해결 → \`references/troubleshooting.md\`
- 에이전트·플러그인·MCP·TaskRuntime → \`references/agents-and-plugins.md\`
`,
  },
  {
    id: 'memory',
    titleKey: 'settings.productHelp.sections.memory',
    markdown: `# hip 메모리 (레벨 3)

세션 간 메모리는 **기본적으로 비활성화**되어 있습니다 (개인정보 보호 / 비용).

## 활성화

1. **설정 → 메모리**를 엽니다.
2. **사용** 및/또는 **생성**을 활성화합니다.
3. 처음 설치 상태에서 둘 다 활성화하면 게이트가 기본값일 때 도그푸드 프리셋(더 짧은 유휴/추출 간격)이 적용될 수 있습니다.
4. 제공자 API 키가 설정되어 있는지 확인합니다 (설정 → 제공자). 추출에는 API 키가 필요합니다.

## 저장되는 내용

SQLite의 구조화된 항목(\`memory_items\`): 선호도, 규칙, 학습 내용, 워크플로우, 프로필 — 범위는 **전역**, **프로젝트**, 또는 **세션**입니다.

**진실 공급원은 SQLite입니다.** \`~/.hip/memories/\` 아래의 Markdown은 내보내기 미러입니다. 프로젝트 \`MEMORY.md\` / \`.hip/MEMORY.md\`는 별도의 프로젝트 노트 주입이며, SQLite로 자동 가져오지 않습니다.

## 런타임 동작

| 경로 | 동작 |
|------|----------|
| **사용** | 코어 스냅샷 + 턴별 프리페치 + \`memory_*\` 도구 |
| **생성** | 유휴 후 → 1단계 추출 → 2단계 통합 |
| **시크릿 모드** | 세션 플래그: 주입 및 추출 없음 |
| **지금 학습** | 도그푸딩 시 추출/통합을 강제하는 설정 제어 |

관리되는 하위 에이전트는 읽기 전용 코어 주입을 받을 수 있으며, 외부 ACP 에이전트는 기본적으로 꺼져 있습니다.

## 개인정보 보호 참고 사항

- 기본 설정: 사용/생성 꺼짐
- 하이브리드 검색(선택 사항)은 임베딩 제공자에게 스니펫을 보낼 수 있음
- 쓰기 시 위협 검사 + 비밀 정보 편집
- 소프트 삭제 휴지통 + 보존 기간
`,
  },
  {
    id: 'config',
    titleKey: 'settings.productHelp.sections.config',
    markdown: `# hip 설정 및 로컬 데이터 (레벨 3)

## 디렉터리 구조 (\`~/.hip/\`)

| 경로 | 용도 |
|------|---------|
| \`~/.hip/config/auth.json\` | 제공자 API 키 (설계상 0600 일반 텍스트) |
| \`~/.hip/config/hip.toml\` | 전역 제품 설정 (스킬, 에이전트 루프 등) |
| \`~/.hip/config/memory.json\` | 메모리 기능 플래그 / 파이프라인 설정값 |
| \`~/.hip/config/network.json\` | 선택적 네트워크 정책 |
| \`~/.hip/config/hip-plugins.json\` | 설치된 플러그인 레지스트리 |
| \`~/.hip/db/hip.db\` | SQLite 세션, 메시지, 메모리 항목, 이벤트 |
| \`~/.hip/data/tool-output/\` | 대용량 도구 출력 (DB 외부 보관) |
| \`~/.hip/logs/\` | 사이드카 / 셸 로그 |
| \`~/.hip/skills/\` | 전역 스킬 |
| \`~/.hip/plugins/\` | 설치된 플러그인 |
| \`~/.hip/memories/\` | 메모리 마크다운 미러 |
| \`~/.hip/builtin-skills/\` | 내장 점진적 제품 스킬 (예: 이 \`hip\` 스킬) |
| \`~/.hip/scratch/\`, 작업 트리 | 임시 / 병렬 작업 트리 도우미 |
| \`~/.hip/trash/\` | 제품 휴지통 (지식 FS 격리, 세션은 SQLite를 통해 소프트 삭제) |

### 휴지통 및 소프트 삭제

| 동작 | 참고 |
|----------|--------|
| UI 삭제 (채팅 / 코드 / 지식) | 소프트 삭제 → 사이드바 **휴지통** (기록 위) |
| 보관 기간 | 기본 **7**일, **설정 → 일반** 또는 \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **영구** 하드 삭제 (휴지통 미사용) |
| 메모리 휴지통 | 여전히 **설정 → 메모리** (별도 보관 기간, 기본 30일) |

프로젝트 재정의는 보통 \`<프로젝트>/.hip/\` 아래에 위치합니다 (예: \`.hip/skills/\`, \`.hip/hip.toml\`).

## 환경 변수 / 격리 (고급)

| 변수 | 역할 |
|----------|------|
| \`HIP_DATA_DIR\` | 데이터/설정 루트 리디렉션 (테스트 / 격리) |
| \`HIP_SKILLS_DIR\` | 전역 스킬 루트 재정의 |
| \`HIP_PLUGINS_DIR\` | 플러그인 루트 재정의 |
| \`HIP_AUTH_PATH\` | auth.json 경로 재정의 |
| \`HIP_CONFIG_PATH\` | hip.toml 경로 재정의 |
| \`HIP_MEMORY_CONFIG_PATH\` | memory.json 경로 재정의 |


**\`~/.hip/config/\`를** 퍼블릭 클라우드나 공개 dotfile 저장소에 동기화하지 마십시오 — API 키가 포함될 수 있습니다.

## 인증 모델

키는 앱 설정 패널에서 입력되며 \`auth.json\`에 저장됩니다. 데스크톱 앱, 독립형 사이드카, 테스트 모두 해당 저장소에서 읽습니다. 이는 의도적인 일반 텍스트 디스크 저장 방식이며 엄격한 파일 모드가 적용됩니다 — 키체인 마이그레이션 대상이 아닙니다.
`,
  },
  {
    id: 'troubleshooting',
    titleKey: 'settings.productHelp.sections.troubleshooting',
    markdown: `# hip 문제 해결 (레벨 3)

## API / 모델 호출이 작동하지 않음

1. **설정 → 제공자**를 열고 키가 저장되어 있는지 확인하세요.
2. 키는 \`~/.hip/config/auth.json\`에 저장됩니다 (사용자에게 비밀을 출력하지 않음).
3. UI 외부에서 인증을 변경한 후 앱을 다시 시작하세요.
4. \`~/.hip/logs/\`에서 사이드카 로그를 확인하세요.

## CLI: \`APP_NOT_RUNNING\`

제품 CLI는 **실행 중인** hip 데스크톱 앱에 연결됩니다. 먼저 앱을 시작한 후(\`yarn tauri dev\` 또는 설치된 앱), \`yarn cli:dev doctor\`를 실행하세요.

## 메모리 목록 활성화 후 비어 있음

1. **설정 → 메모리**에서 **사용** 및 **생성**이 의도한 대로 설정되어 있는지 확인하세요.
2. 추출을 위해 충분한 채팅 횟수와 API 키가 필요합니다. **지금 학습**을 시도해보세요.
3. 상태가 \`no_llm\`, \`rate_limited\` 또는 빈 추출을 표시할 수 있습니다 — 키/할당량을 수정하거나 대기하세요.
4. SQLite가 진실 공급원이며, \`~/.hip/memories/\` 아래의 오래된 미러는 DB가 아닙니다.

## 에이전트가 파일을 쓸 수 없음

- **채팅** 권한 모드는 읽기 전용입니다.
- 기본 **편집** 모드는 프로젝트 루트로 샌드박싱됩니다 — 외부 경로는 실패합니다.
- 사용자가 명시적으로 전체 시스템 파일 시스템 접근을 허용한 경우에만 **전체**를 사용하세요.

## 스킬이 나열되지 않음 / use_skill 실패

- \`hip.toml\`에서 스킬이 비활성화되었거나 플러그인이 비활성화되었을 수 있습니다.
- 프로젝트 스킬 \`paths\` 글로브가 현재 작업 디렉토리를 제외할 수 있습니다.
- 내장 제품 스킬 ID는 \`~/.hip/builtin-skills/hip/\` 아래의 \`hip\`입니다.

## 사이드카 / 연결 문제

- 데스크톱 셸이 사이드카를 생성하고 WS 포트를 노출합니다.
- UI가 연결할 수 없는 경우 앱을 다시 시작하고 \`~/.hip/logs/\`를 확인하세요.
- 개발: 도구 체인 변경 후 \`yarn sidecar:dev-bin\`으로 사이드카 바이너리 래퍼를 다시 생성하세요.

## 오래된 DMG / 빌드 (macOS)

오래된 \`rw.*.dmg\` 마운트가 \`yarn tauri build\`를 중단시킬 수 있습니다. 필요한 경우 이를 제거하고 \`/Volumes/hip\`을 분리하세요.
`,
  },
  {
    id: 'agents',
    titleKey: 'settings.productHelp.sections.agents',
    markdown: `# hip 에이전트, 플러그인 & MCP（Level 3）

## 내장 에이전트 프로필

| 프로필 | 역할 |
|--------|------|
| **supervisor** | 기본 오케스트레이터: 도구, 커밋, 스크립트, 위임 |
| **plan** | 설계 / 계획 중심 |
| **explore** | 읽기 전용 코드 검색 |
| **coder** | 구현 중심(스크립트 가능) |

**내부** 에이전트: 페르소나 + 모델 + 도구 권한.  
**외부 / ACP**: 별도 프로세스; 제품 메모리는 기본 꺼짐.

지원 ACP 프리셋(설정 → 에이전트 → ACP 추가): **OpenCode**, **Grok Build**(\`grok agent stdio\`), **Pi**, **Claude Code**, **Codex**. Grok Build는 네이티브 ACP(\`https://x.ai/cli\`); 인증은 \`grok login\` 또는 선택적 \`XAI_API_KEY\`.

ACP 인증·모델은 **자체 관리**: hip은 provider API 키를 ACP 자식 프로세스에 주입하지 않습니다.

## 기능 매트릭스(내장 vs ACP)

| 기능 | 내장 primary | ACP primary | ACP 서브(dispatch) |
|------|--------------|-------------|---------------------|
| hip 도구(read / write / run_script …) | 있음 | 없음 | 없음 |
| hip Skills / 플러그인 훅 | 있음 | 없음 | 없음 |
| hip MCP | 있음 | 없음(계획: opt-in 전달) | 없음 |
| 클라이언트 FS bridge | n/a | 없음(stub) | 없음 |
| dispatch / task / task_batch | 있음 | 없음 | 없음 |
| TaskRuntime(bg shell / monitor / scheduler) | 있음 | 없음 | 없음 |
| 교차 세션 Memory 주입 | 있음 | 없음 | 없음 |
| Memory 추출 | 있음 | 없음 | 없음 |
| hip 모델 선택 | 있음 | 없음 | 없음 |
| HITL | hip 도구 | ACP \`requestPermission\` | ACP primary와 동일 |
| permissionMode | hip 게이트 | chat/edit 안전 kind 자동; 그 외 HITL | 부모 세션 상속 |

**요약:** ACP를 primary로 쓰면 hip 내장 도구/스킬/MCP가 아닌 대등한 별도 스택입니다.

## 위임 & TaskRuntime 도구(메인 에이전트)

| 도구 | 용도 |
|------|------|
| \`task\` | 단일 서브태스크(fg / background) |
| \`dispatch_agent\` | 명단 에이전트 |
| \`task_batch\` | **독립 서브태스크 2+ 권장**(진짜 병렬) |
| \`run_script\`(+ \`background:true\`) | 셸; 장시간 → \`task_id\` |
| \`wait_tasks\` | 백그라운드 id 대기 |
| \`task_output\` | 지금까지 출력 읽기 |
| \`task_stop\` | 실행 중 태스크 중지 |
| \`monitor\` | stdout를 UI 이벤트로 스트리밍(모델에 자동 주입 안 함) |
| \`scheduler_create\` / \`list\` / \`delete\` | 주기 깨우기(최소 60s) |

메인 턴에서 긴 shell/CI를 sleep 폴링하지 마세요.

### Runtime 패널(UI)

세션 오른쪽 패널은 **Agents**와 **Runtime**을 합칩니다. 실행 중 작업은 chip으로 표시됩니다.

## 플러그인

- 위치: \`~/.hip/plugins/\`; 레지스트리 \`~/.hip/config/hip-plugins.json\`.
- 스킬, 에이전트, MCP, 훅 포함 가능.

### Plugin Market(설정)

공식 카탈로그만:

| Source id | Catalog |
|-----------|---------|
| \`grok-official\` | [xai-org/plugin-marketplace](https://github.com/xai-org/plugin-marketplace) |
| \`claude-official\` | [anthropics/claude-plugins-official](https://github.com/anthropics/claude-plugins-official) |

UI: **Grok market** · **Claude market** · **Custom plugins**.

- 캐시: \`~/.hip/cache/marketplaces/<sourceId>/\`
- 소스 토글: \`~/.hip/config/marketplace-sources.json\`
- 다운로드 기본 \`enabled: false\`; \`boundModel\` 검토.

### 플러그인 디렉터리

필수: \`.plugin/plugin.json\`(\`name\` / \`version\` 최소).

### \`hip-plugins.json\`

권장(문자열 배열):

\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

## MCP

- hip.toml / 플러그인 합성.
- \`mcp_search\` 후 \`mcp__<server>__<tool>\`.
- 네트워크 정책이 아웃바운드를 막을 수 있음.

## 스킬 범위

| 범위 | 위치 |
|------|------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\` |
| plugin | 플러그인 소유 |
| builtin | \`~/.hip/builtin-skills/hip/\`(최저 우선) |
`,
  }
  ],
},
}

/** Map app language / BCP-47 tag → product help locale. */
export function resolveProductHelpLocale(lang: string | null | undefined): ProductHelpLocale {
  const raw = (lang ?? '').trim()
  if (raw === 'zh-CN' || raw === 'zh-TW' || raw === 'en' || raw === 'ja' || raw === 'ko') return raw
  if (raw.startsWith('zh-TW') || raw.startsWith('zh-HK') || raw === 'zh-Hant') return 'zh-TW'
  if (raw.startsWith('zh')) return 'zh-CN'
  if (raw === 'ja' || raw.startsWith('ja-') || raw.startsWith('ja_')) return 'ja'
  if (raw === 'ko' || raw.startsWith('ko-') || raw.startsWith('ko_')) return 'ko'
  if (raw.startsWith('en')) return 'en'
  return 'en'
}

/** Locale pack for Settings Help; falls back to English. */
export function getProductHelpPack(lang: string | null | undefined): ProductHelpLocalePack {
  return PRODUCT_HELP_LOCALES[resolveProductHelpLocale(lang)]
}
