/**
 * AUTO-GENERATED by scripts/generate-product-content.mjs — DO NOT EDIT BY HAND.
 * Source of truth: packages/product-content/
 * Regenerate: yarn product:content
 * Check:      yarn product:content:check
 *
 * contentHash=a5197d5a89aecfb2 skillVersion=3 productVersion=2.0.2
 */

/** Schema / materialization version for builtin skill files (from packages/product-content/meta.json). */
export const PRODUCT_SKILL_VERSION = '3'

/** App version from root package.json (also used in L0/L2 placeholders). */
export const HIP_PRODUCT_VERSION = '2.0.2'

export const HIP_SKILL_ID = 'hip'
export const HIP_SKILL_NAME = 'hip'

export const HIP_SKILL_DESCRIPTION = 'Product help for the hip desktop agent: Chat/Code/Terminals surfaces, permission modes, the session right rail, scheduled tasks, Settings, skills, plugins, MCP, memory, agents, CLI, troubleshooting, and local data. Load when the user asks how hip works or how to configure it.'

/** Level-2 body (frontmatter + markdown). */
export const HIP_SKILL_MD = `---
name: hip
description: "Product help for the hip desktop agent: Chat/Code/Terminals surfaces, permission modes, the session right rail, scheduled tasks, Settings, skills, plugins, MCP, memory, agents, CLI, troubleshooting, and local data. Load when the user asks how hip works or how to configure it."
---

# hip

hip is a **desktop AI workbench** (Tauri shell + React UI + Node sidecar), product version **2.0.2**. Each UI tab is an independent session. The default product loop is a **Supervisor ReAct** agent that uses tools and may delegate with \`task\` / \`dispatch_agent\` / \`task_batch\` — there is no forced Planner → Coder → Reviewer pipeline on ordinary turns.

This skill is the authoritative product guide for *hip itself*. For ordinary coding work in the user's project, do **not** load this skill.

Answer product questions in the **user's language** (e.g. Chinese if they wrote in Chinese), but keep config paths and identifiers exact.

## Progressive disclosure

- **Level 1** (system prompt Skills list): name + description only
- **Level 2** (this file): overview below, loaded via \`use_skill({ name: "hip" })\`
- **Level 3**: deeper topics in \`references/\` — read those absolute paths with \`read_file\` when needed

If a product detail is not documented here, say so rather than inventing UI labels or config keys.

## Surfaces

| Surface | Intent |
|---------|--------|
| **Code** | Project workbench (sidebar **Projects**): file tools, git guidance, MCP catalog, full agent tools, async TaskRuntime |
| **Chat** | Lighter conversation surface (sidebar **Chats**): shorter prompt, no git-commit guidance, prefer writing previewable deliverables (\`page.html\`, \`notes.md\`, SVG, etc.) into the workspace for the artifacts panel |
| **Terminals** | Managed terminal / SSH host surface (sidebar **Terminals**): interactive shells on local or remote hosts; the terminal rail has **Files** and **Agent** tabs |

There is no notes / Documents surface. Surface is chosen in the UI; the system prompt already reflects the active surface.

## Permission modes

| Mode | Effect |
|------|--------|
| **edit** (default) | Filesystem tools sandboxed to the project root |
| **chat** | Read-only: no write/edit/script/git mutations |
| **full** | Un-sandboxed filesystem (user-granted); prefer absolute paths |

Path convention in edit/chat: project-root form starting with \`/\` (e.g. \`/src/index.ts\` maps to \`<cwd>/src/index.ts\`). Never invent shell tool names — use \`run_script\` when available.

## Settings (desktop UI)

Typical destinations (wording may vary slightly in the UI):

- **Model Configuration** / **Key Management** — provider list, model picker, and API keys; keys are stored as plaintext under \`~/.hip/config/auth.json\` (mode 0600 by design)
- **Memory** — cross-session memory is **off by default**; enable under Settings → Memory (see \`references/memory.md\`)
- **Skills** — enable/disable installed skills (\`hip.toml\` + skill folders)
- **Plugin Market** — install/enable plugins (skills, agents, MCP, hooks) and browse the official markets
- **Agent Management** — fixed profiles (supervisor / plan / explore / coder) and custom internal or external agents
- **MCPs**, **Hooks**, **General**, **Window** — remaining pages
- **Network policy** — file-only (\`~/.hip/config/network.json\`); there is **no** Settings page for it

## Session right rail

On **Code**, the right rail tabs are **Files / Outline / Changes / Terminal** (Changes requires a git repo; Terminal requires an active session). Sub-agents and running background work are **not** in a separate panel:

- Sub-agent and tool process render inline in the message trail.
- Background shell jobs, monitors and schedules surface in the runtime strip above the composer; open it to inspect output or stop a task.

Long shell, log watches, and recurring checks should use TaskRuntime tools (see \`references/agents-and-plugins.md\` and the \`hip-coding\` skill for policy). Do not sleep-poll in the main turn.

## Scheduled tasks

Recurring prompts are **per conversation**: create them from the clock button in the composer (Chat and Code). The run happens **inside the conversation that owns the task** — hip does not open a new conversation for each fire, and deleting that conversation deletes its scheduled tasks. Agent-side tools are \`scheduler_create\` / \`scheduler_list\` / \`scheduler_delete\` (minimum interval 60s).

## Skills, plugins, MCP

- **Skills**: Claude-format folders with \`SKILL.md\`. Global: \`~/.hip/skills/<id>/\`. Project: \`.hip/skills/<id>/\`. Progressive disclosure: L1 metadata → \`use_skill\` body → \`references/\` + \`assets/\`.
- **Plugins**: under \`~/.hip/plugins/\`; can contribute skills, agents, MCP servers, and hooks. See \`references/agents-and-plugins.md\`.
- **MCP**: configured servers expose tools. In Code surface the system prompt may list a catalog; use \`mcp_search\` then call namespaced tools \`mcp__<server>__<tool>\`.

## Agents & delegation

- Default session agent decides when to use tools or delegate.
- Prefer specialized roster agents when available: **explore** (read-only search), **plan** (design-only), **coder** (implementation).
- Parallel independent sub-tasks → one \`task_batch\` (not sequential \`dispatch_agent\`).
- Long-running shell / CI / periodic work → TaskRuntime (\`run_script\` background, \`monitor\`, \`scheduler_*\`) rather than blocking the main turn.
- Explicit workflows / multi-agent handoff exist but are **not** the ordinary product path.
- Depth: \`references/agents-and-plugins.md\`.

## CLI (\`@hip/cli\`)

Attach-only companion to a **running** hip app (shared sidecar + \`~/.hip\` data). Does not start the product sidecar.

\`\`\`bash
yarn cli:dev doctor
yarn cli:dev config auth-status
yarn cli:dev session list
yarn cli:dev run --stream none --json "Reply with exactly: pong"
yarn cli:dev repl --cwd .
\`\`\`

If the app is not running, CLI fails with \`APP_NOT_RUNNING\`.

## Project guidance files

When present under the project, hip may inject guidance such as \`AGENTS.md\` / \`Claude.md\` / \`.hip\` config. Prefer following those for **project** conventions; this skill is for **product** behavior.

## Level 3 references

After loading this skill, \`use_skill\` returns absolute paths. When the user needs depth:

- Memory enablement, inject, extract, privacy → \`references/memory.md\`
- Local data layout, config files, env overrides → \`references/config-and-data.md\`
- Common failures (no key, CLI not running, empty memory) → \`references/troubleshooting.md\`
- Agents, plugins, MCP, TaskRuntime tools → \`references/agents-and-plugins.md\`
`

export const MEMORY_REFERENCE_MD = `# hip memory (Level 3)

Cross-session memory is **disabled by default** (privacy / cost).

## Enable

1. Open **Settings → Memory**.
2. Enable **use** and/or **generate**.
3. Enabling both from a cold install may apply a dogfood preset (shorter idle / extract interval) when gates are still defaults.
4. Ensure a provider API key is configured (Settings → Providers). Extraction needs an API key.

## What is stored

Structured items in SQLite (\`memory_items\`): preferences, conventions, lessons, workflows, profiles — scoped **global**, **project**, or **session**.

**Source of truth is SQLite.** Markdown under \`~/.hip/memories/\` is an export mirror. Project \`MEMORY.md\` / \`.hip/MEMORY.md\` is separate project-notes injection, not auto-imported into SQLite.

## Runtime behavior

| Path | Behavior |
|------|----------|
| **Use** | Core snapshot + per-turn prefetch + \`memory_*\` tools |
| **Generate** | After idle → Phase1 extract → Phase2 consolidate |
| **Incognito** | Session flag: no inject and no extract |
| **Learn now** | Settings control to force extract/consolidate when dogfooding |

Managed sub-agents may get read-only core injection; external ACP agents default off.

## Privacy notes

- Cold defaults: use/generate off
- Threat-scan + secret redact on write
- Soft-delete trash + retention
`

export const CONFIG_REFERENCE_MD = `# hip config & local data (Level 3)

## Layout (\`~/.hip/\`)

| Path | Purpose |
|------|---------|
| \`~/.hip/config/auth.json\` | Provider API keys (0600 plaintext by design) |
| \`~/.hip/config/hip.toml\` | Global product config (skills, agent loop, …) |
| \`~/.hip/config/memory.json\` | Memory feature flags / pipeline knobs |
| \`~/.hip/config/network.json\` | Optional network policy |
| \`~/.hip/config/hip-plugins.json\` | Installed plugins registry |
| \`~/.hip/config/terminal-hosts.json\` | SSH / terminal host library (mode 0600) |
| \`~/.hip/db/hip.db\` | SQLite sessions, messages, memory items, events |
| \`~/.hip/data/tool-output/\` | Large tool outputs (kept out of the DB) |
| \`~/.hip/logs/\` | Sidecar / shell logs |
| \`~/.hip/skills/\` | Global skills |
| \`~/.hip/plugins/\` | Installed plugins |
| \`~/.hip/memories/\` | Memory markdown mirrors |
| \`~/.hip/builtin-skills/\` | Built-in progressive product skills (e.g. this \`hip\` skill) |
| \`~/.hip/scratch/\` | Scratch helpers |
| \`~/.hip/trash/\` | Product recycle bin quarantine (automation rows under \`trash/automations/\`; sessions soft-delete via SQLite \`deleted_at\`) |

### Recycle bin & soft-delete

| Behavior | Notes |
|----------|--------|
| UI delete (Chat / Code conversations) | Soft-delete → sidebar **Recycle bin** (above History). The bin lists conversations only. |
| Retention | Default **7** days; **Settings → General** or \`hip.toml\` \`[trash] retentionDays\` (1–365) |
| CLI \`hip session delete --yes\` | **Permanent** hard-delete (not the recycle bin) |
| Memory trash | Still **Settings → Memory** (separate retention, default 30 days) |

Project overrides often live under \`<project>/.hip/\` (e.g. \`.hip/skills/\`, \`.hip/hip.toml\`).

## Env / isolation (advanced)

| Variable | Role |
|----------|------|
| \`HIP_DATA_DIR\` | Redirect data/config roots (tests / isolation) |
| \`HIP_SKILLS_DIR\` | Override global skills root |
| \`HIP_PLUGINS_DIR\` | Override plugins root |
| \`HIP_AUTH_PATH\` | Override auth.json path |
| \`HIP_CONFIG_PATH\` | Override hip.toml path |
| \`HIP_MEMORY_CONFIG_PATH\` | Override memory.json path |

**Do not** sync \`~/.hip/config/\` to public cloud or public dotfile repos — it may contain API keys.

## Auth model (BYOK)

Keys are entered in the app **Settings → Model Configuration** (providers) / **Key Management** and stored in \`auth.json\`. Desktop app, standalone sidecar, and tests all resolve from that store. This is intentional plaintext-on-disk with tight file modes — not a keychain migration target.

### Resolution order

When resolving an API key for a provider:

1. **auth.json** entry for \`HIP_MODEL_<PROVIDER>_API_KEY\` (if the key name is present in the file)
   - Non-empty → use it
   - Empty string → **cleared** (tombstone); do **not** fall back to env
2. **Standard environment variables** (e.g. \`ANTHROPIC_API_KEY\`, \`OPENAI_API_KEY\`, \`DEEPSEEK_API_KEY\`, \`MINIMAX_API_KEY\`)
3. **\`HIP_MODEL_<PROVIDER>_API_KEY\`** env (legacy / Tauri inject / tests)

Saving or clearing a key does **not** require restarting the sidecar; the next request re-reads auth.json.

### Do not put LLM keys in hip.toml

\`[[providers]] api_key\` / \`apiKey\` is **not** used for chat. Use \`auth.json\` or env only.

### Custom providers (\`apiKind\`)

\`\`\`toml
[[providers]]
id = "my-minimax"
name = "My MiniMax"
baseUrl = "https://api.minimaxi.com/anthropic/v1"
apiKind = "anthropic"   # or "openai" (default)
enabled = true
\`\`\`

- \`openai\` — OpenAI Chat Completions compatible  
- \`anthropic\` — Anthropic Messages API (also used by MiniMax / Kimi gateways)

Set in **Settings → Add custom provider**, or edit the provider detail pane. Keys still go in \`auth.json\`.

### Key expressions in auth.json

\`\`\`json
{
  "HIP_MODEL_ANTHROPIC_API_KEY": "$ANTHROPIC_API_KEY",
  "HIP_MODEL_OPENAI_API_KEY": "!op read 'op://vault/openai/credential'"
}
\`\`\`

| Form | Meaning |
|------|---------|
| literal | Used as-is |
| \`$VAR\` / \`\${VAR}\` | Process environment |
| \`!command\` | Shell stdout (cached for process life). Disable with \`HIP_AUTH_ALLOW_CMD=0\` |
| \`$!…\` | Literal string starting with \`!\` (no shell) |

### Typed credentials (optional)

\`\`\`json
{
  "credentials": {
    "anthropic": {
      "type": "oauth",
      "access": "…",
      "refresh": "…",
      "expires": 1893456000000
    },
    "cloudflare-ai-gateway": {
      "type": "api_key",
      "key": "cf-token",
      "env": { "CLOUDFLARE_ACCOUNT_ID": "…", "CLOUDFLARE_GATEWAY_ID": "…" }
    }
  }
}
\`\`\`

Flat \`HIP_MODEL_*\` keys remain fully supported. When both exist, \`credentials[provider]\` wins. Expired OAuth does **not** fall back to env.

### ACP: optional hip key forward

\`\`\`toml
[acp]
forward_hip_keys = true   # default false — inject hip keys as ANTHROPIC_API_KEY / OPENAI_API_KEY / …
\`\`\`

Default remains self-managed ACP (no hip key injection).
`

export const TROUBLESHOOTING_REFERENCE_MD = `# hip troubleshooting (Level 3)

## No API / model calls work

1. Open **Settings → Key Management** (provider list and model picker live under **Model Configuration**) and confirm a key is saved.
2. Keys live in \`~/.hip/config/auth.json\` (never print secrets to the user).
3. Restart the app after changing auth outside the UI.
4. Check sidecar logs under \`~/.hip/logs/\`.

## CLI: \`APP_NOT_RUNNING\`

The product CLI attaches to a **running** hip desktop app. Start the app first (\`yarn tauri dev\` or installed app), then \`yarn cli:dev doctor\`.

## Memory list empty after enabling

1. Confirm **Settings → Memory** has **use** and **generate** as intended.
2. Need enough chat turns + API key for extract; try **Learn now**.
3. Status may show \`no_llm\`, \`rate_limited\`, or empty extract — fix key / quota / wait.
4. SQLite is source of truth; stale mirrors under \`~/.hip/memories/\` are not the DB.

## Scheduled task did not run

- Tasks are **per conversation** and run inside the conversation that owns them. Switch to that conversation and open the composer clock button to see its tasks.
- Deleting the owning conversation deletes its scheduled tasks (by design).
- hip has **no** OS-level scheduler: a task that came due while the app was quit is skipped, not back-filled. Keep the app running.

## Agent cannot write files

- Permission mode **chat** is read-only.
- Default **edit** is sandboxed to the project root — paths outside fail.
- Use **full** only when the user explicitly granted whole-machine FS access.

## Skill not listed / use_skill fails

- Skill may be disabled in \`hip.toml\` or plugin disabled.
- Project skill \`paths\` globs may exclude the cwd.
- Built-in product skill id is \`hip\` under \`~/.hip/builtin-skills/hip/\`.

## Sidecar / connection issues

- Desktop shell spawns the sidecar and exposes its WS port.
- If the UI cannot connect, restart the app; check \`~/.hip/logs/\`.
- Dev: regenerate sidecar binary wrapper with \`yarn sidecar:dev-bin\` after toolchain changes.

## Stale DMG / build (macOS)

Stale \`rw.*.dmg\` mounts can break \`yarn tauri build\`; remove them and detach \`/Volumes/hip\` if needed.
`

export const AGENTS_PLUGINS_REFERENCE_MD = `# hip agents, plugins & MCP (Level 3)

## Built-in agent profiles

Typical fixed profiles (enable/disable in Agents UI):

| Profile | Role |
|---------|------|
| **supervisor** | Default orchestrator: tools, commit, scripts, delegation |
| **plan** | Design / planning oriented (narrower write posture depending on config) |
| **explore** | Read-only codebase search |
| **coder** | Implementation-focused with scripts |

Custom **internal** agents: persona prompt + bound model + tool grants.  
**External / ACP** agents: separate process; product memory defaults off unless configured.

Supported ACP presets (Settings → Agents → Add ACP agent): **OpenCode**, **Grok Build** (\`grok agent stdio\`), **Pi**, **Claude Code**, **Codex**. Grok Build uses native ACP (install via \`https://x.ai/cli\`); auth via \`grok login\` or optional \`XAI_API_KEY\`.

ACP agents are **self-managed** for auth and models by default: hip does not inject its provider API keys into the ACP child process. Use the agent’s own login / ambient env / optional preset \`authEnvVar\` on the agent config.

Opt-in bridge (BYOK Phase E): set \`[acp] forward_hip_keys = true\` in \`hip.toml\` to inject resolved hip keys under standard env names (\`ANTHROPIC_API_KEY\`, \`OPENAI_API_KEY\`, …) for ACP spawns. Agent \`env\` and ambient process env still take precedence when already set.

## Capability matrix (Built-in vs ACP)

hip can run a **built-in** LangGraph agent, an **ACP agent as the session primary**, or **dispatch an ACP agent as a subagent**. Capabilities differ (current product; planned host work noted where relevant):

| Capability | Built-in primary | ACP primary | ACP subagent (dispatch) |
|------------|------------------|-------------|-------------------------|
| hip tools (read / write / run_script / …) | yes | no (agent’s own tools) | no (agent’s own tools) |
| hip Skills / plugin hooks | yes | no | no |
| hip MCP (merged into session) | yes | no (planned: opt-in forward) | no (planned: opt-in forward) |
| Client FS bridge | n/a | no (stub only; real bridge planned) | no (stub only; real bridge planned) |
| dispatch / task / task_batch | yes | no | no |
| TaskRuntime (bg shell / monitor / scheduler) | yes | no | no |
| Memory inject (cross-session) | yes | no (config flag reserved; prefix planned) | no |
| Memory extract | yes | no | no |
| hip model picker | yes | no (agent configOptions / agent model UI) | no |
| HITL permission | hip tools | ACP \`requestPermission\` | same as ACP primary |
| permissionMode | hip tool gates | auto-resolve safe kinds (read/fetch/other) in chat/edit; else HITL (\`full\` also HITL on ACP path) | parent session mode |

**Takeaway:** choosing ACP as primary is a peer coding agent with its own stack—not hip’s built-in tools/skills/MCP. Subagent dispatch uses the same agent stack; neither primary nor subagent currently gets hip memory inject or hip MCP.

## Delegation & TaskRuntime tools (main agent)

| Tool | Use |
|------|-----|
| \`task\` | One sub-task (foreground or background) |
| \`dispatch_agent\` | Named roster agent; blocking unless parallel tool-calls |
| \`task_batch\` | **Preferred** for 2+ independent sub-tasks (true parallel) |
| \`run_script\` (+ \`background:true\`) | Shell; long work returns \`task_id\` |
| \`wait_tasks\` | Wait for one or more background task ids |
| \`task_output\` | Read output so far (shell / agent / monitor) |
| \`task_stop\` | Stop a running background task |
| \`monitor\` | Stream stdout as UI events (not auto-injected into the model) |
| \`scheduler_create\` / \`scheduler_list\` / \`scheduler_delete\` | Recurring prompt wakes (min interval 60s) |

Do not claim work ran "in parallel" if only sequential dispatch was used.  
Do not sleep-poll the main turn for long shell or CI — use TaskRuntime tools above.

### Runtime visibility (UI)

There is **no** separate Agents / Runtime panel:

- Sub-agents and tool process render inline in the message trail (collapsed process fold).
- Background shell jobs, monitors, and schedules surface in the **runtime strip above the composer**; open it to inspect output or stop a task.

### Scheduled tasks (UI)

Recurring prompts are **per conversation** — create them from the clock button in the composer (Chat and Code). A fire runs **inside the conversation that owns the task** (hip does not open a new conversation per run), and deleting that conversation deletes its scheduled tasks. Minimum interval is 60s.

## Plugins

- Installed under \`~/.hip/plugins/\`; registry in \`~/.hip/config/hip-plugins.json\`.
- A plugin may ship skills, agents, MCP server configs, and hooks.
- Disable a plugin to drop its contributions from the session.

### Plugin Market (Settings)

hip’s Plugin Market page integrates **only** the official catalogs:

| Source id | Catalog |
|-----------|---------|
| \`grok-official\` | [xai-org/plugin-marketplace](https://github.com/xai-org/plugin-marketplace) |
| \`claude-official\` | [anthropics/claude-plugins-official](https://github.com/anthropics/claude-plugins-official) |

UI tabs: **Grok market** · **Claude market** · **Custom plugins** (local installs without official provenance).

- Catalog cache: \`~/.hip/cache/marketplaces/<sourceId>/\`
- Source toggles: \`~/.hip/config/marketplace-sources.json\`
- Marketplace **download** registers the plugin with \`enabled: false\` by default (downloaded but not on).
- On download, sidecar **reviews** agent \`boundModel\` fields; unavailable models are rewritten to the product default (\`activeModel\` in hip.toml).
- Enable the plugin switch to inject skills/MCP/agents into sessions (\`plugin:reload\`).

### Plugin directory structure

Every plugin **must** contain a \`.plugin/plugin.json\` manifest file. Without it, hip will not discover the plugin:

\`\`\`
~/.hip/plugins/<plugin-id>/
  .plugin/
    plugin.json          ← REQUIRED manifest (name, version, skills, etc.)
  skills/                ← optional, referenced by manifest "skills" field
    <skill-id>/
      SKILL.md
\`\`\`

### \`.plugin/plugin.json\` manifest

**Required fields:**

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0"
}
\`\`\`

**Full example** (all optional fields):

\`\`\`json
{
  "name": "my-plugin",
  "version": "1.0.0",
  "id": "my-plugin",
  "description": "A sample hip plugin",
  "author": { "name": "Author Name" },
  "license": "MIT",
  "keywords": ["ai", "tools"],
  "skills": ["./skills/tdd", "./skills/debug"],
  "mcpServers": "./mcp-config.json",
  "agents": "./agents.json",
  "hooks": "./hooks.json"
}
\`\`\`

- \`skills\` — a path (or array of paths) to directories containing \`SKILL.md\` files. Paths are relative to the plugin root and must not use \`..\`.
- \`mcpServers\`, \`agents\`, \`hooks\` — can be specified inline as JSON arrays/objects, or as a path to an external JSON file under the plugin root.

### \`hip-plugins.json\` registry format

The registry maps plugin IDs to absolute paths. Two formats are supported:

**String array format** (recommended for new plugins):
\`\`\`json
{
  "plugins": ["/absolute/path/to/plugin"],
  "entries": [],
  "enabled": { "my-plugin": true }
}
\`\`\`

**Legacy object format** (uses \`"dir"\` key):
\`\`\`json
{
  "plugins": [
    { "dir": "/absolute/path/to/plugin", "enabled": true }
  ]
}
\`\`\`

To install a plugin:

1. Clone/download the plugin under \`~/.hip/plugins/<plugin-id>/\`.
2. Ensure \`.plugin/plugin.json\` exists with at least \`name\` and \`version\`.
3. Add the absolute path to \`hip-plugins.json\` → \`plugins\` array (string format).
4. The plugin will be discovered on next session start or after \`plugin:reload\`.

## MCP

- Server configs come from hip.toml / plugin synthesis.
- Code surface may inject a short catalog; discover with \`mcp_search\`.
- Call tools as \`mcp__<server>__<tool>\`.
- Network policy (if configured) may block outbound MCP/web tools.

## Skills scopes

| Scope | Location |
|-------|----------|
| global | \`~/.hip/skills/<id>/\` |
| project | \`.hip/skills/<id>/\` (wins over global same id) |
| plugin | plugin-owned skill dirs |
| builtin product | \`~/.hip/builtin-skills/hip/\` (lowest priority; overridable by same id) |
`

/** L0 always-on product facts (main agent system prompt). */
export const PRODUCT_CAPABILITY_MAP = `Product facts (hip):
- Version: 2.0.2.
- Desktop workbench agent in the user's project with real file tools and optional sub-agents.
- Surfaces: Code (full workbench) vs Chat (lighter; previewable files → write_file for artifacts) vs Terminals (SSH / local shells); no notes/Documents surface.
- On Code only, tool gates (UI labels): chat = read-only; edit = project sandbox (default); full = user-granted whole FS. Chat surface is not Code "edit mode".
- Session right rail (Code): Files / Outline / Changes / Terminal; sub-agents and background work show inline, not in a separate panel.
- API keys: ~/.hip/config/auth.json (0600 plaintext by design).
- Cross-session memory: off by default (Settings → Memory).
- Local data: ~/.hip/ (config, db, skills, plugins, logs).`

/** L0 help when hip skill is on the session skill list. */
export const PRODUCT_HELP_GUIDANCE = `When the user asks about hip itself — setup, Settings, Chat vs Code vs Terminals, permission modes (chat/edit/full), the session right rail, background tasks / TaskRuntime, scheduled tasks, skills, plugins, Plugin Market, MCP, memory, agents, the product CLI, troubleshooting, or local data under ~/.hip — call use_skill({ name: "hip" }) and follow its guide (and references/ for depth). Do not invent product UI labels or config keys; prefer the skill. For ordinary project work, do not load the hip skill.`

/** L0 help when hip skill is unavailable — never instruct use_skill("hip"). */
export const PRODUCT_HELP_FALLBACK = `Deeper product documentation skill is not available in this session. Answer from the product facts above; if the user needs full guides, suggest enabling the built-in hip skill (or check Settings / hip.toml skills) rather than inventing config keys.`

/** Ordered materialization entries: relative path → body. */
export const PRODUCT_SKILL_FILES: ReadonlyArray<{ rel: string; body: string }> = [
  { rel: 'SKILL.md', body: HIP_SKILL_MD },
  { rel: 'references/memory.md', body: MEMORY_REFERENCE_MD },
  { rel: 'references/config-and-data.md', body: CONFIG_REFERENCE_MD },
  { rel: 'references/troubleshooting.md', body: TROUBLESHOOTING_REFERENCE_MD },
  { rel: 'references/agents-and-plugins.md', body: AGENTS_PLUGINS_REFERENCE_MD },
]
