# Regenerates the dev-mode sidecar wrapper for Windows.
#
# Equivalent to make-sidecar-dev-bin.sh, adapted for Windows.
# Generates a minimal Rust launcher .exe that Tauri can spawn as
# the sidecar child process on Windows (Tauri requires .exe).
#
# Run once after cloning, or after switching Rust toolchains:
#     yarn sidecar:dev-bin  (calls this script on Windows)

$ErrorActionPreference = "Stop"

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Resolve-Path "$ScriptDir\.."
$BinDir = Join-Path $RootDir "src-tauri\binaries"

# Determine the Rust host target triple (e.g. x86_64-pc-windows-msvc)
$rustcOutput = rustc -vV 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "error: could not run rustc -vV (is rustc installed?)"
    exit 1
}
$targetTripleLine = $rustcOutput | Select-String -Pattern "^host:\s+(.+)" | ForEach-Object { $_.Matches.Groups[1].Value }
if (-not $targetTripleLine) {
    Write-Error "error: could not determine host target triple from rustc -vV"
    exit 1
}
$TargetTriple = $targetTripleLine.Trim()

# Resolve node's ABSOLUTE path at generation time.
# Use process.execPath, not Get-Command node: yarn injects an ephemeral
# temp dir onto PATH, which would bake a transient path into the wrapper.
$nodeBin = node -e "process.stdout.write(process.execPath)" 2>$null
if (-not $nodeBin -or -not (Test-Path $nodeBin)) {
    Write-Error "error: could not resolve a real node executable"
    exit 1
}
$NodeDir = Split-Path -Parent $nodeBin
$RootDirStr = $RootDir.Path

# Ensure the binaries directory exists
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null

$wrapperExe = Join-Path $BinDir "sidecar-$TargetTriple.exe"
$tempDir = Join-Path $BinDir ".launcher-build"

Write-Host "target triple: $TargetTriple"
Write-Host "node:          $nodeBin"
Write-Host "repo root:     $RootDirStr"

# Generate a minimal Rust launcher that spawns the Node.js sidecar.
# Paths are baked in so the wrapper works regardless of PATH.
#
# IMPORTANT process model (mirrors Unix `exec` single-PID semantics):
# Tauri's child.kill() only TerminateProcess-es this launcher PID. A plain
# Command::status() child would be orphaned (port still bound, SQLite locked).
# We put Node under a Job Object with JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE so
# when the launcher dies, Windows tears down the whole job tree.
$rustSource = @"
#![windows_subsystem = "windows"]
// Generated by make-sidecar-dev-bin.ps1 — do not edit.
// Thin launcher: spawn Node under a kill-on-close Job Object so Tauri's
// child.kill() on this PID also terminates the sidecar (and any grandchildren).
// #![windows_subsystem = "windows"] avoids a console flash when GUI-spawned.

use std::os::windows::io::AsRawHandle;
use std::process::{Command, exit};
use std::ptr;

type HANDLE = *mut core::ffi::c_void;

const JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE: u32 = 0x2000;
const JOB_OBJECT_EXTENDED_LIMIT_INFORMATION: i32 = 9;

#[repr(C)]
struct JOBOBJECT_BASIC_LIMIT_INFORMATION {
    per_process_user_time_limit: i64,
    per_job_user_time_limit: i64,
    limit_flags: u32,
    minimum_working_set_size: usize,
    maximum_working_set_size: usize,
    active_process_limit: u32,
    affinity: usize,
    priority_class: u32,
    scheduling_class: u32,
}

#[repr(C)]
struct IO_COUNTERS {
    read_operation_count: u64,
    write_operation_count: u64,
    other_operation_count: u64,
    read_transfer_count: u64,
    write_transfer_count: u64,
    other_transfer_count: u64,
}

#[repr(C)]
struct JOBOBJECT_EXTENDED_LIMIT_INFORMATION {
    basic_limit_information: JOBOBJECT_BASIC_LIMIT_INFORMATION,
    io_info: IO_COUNTERS,
    process_memory_limit: usize,
    job_memory_limit: usize,
    peak_process_memory_used: usize,
    peak_job_memory_used: usize,
}

#[link(name = "kernel32")]
extern "system" {
    fn CreateJobObjectW(attrs: *mut core::ffi::c_void, name: *const u16) -> HANDLE;
    fn SetInformationJobObject(
        job: HANDLE,
        info_class: i32,
        info: *mut core::ffi::c_void,
        len: u32,
    ) -> i32;
    fn AssignProcessToJobObject(job: HANDLE, process: HANDLE) -> i32;
}

fn main() {
    // Create Job Object with KILL_ON_JOB_CLOSE before spawning Node.
    // Intentionally never CloseHandle(job): the handle lives until this process
    // exits (or is TerminateProcess'd by Tauri). Closing the last handle then
    // kills every process still assigned to the job.
    let job = unsafe { CreateJobObjectW(ptr::null_mut(), ptr::null()) };
    if job.is_null() {
        eprintln!("sidecar-launcher: CreateJobObjectW failed");
        exit(1);
    }

    let mut info: JOBOBJECT_EXTENDED_LIMIT_INFORMATION = unsafe { std::mem::zeroed() };
    info.basic_limit_information.limit_flags = JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;
    let set_ok = unsafe {
        SetInformationJobObject(
            job,
            JOB_OBJECT_EXTENDED_LIMIT_INFORMATION,
            &mut info as *mut _ as *mut core::ffi::c_void,
            std::mem::size_of::<JOBOBJECT_EXTENDED_LIMIT_INFORMATION>() as u32,
        )
    };
    if set_ok == 0 {
        eprintln!("sidecar-launcher: SetInformationJobObject failed");
        exit(1);
    }

    let mut child = Command::new(r#"$nodeBin"#)
        .arg("--import")
        .arg("tsx")
        .arg("packages/sidecar/src/main.ts")
        .current_dir(r#"$RootDirStr"#)
        .env(
            "PATH",
            format!("{};{}", r#"$NodeDir"#, std::env::var("PATH").unwrap_or_default()),
        )
        .spawn()
        .unwrap_or_else(|e| {
            eprintln!("sidecar-launcher: failed to start node: {}", e);
            exit(1);
        });

    let process_handle = child.as_raw_handle() as HANDLE;
    let assign_ok = unsafe { AssignProcessToJobObject(job, process_handle) };
    if assign_ok == 0 {
        eprintln!("sidecar-launcher: AssignProcessToJobObject failed");
        let _ = child.kill();
        exit(1);
    }

    let status = child.wait().unwrap_or_else(|e| {
        eprintln!("sidecar-launcher: wait failed: {}", e);
        exit(1);
    });
    exit(status.code().unwrap_or(1));
}
"@

# Build in a temp directory to keep things clean
Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
$tempSrcDir = Join-Path $tempDir "src"
New-Item -ItemType Directory -Force -Path $tempSrcDir | Out-Null
$rustFile = Join-Path $tempSrcDir "main.rs"
Write-Utf8NoBom -Path $rustFile -Content $rustSource

$cargoToml = @"
[package]
name = "sidecar-launcher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sidecar-launcher"
path = "src/main.rs"
"@
Write-Utf8NoBom -Path (Join-Path $tempDir "Cargo.toml") -Content $cargoToml

Write-Host "compiling launcher..."
# cargo writes progress to stderr; temporarily relax ErrorAction so
# redirected stderr lines don't abort the script in Stop mode.
$prevErrorAction = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$cargoOutput = & cargo build --manifest-path (Join-Path $tempDir "Cargo.toml") --release 2>&1
$cargoExit = $LASTEXITCODE
$ErrorActionPreference = $prevErrorAction
if ($cargoOutput) {
    $cargoOutput | ForEach-Object { Write-Host $_ }
}
if ($cargoExit -ne 0) {
    Write-Error "error: cargo build failed (exit code: $cargoExit)"
    Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
    exit 1
}

# Copy the compiled binary to the expected location
$builtExe = Join-Path $tempDir "target\release\sidecar-launcher.exe"
Copy-Item -Force $builtExe $wrapperExe

# Clean up build artifacts
Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue

Write-Host "wrote dev sidecar wrapper: $wrapperExe"
