# Regenerates the dev-mode sidecar wrapper for Windows.
#
# Equivalent to make-sidecar-dev-bin.sh, adapted for Windows.
# Generates a minimal Rust launcher .exe that Tauri can spawn as
# the sidecar child process on Windows (Tauri requires .exe).
#
# Run once after cloning, or after switching Rust toolchains:
#     yarn sidecar:dev-bin  (calls this script on Windows)
#     yarn sidecar:dev-bin:win  (explicit Windows variant)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Resolve-Path "$ScriptDir\.."
$BinDir = Join-Path $RootDir "src-tauri\binaries"

# Determine the Rust host target triple (e.g. x86_64-pc-windows-msvc)
$rustcOutput = rustc -vV 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "error: could not run rustc -vV (is rustc installed?)"
    exit 1
}
$targetTripleLine = $rustcOutput | Select-String -Pattern "^host:\s+(.+)" | ForEach-Object { $_.Matches.Groups[1].Value }
if (-not $targetTripleLine) {
    Write-Error "error: could not determine host target triple from rustc -vV"
    exit 1
}
$TargetTriple = $targetTripleLine.Trim()

# Resolve node's ABSOLUTE path at generation time.
# Use process.execPath, not Get-Command node: yarn injects an ephemeral
# temp dir onto PATH, which would bake a transient path into the wrapper.
$nodeBin = node -e "process.stdout.write(process.execPath)" 2>$null
if (-not $nodeBin -or -not (Test-Path $nodeBin)) {
    Write-Error "error: could not resolve a real node executable"
    exit 1
}
$NodeDir = Split-Path -Parent $nodeBin
$RootDirStr = $RootDir.Path

# Ensure the binaries directory exists
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null

$wrapperExe = Join-Path $BinDir "sidecar-$TargetTriple.exe"
$tempDir = Join-Path $BinDir ".launcher-build"

Write-Host "target triple: $TargetTriple"
Write-Host "node:          $nodeBin"
Write-Host "repo root:     $RootDirStr"

# Generate a minimal Rust launcher that spawns the Node.js sidecar.
# The paths are baked in so the wrapper works regardless of PATH.
$rustSource = @"
// Generated by make-sidecar-dev-bin.ps1 — do not edit.
// This is a thin launcher that spawns the Node.js sidecar in-process.
// Tauri's child.kill() kills this PID, which in turn kills the node process.
use std::process::{Command, exit};

fn main() {
    let status = Command::new(r#"$nodeBin"#)
        .arg("--import")
        .arg("tsx")
        .arg("packages/sidecar/src/main.ts")
        .current_dir(r#"$RootDirStr"#)
        .env("PATH", format!("{};{}", r#"$NodeDir"#, std::env::var("PATH").unwrap_or_default()))
        .status()
        .unwrap_or_else(|e| {
            eprintln!("sidecar-launcher: failed to start node: {}", e);
            exit(1);
        });
    exit(status.code().unwrap_or(1));
}
"@

# Build in a temp directory to keep things clean
Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
$tempSrcDir = Join-Path $tempDir "src"
New-Item -ItemType Directory -Force -Path $tempSrcDir | Out-Null
$rustFile = Join-Path $tempSrcDir "main.rs"
Set-Content -Path $rustFile -Value $rustSource -Encoding UTF8

$cargoToml = @"
[package]
name = "sidecar-launcher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sidecar-launcher"
path = "src/main.rs"
"@
Set-Content -Path (Join-Path $tempDir "Cargo.toml") -Value $cargoToml -Encoding UTF8

Write-Host "compiling launcher..."
# cargo writes progress to stderr; temporarily relax ErrorAction so
# redirected stderr lines don't abort the script in Stop mode.
$prevErrorAction = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$cargoOutput = & cargo build --manifest-path (Join-Path $tempDir "Cargo.toml") --release 2>&1
$cargoExit = $LASTEXITCODE
$ErrorActionPreference = $prevErrorAction
if ($cargoOutput) {
    $cargoOutput | ForEach-Object { Write-Host $_ }
}
if ($cargoExit -ne 0) {
    Write-Error "error: cargo build failed (exit code: $cargoExit)"
    Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
    exit 1
}

# Copy the compiled binary to the expected location
$builtExe = Join-Path $tempDir "target\release\sidecar-launcher.exe"
Copy-Item -Force $builtExe $wrapperExe

# Clean up build artifacts
Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue

Write-Host "wrote dev sidecar wrapper: $wrapperExe"
