/**
 * Self-contained HTML report for a convened roundtable (deliverable for Chat preview).
 */
import { personaLabel } from './prompts.js'
import type {
  PersonaId,
  RoundtableEdgeResult,
  RoundtableLang,
  SpeechRecord,
  StageRecord,
} from './types.js'

export interface RoundtableReportData {
  issue: string
  language: RoundtableLang
  agenda: string[]
  rationale: string
  rounds: Array<{
    round: number
    focus: string
    speeches: SpeechRecord[]
    stage: StageRecord
  }>
  decision?: {
    decision: string
    residual: string[]
    nextSteps: string[]
  }
  edges?: RoundtableEdgeResult[]
  earlyExit?: boolean
  generatedAt?: string
}

const LABELS: Record<
  RoundtableLang,
  {
    title: string
    issue: string
    plan: string
    agenda: string
    why: string
    round: string
    focus: string
    speeches: string
    stage: string
    agreed: string
    open: string
    edges: string
    decision: string
    residual: string
    next: string
    early: string
    footer: string
  }
> = {
  en: {
    title: 'Roundtable report',
    issue: 'Issue',
    plan: 'Meeting plan',
    agenda: 'Agenda',
    why: 'Why convened',
    round: 'Round',
    focus: 'Focus',
    speeches: 'Advisor speeches',
    stage: 'Stage conclusion (hip)',
    agreed: 'Agreed',
    open: 'Still open',
    edges: 'Discussion edges',
    decision: 'Decision (hip)',
    residual: 'Residual disagreements',
    next: 'Next steps',
    early: 'Ended early',
    footer: 'Generated by hip roundtable',
  },
  'zh-CN': {
    title: '圆桌会议报告',
    issue: '议题',
    plan: '会议规划',
    agenda: '议程',
    why: '召开原因',
    round: '第',
    focus: '焦点',
    speeches: '顾问发言',
    stage: '阶段性结论（hip）',
    agreed: '已共识',
    open: '仍开放',
    edges: '交锋关系',
    decision: '决策（hip）',
    residual: '残留分歧',
    next: '后续步骤',
    early: '提前结束',
    footer: '由 hip 圆桌会议生成',
  },
  'zh-TW': {
    title: '圓桌會議報告',
    issue: '議題',
    plan: '會議規劃',
    agenda: '議程',
    why: '召開原因',
    round: '第',
    focus: '焦點',
    speeches: '顧問發言',
    stage: '階段性結論（hip）',
    agreed: '已共識',
    open: '仍開放',
    edges: '交鋒關係',
    decision: '決策（hip）',
    residual: '殘留分歧',
    next: '後續步驟',
    early: '提前結束',
    footer: '由 hip 圓桌會議生成',
  },
  ja: {
    title: '円卓会議レポート',
    issue: '議題',
    plan: '会議計画',
    agenda: 'アジェンダ',
    why: '開催理由',
    round: 'ラウンド',
    focus: '焦点',
    speeches: 'アドバイザー発言',
    stage: '段階結論 (hip)',
    agreed: '合意',
    open: '未決',
    edges: '議論の関係',
    decision: '決定 (hip)',
    residual: '残る対立',
    next: '次のステップ',
    early: '早期終了',
    footer: 'hip 円卓会議が生成',
  },
  ko: {
    title: '원탁 회의 보고서',
    issue: '안건',
    plan: '회의 계획',
    agenda: '안건 목록',
    why: '소집 이유',
    round: '라운드',
    focus: '초점',
    speeches: '자문 발언',
    stage: '단계 결론 (hip)',
    agreed: '합의',
    open: '미결',
    edges: '논의 관계',
    decision: '결정 (hip)',
    residual: '잔여 이견',
    next: '다음 단계',
    early: '조기 종료',
    footer: 'hip 원탁 회의 생성',
  },
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function bullets(items: string[]): string {
  if (!items.length) return '<li class="muted">—</li>'
  return items.map((x) => `<li>${esc(x)}</li>`).join('\n')
}

function roundHeading(lang: RoundtableLang, n: number): string {
  const L = LABELS[lang]
  if (lang === 'zh-CN' || lang === 'zh-TW') return `${L.round} ${n} 轮`
  if (lang === 'ja') return `${L.round} ${n}`
  if (lang === 'ko') return `${L.round} ${n}`
  return `${L.round} ${n}`
}

function edgeRel(lang: RoundtableLang, rel: string): string {
  if (lang === 'zh-CN' || lang === 'zh-TW') {
    if (rel === 'rebut') return '反驳'
    if (rel === 'support') return '附议'
    return '提问'
  }
  return rel
}

function personaName(id: string, lang: RoundtableLang): string {
  if ((['strategist', 'skeptic', 'creative', 'operator', 'audience'] as string[]).includes(id)) {
    return personaLabel(id as PersonaId, lang)
  }
  return id
}

/** Build a single-file HTML report suitable for Chat artifact preview. */
export function buildRoundtableReportHtml(data: RoundtableReportData): string {
  const lang = data.language
  const L = LABELS[lang]
  const when = data.generatedAt ?? new Date().toISOString()
  const issueTitle = data.issue.replace(/\s+/g, ' ').trim().slice(0, 80)

  const roundsHtml = data.rounds
    .map((r) => {
      const speeches = r.speeches
        .map(
          (s) => `
        <article class="speech">
          <h4>${esc(personaLabel(s.speaker, lang))}</h4>
          <div class="prose">${esc(s.content).replace(/\n/g, '<br/>')}</div>
        </article>`,
        )
        .join('\n')
      return `
      <section class="card round">
        <h2>${esc(roundHeading(lang, r.round))}</h2>
        <p class="meta"><strong>${esc(L.focus)}:</strong> ${esc(r.focus)}</p>
        <h3>${esc(L.speeches)}</h3>
        <div class="speeches">${speeches || '<p class="muted">—</p>'}</div>
        <h3>${esc(L.stage)}</h3>
        <div class="stage">
          <p><strong>${esc(L.agreed)}</strong></p>
          <ul>${bullets(r.stage.agreed)}</ul>
          <p><strong>${esc(L.open)}</strong></p>
          <ul>${bullets(r.stage.open)}</ul>
          ${
            r.stage.earlyExit
              ? `<p class="badge">${esc(L.early)}${r.stage.earlyExitReason ? `: ${esc(r.stage.earlyExitReason)}` : ''}</p>`
              : ''
          }
        </div>
      </section>`
    })
    .join('\n')

  const edges = data.edges ?? []
  const edgesHtml =
    edges.length === 0
      ? ''
      : `
    <section class="card">
      <h2>${esc(L.edges)}</h2>
      <ul class="edges">
        ${edges
          .map(
            (e) =>
              `<li><span class="from">${esc(personaName(e.from, lang))}</span>
               <span class="rel">${esc(edgeRel(lang, e.relation))}</span>
               <span class="to">${esc(personaName(e.to, lang))}</span>
               <span class="round-tag">R${e.round}</span>
               ${e.summary ? `<div class="sum">${esc(e.summary)}</div>` : ''}</li>`,
          )
          .join('\n')}
      </ul>
    </section>`

  const decide = data.decision
  const decideHtml = decide
    ? `
    <section class="card decision">
      <h2>${esc(L.decision)}</h2>
      <div class="prose lead">${esc(decide.decision).replace(/\n/g, '<br/>')}</div>
      <h3>${esc(L.residual)}</h3>
      <ul>${bullets(decide.residual)}</ul>
      <h3>${esc(L.next)}</h3>
      <ol>${
        decide.nextSteps.length
          ? decide.nextSteps.map((x) => `<li>${esc(x)}</li>`).join('\n')
          : '<li class="muted">—</li>'
      }</ol>
      ${data.earlyExit ? `<p class="badge">${esc(L.early)}</p>` : ''}
    </section>`
    : ''

  return `<!DOCTYPE html>
<html lang="${esc(lang)}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(L.title)} — ${esc(issueTitle)}</title>
  <style>
    :root {
      --bg: #0f1115;
      --card: #171a21;
      --ink: #e8eaed;
      --muted: #9aa0a6;
      --accent: #7aa2ff;
      --border: #2a2f3a;
      --badge: #3d2a12;
      --badge-ink: #f0c674;
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #f6f7f9;
        --card: #ffffff;
        --ink: #1a1d23;
        --muted: #5f6368;
        --accent: #3b6ef5;
        --border: #e2e5eb;
        --badge: #fff4e0;
        --badge-ink: #8a5a00;
      }
    }
    * { box-sizing: border-box; }
    html {
      height: 100%;
      overflow: auto;
      -webkit-overflow-scrolling: touch;
    }
    body {
      margin: 0;
      min-height: 100%;
      font: 15px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
      color: var(--ink);
      background: var(--bg);
      padding: 2rem 1.25rem 3rem;
      overflow: auto;
    }
    .wrap { max-width: 46rem; margin: 0 auto; }
    h1 { font-size: 1.55rem; margin: 0 0 0.35rem; letter-spacing: -0.02em; }
    h2 { font-size: 1.15rem; margin: 0 0 0.75rem; }
    h3 { font-size: 0.95rem; margin: 1rem 0 0.4rem; color: var(--muted); font-weight: 600; }
    h4 { font-size: 0.9rem; margin: 0 0 0.35rem; color: var(--accent); }
    .sub { color: var(--muted); font-size: 0.85rem; margin-bottom: 1.5rem; }
    .card {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 1.1rem 1.2rem;
      margin-bottom: 1rem;
    }
    .decision { border-color: var(--accent); }
    .prose { white-space: pre-wrap; word-break: break-word; }
    .lead { font-size: 1.05rem; }
    .meta { color: var(--muted); margin: 0 0 0.75rem; }
    ul, ol { margin: 0.25rem 0 0.75rem; padding-left: 1.2rem; }
    li { margin: 0.2rem 0; }
    .muted { color: var(--muted); }
    .speech {
      border-left: 2px solid var(--border);
      padding: 0.35rem 0 0.35rem 0.85rem;
      margin: 0.65rem 0;
    }
    .badge {
      display: inline-block;
      margin-top: 0.5rem;
      padding: 0.2rem 0.55rem;
      border-radius: 999px;
      background: var(--badge);
      color: var(--badge-ink);
      font-size: 0.8rem;
    }
    .edges { list-style: none; padding: 0; }
    .edges li {
      padding: 0.55rem 0;
      border-bottom: 1px solid var(--border);
    }
    .edges li:last-child { border-bottom: 0; }
    .rel { color: var(--accent); margin: 0 0.35rem; font-weight: 600; }
    .round-tag { color: var(--muted); font-size: 0.8rem; margin-left: 0.4rem; }
    .sum { color: var(--muted); font-size: 0.85rem; margin-top: 0.2rem; }
    footer { margin-top: 1.5rem; color: var(--muted); font-size: 0.8rem; }
  </style>
</head>
<body>
  <div class="wrap">
    <header>
      <h1>${esc(L.title)}</h1>
      <p class="sub">${esc(when)}${data.earlyExit ? ` · ${esc(L.early)}` : ''}</p>
    </header>

    <section class="card">
      <h2>${esc(L.issue)}</h2>
      <div class="prose">${esc(data.issue).replace(/\n/g, '<br/>')}</div>
    </section>

    <section class="card">
      <h2>${esc(L.plan)}</h2>
      <p class="meta"><strong>${esc(L.why)}:</strong> ${esc(data.rationale || '—')}</p>
      <p><strong>${esc(L.agenda)}</strong></p>
      <ol>${
        data.agenda.length
          ? data.agenda.map((a) => `<li>${esc(a)}</li>`).join('\n')
          : '<li class="muted">—</li>'
      }</ol>
    </section>

    ${roundsHtml}
    ${edgesHtml}
    ${decideHtml}

    <footer>${esc(L.footer)}</footer>
  </div>
</body>
</html>
`
}

/** Default deliverable filename under the session cwd / chat scratch. */
export const ROUNDTABLE_REPORT_FILENAME = 'roundtable-report.html'
