/**
 * Self-contained HTML reports for a convened roundtable (Chat artifact deliverables).
 *
 * Bundle:
 * - roundtable-report.html — hip summary (visual flow, debate graph, decision, roles)
 * - roundtable-report-{persona}.html — each seat's stance + exchanges
 *
 * Template: fixed TOC, wide main, data-jump nav, code blocks, collapsible prose, inline SVG.
 */
import { personaLabel } from './prompts.js'
import {
  metricsRow,
  PERSONA_HUE,
  svgDebateGraph,
  svgFlowPipeline,
  svgSeatArchitecture,
} from './report-diagrams.js'
import {
  collapsibleProse,
  esc,
  firstLine,
  richProseHtml,
  snip,
} from './report-prose.js'
import type {
  PersonaId,
  RoundtableEdgeResult,
  RoundtableLang,
  SpeechRecord,
  StageRecord,
} from './types.js'
import { PERSONA_IDS } from './types.js'

export interface RoundtableReportData {
  issue: string
  language: RoundtableLang
  agenda: string[]
  rationale: string
  rounds: Array<{
    round: number
    focus: string
    speeches: SpeechRecord[]
    stage: StageRecord
  }>
  decision?: {
    decision: string
    residual: string[]
    nextSteps: string[]
  }
  edges?: RoundtableEdgeResult[]
  earlyExit?: boolean
  generatedAt?: string
}

export interface RoundtableReportFile {
  filename: string
  html: string
  kind: 'main' | 'persona'
  persona?: PersonaId
}

const LABELS: Record<
  RoundtableLang,
  {
    title: string
    titlePersona: string
    toc: string
    issue: string
    plan: string
    agenda: string
    why: string
    round: string
    focus: string
    speeches: string
    stage: string
    agreed: string
    open: string
    edges: string
    discussion: string
    rebuttals: string
    decision: string
    residual: string
    next: string
    early: string
    footer: string
    footerPersona: string
    backToTop: string
    top: string
    subReports: string
    subReportsHint: string
    openMain: string
    hipBadge: string
    roleBadge: string
    myStance: string
    mySpeeches: string
    iRebutted: string
    iSupported: string
    iQuestioned: string
    rebuttedMe: string
    supportedMe: string
    questionedMe: string
    noExchange: string
    vsDecision: string
    process: string
    seats: string
    none: string
    more: string
    less: string
    overview: string
    flow: string
    architecture: string
    debateMap: string
    metricRounds: string
    metricSeats: string
    metricEdges: string
    metricRebuts: string
    detailsList: string
    keyPoints: string
  }
> = {
  en: {
    title: 'Roundtable report (hip summary)',
    titlePersona: 'Role report',
    toc: 'Contents',
    issue: 'Issue',
    plan: 'Meeting plan',
    agenda: 'Agenda',
    why: 'Why convened',
    round: 'Round',
    focus: 'Focus',
    speeches: 'Advisor speeches',
    stage: 'Stage conclusion (hip)',
    agreed: 'Agreed',
    open: 'Still open',
    edges: 'Debate map',
    discussion: 'Discussion process',
    rebuttals: 'Rebuttals & challenges',
    decision: 'Decision (hip)',
    residual: 'Residual disagreements',
    next: 'Next steps',
    early: 'Ended early',
    footer: 'Generated by hip roundtable',
    footerPersona: 'Role report · hip roundtable',
    backToTop: 'Back to top',
    top: 'Top',
    subReports: 'Role reports',
    subReportsHint: 'Open a seat report for that perspective. Browser links work; preview uses in-app open.',
    openMain: '← Back to hip summary',
    hipBadge: 'hip summary',
    roleBadge: 'role report',
    myStance: 'How I see it',
    mySpeeches: 'My contributions',
    iRebutted: 'I challenged',
    iSupported: 'I supported',
    iQuestioned: 'I questioned',
    rebuttedMe: 'Challenged me',
    supportedMe: 'Supported me',
    questionedMe: 'Asked me',
    noExchange: 'No direct exchanges recorded for this seat.',
    vsDecision: 'Against hip’s decision',
    process: 'Discussion flow',
    seats: 'Seats',
    none: '—',
    more: 'Show full text',
    less: 'Collapse',
    overview: 'At a glance',
    flow: 'Meeting flow',
    architecture: 'Council architecture',
    debateMap: 'Debate graph',
    metricRounds: 'Rounds',
    metricSeats: 'Seats',
    metricEdges: 'Exchanges',
    metricRebuts: 'Rebuttals',
    detailsList: 'Exchange list',
    keyPoints: 'Highlights',
  },
  'zh-CN': {
    title: '圆桌会议报告（hip 汇总）',
    titlePersona: '角色报告',
    toc: '目录',
    issue: '议题',
    plan: '会议规划',
    agenda: '议程',
    why: '召开原因',
    round: '第',
    focus: '焦点',
    speeches: '顾问发言',
    stage: '阶段性结论（hip）',
    agreed: '已共识',
    open: '仍开放',
    edges: '交锋图谱',
    discussion: '讨论过程',
    rebuttals: '反驳与挑战',
    decision: '决策（hip）',
    residual: '残留分歧',
    next: '后续步骤',
    early: '提前结束',
    footer: '由 hip 圆桌会议生成',
    footerPersona: '角色报告 · hip 圆桌会议',
    backToTop: '返回顶部',
    top: '顶部',
    subReports: '各角色子报告',
    subReportsHint: '点卡片进入该席位视角。浏览器中可直接跳转；侧栏预览会在应用内打开文件。',
    openMain: '← 返回 hip 汇总',
    hipBadge: 'hip 汇总',
    roleBadge: '角色报告',
    myStance: '我的理解',
    mySpeeches: '我的发言',
    iRebutted: '我反驳了',
    iSupported: '我附议了',
    iQuestioned: '我提问了',
    rebuttedMe: '反驳我的',
    supportedMe: '支持我的',
    questionedMe: '向我提问的',
    noExchange: '本席位未记录到直接交锋。',
    vsDecision: '对照 hip 决策',
    process: '讨论流程',
    seats: '席位',
    none: '—',
    more: '展开全文',
    less: '收起',
    overview: '一览',
    flow: '会议流程',
    architecture: '席位架构',
    debateMap: '交锋关系图',
    metricRounds: '轮次',
    metricSeats: '席位',
    metricEdges: '交锋',
    metricRebuts: '反驳',
    detailsList: '交锋明细',
    keyPoints: '要点',
  },
  'zh-TW': {
    title: '圓桌會議報告（hip 匯總）',
    titlePersona: '角色報告',
    toc: '目錄',
    issue: '議題',
    plan: '會議規劃',
    agenda: '議程',
    why: '召開原因',
    round: '第',
    focus: '焦點',
    speeches: '顧問發言',
    stage: '階段性結論（hip）',
    agreed: '已共識',
    open: '仍開放',
    edges: '交鋒圖譜',
    discussion: '討論過程',
    rebuttals: '反駁與挑戰',
    decision: '決策（hip）',
    residual: '殘留分歧',
    next: '後續步驟',
    early: '提前結束',
    footer: '由 hip 圓桌會議生成',
    footerPersona: '角色報告 · hip 圓桌會議',
    backToTop: '返回頂部',
    top: '頂部',
    subReports: '各角色子報告',
    subReportsHint: '點卡片進入該席位視角。瀏覽器可直接跳轉；側欄預覽會在應用內開啟。',
    openMain: '← 返回 hip 匯總',
    hipBadge: 'hip 匯總',
    roleBadge: '角色報告',
    myStance: '我的理解',
    mySpeeches: '我的發言',
    iRebutted: '我反駁了',
    iSupported: '我附議了',
    iQuestioned: '我提問了',
    rebuttedMe: '反駁我的',
    supportedMe: '支持我的',
    questionedMe: '向我提問的',
    noExchange: '本席位未記錄到直接交鋒。',
    vsDecision: '對照 hip 決策',
    process: '討論流程',
    seats: '席位',
    none: '—',
    more: '展開全文',
    less: '收起',
    overview: '一覽',
    flow: '會議流程',
    architecture: '席位架構',
    debateMap: '交鋒關係圖',
    metricRounds: '輪次',
    metricSeats: '席位',
    metricEdges: '交鋒',
    metricRebuts: '反駁',
    detailsList: '交鋒明細',
    keyPoints: '要點',
  },
  ja: {
    title: '円卓会議レポート（hip 要約）',
    titlePersona: '役割レポート',
    toc: '目次',
    issue: '議題',
    plan: '会議計画',
    agenda: 'アジェンダ',
    why: '開催理由',
    round: 'ラウンド',
    focus: '焦点',
    speeches: 'アドバイザー発言',
    stage: '段階結論 (hip)',
    agreed: '合意',
    open: '未決',
    edges: '議論マップ',
    discussion: '議論の流れ',
    rebuttals: '反論と挑戦',
    decision: '決定 (hip)',
    residual: '残る対立',
    next: '次のステップ',
    early: '早期終了',
    footer: 'hip 円卓会議が生成',
    footerPersona: '役割レポート · hip 円卓会議',
    backToTop: '先頭へ',
    top: '先頭',
    subReports: '役割別レポート',
    subReportsHint: 'カードから各席へ。ブラウザでリンク可。',
    openMain: '← hip 要約へ戻る',
    hipBadge: 'hip 要約',
    roleBadge: '役割',
    myStance: '私の理解',
    mySpeeches: '私の発言',
    iRebutted: '反論した相手',
    iSupported: '支持した相手',
    iQuestioned: '質問した相手',
    rebuttedMe: '私への反論',
    supportedMe: '私への支持',
    questionedMe: '私への質問',
    noExchange: '直接のやり取りは記録されていません。',
    vsDecision: 'hip 決定との対照',
    process: '議論フロー',
    seats: '席',
    none: '—',
    more: '全文を表示',
    less: '折りたたむ',
    overview: '概要',
    flow: '会議フロー',
    architecture: '構成',
    debateMap: '議論グラフ',
    metricRounds: 'ラウンド',
    metricSeats: '席',
    metricEdges: 'やり取り',
    metricRebuts: '反論',
    detailsList: '詳細リスト',
    keyPoints: '要点',
  },
  ko: {
    title: '원탁 회의 보고서 (hip 요약)',
    titlePersona: '역할 보고서',
    toc: '목차',
    issue: '안건',
    plan: '회의 계획',
    agenda: '안건 목록',
    why: '소집 이유',
    round: '라운드',
    focus: '초점',
    speeches: '자문 발언',
    stage: '단계 결론 (hip)',
    agreed: '합의',
    open: '미결',
    edges: '논쟁 지도',
    discussion: '토론 과정',
    rebuttals: '반박과 도전',
    decision: '결정 (hip)',
    residual: '잔여 이견',
    next: '다음 단계',
    early: '조기 종료',
    footer: 'hip 원탁 회의 생성',
    footerPersona: '역할 보고서 · hip 원탁',
    backToTop: '맨 위로',
    top: '맨 위',
    subReports: '역할별 보고서',
    subReportsHint: '카드로 각 좌석 보고서를 엽니다.',
    openMain: '← hip 요약으로',
    hipBadge: 'hip 요약',
    roleBadge: '역할',
    myStance: '나의 이해',
    mySpeeches: '나의 발언',
    iRebutted: '내가 반박한 대상',
    iSupported: '내가 지지한 대상',
    iQuestioned: '내가 질문한 대상',
    rebuttedMe: '나를 반박한',
    supportedMe: '나를 지지한',
    questionedMe: '나에게 질문한',
    noExchange: '직접 교환이 기록되지 않았습니다.',
    vsDecision: 'hip 결정 대비',
    process: '토론 흐름',
    seats: '좌석',
    none: '—',
    more: '전문 보기',
    less: '접기',
    overview: '한눈에',
    flow: '회의 흐름',
    architecture: '구성',
    debateMap: '논쟁 그래프',
    metricRounds: '라운드',
    metricSeats: '좌석',
    metricEdges: '교환',
    metricRebuts: '반박',
    detailsList: '상세 목록',
    keyPoints: '핵심',
  },
}

type Labels = (typeof LABELS)[RoundtableLang]

interface TocItem {
  id: string
  label: string
  depth: 1 | 2
}

export const ROUNDTABLE_REPORT_FILENAME = 'roundtable-report.html'

export function personaReportFilename(persona: PersonaId): string {
  return `roundtable-report-${persona}.html`
}

function jumpLink(id: string, label: string, className = ''): string {
  const cls = className ? ` class="${esc(className)}"` : ''
  return `<a href="#${esc(id)}" data-jump="${esc(id)}"${cls}>${label}</a>`
}

function fileLink(href: string, label: string, className = ''): string {
  const cls = className ? ` class="${esc(className)}"` : ''
  return `<a href="${esc(href)}" data-file="${esc(href)}"${cls}>${label}</a>`
}

function backLink(L: Labels): string {
  return `<p class="back">${jumpLink('top', esc(L.backToTop))}</p>`
}

function sectionOpen(id: string, title: string, extraClass = ''): string {
  const cls = extraClass ? ` card ${extraClass}` : ' card'
  return `<section id="${esc(id)}" class="${cls.trim()}" tabindex="-1">
  <h2>${jumpLink(id, '#', 'anchor')}${esc(title)}</h2>`
}

function bullets(items: string[]): string {
  if (!items.length) return '<li class="muted">—</li>'
  return items.map((x) => `<li>${esc(x)}</li>`).join('\n')
}

function roundHeading(lang: RoundtableLang, n: number): string {
  const L = LABELS[lang]
  if (lang === 'zh-CN' || lang === 'zh-TW') return `${L.round} ${n} 轮`
  if (lang === 'ja') return `${L.round} ${n}`
  if (lang === 'ko') return `${L.round} ${n}`
  return `${L.round} ${n}`
}

function edgeRel(lang: RoundtableLang, rel: string): string {
  if (lang === 'zh-CN' || lang === 'zh-TW') {
    if (rel === 'rebut') return '反驳'
    if (rel === 'support') return '附议'
    return '提问'
  }
  if (lang === 'ja') {
    if (rel === 'rebut') return '反論'
    if (rel === 'support') return '支持'
    return '質問'
  }
  if (lang === 'ko') {
    if (rel === 'rebut') return '반박'
    if (rel === 'support') return '지지'
    return '질문'
  }
  return rel
}

function personaName(id: string, lang: RoundtableLang): string {
  if ((PERSONA_IDS as readonly string[]).includes(id)) {
    return personaLabel(id as PersonaId, lang)
  }
  return id
}

export const ROUNDTABLE_REPORT_NAV_SCRIPT = /* js */ `
(function () {
  var main = document.getElementById('report-main');
  function jump(id) {
    if (!id) return;
    if (id === 'top') {
      if (main) main.scrollTo({ top: 0, behavior: 'smooth' });
      else window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }
    var el = document.getElementById(id);
    if (!el) return;
    if (main && main.contains(el)) {
      var top = el.getBoundingClientRect().top - main.getBoundingClientRect().top + main.scrollTop - 12;
      main.scrollTo({ top: top, behavior: 'smooth' });
    } else {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }
  function openSibling(file) {
    if (!file) return false;
    if (!window.parent || window.parent === window) return false;
    try {
      window.parent.postMessage(
        { source: 'hip-roundtable-report', type: 'open-file', file: file },
        '*'
      );
      return true;
    } catch (err) {
      return false;
    }
  }
  document.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[data-jump], a[data-file]') : null;
    if (!a) return;
    if (a.hasAttribute('data-jump')) {
      e.preventDefault();
      jump(a.getAttribute('data-jump'));
      return;
    }
    var file = a.getAttribute('data-file');
    if (file && openSibling(file)) {
      e.preventDefault();
    }
  });
})();
`.trim()

export const ROUNDTABLE_REPORT_STYLES = /* css */ `
:root {
  --bg: #0b0d12;
  --card: #141820;
  --ink: #e8eaed;
  --muted: #9aa0a6;
  --accent: #7aa2ff;
  --accent-soft: rgba(122, 162, 255, 0.14);
  --border: #2a2f3a;
  --badge: #3d2a12;
  --badge-ink: #f0c674;
  --rebut: #f07178;
  --rebut-soft: rgba(240, 113, 120, 0.12);
  --support: #7fd99a;
  --support-soft: rgba(127, 217, 154, 0.12);
  --question: #e0b45a;
  --question-soft: rgba(224, 180, 90, 0.12);
  --code-bg: #0a0c10;
  --code-border: #2c3340;
  --code-ink: #d7dde8;
  --toc-w: 15.5rem;
  --radius: 14px;
  --shadow: 0 1px 0 rgba(255,255,255,0.03) inset;
  --glow: 0 12px 40px rgba(0,0,0,0.35);
  --diag-issue-fill: rgba(122, 162, 255, 0.12);
  --diag-issue-stroke: #7aa2ff;
  --diag-round-fill: rgba(255,255,255,0.04);
  --diag-round-stroke: #4a5568;
  --diag-decision-fill: rgba(127, 217, 154, 0.12);
  --diag-decision-stroke: #7fd99a;
  --diag-ring: #3a4252;
}
@media (prefers-color-scheme: light) {
  :root {
    --bg: #eef1f6;
    --card: #ffffff;
    --ink: #1a1d23;
    --muted: #5f6368;
    --accent: #3b6ef5;
    --accent-soft: rgba(59, 110, 245, 0.1);
    --border: #e2e5eb;
    --badge: #fff4e0;
    --badge-ink: #8a5a00;
    --rebut: #c23b3b;
    --rebut-soft: rgba(194, 59, 59, 0.08);
    --support: #1a7f4b;
    --support-soft: rgba(26, 127, 75, 0.08);
    --question: #9a6b00;
    --question-soft: rgba(154, 107, 0, 0.08);
    --code-bg: #f6f8fb;
    --code-border: #d8dee8;
    --code-ink: #1f2937;
    --shadow: 0 1px 2px rgba(16, 24, 40, 0.04);
    --glow: 0 12px 32px rgba(16, 24, 40, 0.07);
    --diag-issue-fill: rgba(59, 110, 245, 0.08);
    --diag-issue-stroke: #3b6ef5;
    --diag-round-fill: #f8fafc;
    --diag-round-stroke: #c5ccd8;
    --diag-decision-fill: rgba(26, 127, 75, 0.08);
    --diag-decision-stroke: #1a7f4b;
    --diag-ring: #c5ccd8;
  }
}
* { box-sizing: border-box; }
html, body { height: 100%; margin: 0; overflow: hidden; }
body {
  font: 15px/1.55 system-ui, -apple-system, "Segoe UI", "PingFang SC", "Noto Sans SC", sans-serif;
  color: var(--ink);
  background:
    radial-gradient(1000px 520px at 8% -8%, color-mix(in srgb, var(--accent) 14%, transparent), transparent 55%),
    radial-gradient(800px 420px at 100% 0%, color-mix(in srgb, var(--support) 10%, transparent), transparent 50%),
    var(--bg);
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

.shell { display: flex; flex-direction: column; height: 100%; width: 100%; min-height: 0; }
@media (min-width: 720px) { .shell { flex-direction: row; } }

.toc {
  flex: 0 0 auto; border-bottom: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 92%, transparent);
  backdrop-filter: blur(8px);
  padding: 0.75rem 0.85rem 0.85rem; max-height: 38vh; overflow: auto;
}
@media (min-width: 720px) {
  .toc {
    width: var(--toc-w); min-width: var(--toc-w); max-width: var(--toc-w);
    max-height: none; height: 100%; border-bottom: 0; border-right: 1px solid var(--border);
    padding: 1rem 0.85rem 1.25rem;
  }
}
.toc-title {
  font-size: 0.72rem; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase;
  color: var(--muted); margin: 0 0 0.55rem; padding: 0 0.35rem;
}
.toc ol { list-style: none; margin: 0; padding: 0; }
.toc a {
  display: block; padding: 0.38rem 0.5rem; border-radius: 8px; color: var(--ink);
  font-size: 0.88rem; line-height: 1.35; text-decoration: none; cursor: pointer;
}
.toc a:hover { background: var(--accent-soft); color: var(--accent); text-decoration: none; }
.toc .depth-2 a { padding-left: 1rem; font-size: 0.82rem; color: var(--muted); }

#report-main {
  flex: 1 1 auto; min-width: 0; min-height: 0; overflow: auto; width: 100%;
}
.main-inner { width: 100%; max-width: none; margin: 0; padding: 1.1rem 1.25rem 2.5rem; }
@media (min-width: 720px) { .main-inner { padding: 1.35rem 1.75rem 3rem; } }
@media (min-width: 1200px) { .main-inner { padding: 1.5rem 2.25rem 3rem; } }

.report-header {
  margin-bottom: 1rem; padding: 1.15rem 1.25rem; border-radius: var(--radius);
  border: 1px solid var(--border);
  background: linear-gradient(135deg, color-mix(in srgb, var(--card) 88%, var(--accent-soft)), var(--card));
  box-shadow: var(--glow);
}
.report-header h1 {
  font-size: 1.5rem; margin: 0.35rem 0 0.35rem; letter-spacing: -0.02em; line-height: 1.25;
}
.sub { color: var(--muted); font-size: 0.85rem; margin: 0; }
.pill {
  display: inline-flex; align-items: center; gap: 0.35rem;
  padding: 0.18rem 0.6rem; border-radius: 999px; font-size: 0.72rem; font-weight: 700;
  letter-spacing: 0.04em; text-transform: uppercase;
  background: var(--accent-soft); color: var(--accent);
  border: 1px solid color-mix(in srgb, var(--accent) 35%, var(--border));
}
.pill.role {
  background: color-mix(in srgb, hsl(var(--persona-h, 220) 55% 50%) 16%, transparent);
  color: hsl(var(--persona-h, 220) 60% 68%);
  border-color: color-mix(in srgb, hsl(var(--persona-h, 220) 55% 50%) 35%, var(--border));
}

.metrics {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(6.5rem, 1fr));
  gap: 0.55rem; margin: 0.85rem 0 0.25rem;
}
.metric {
  padding: 0.7rem 0.75rem; border-radius: 12px; border: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 90%, transparent); text-align: center;
}
.metric-value {
  font-size: 1.35rem; font-weight: 750; letter-spacing: -0.03em;
  font-variant-numeric: tabular-nums; color: var(--accent);
}
.metric-label { font-size: 0.72rem; color: var(--muted); margin-top: 0.15rem; }

.card {
  background: var(--card); border: 1px solid var(--border); border-radius: var(--radius);
  padding: 1.1rem 1.25rem; margin-bottom: 0.9rem; box-shadow: var(--shadow);
  scroll-margin-top: 0.75rem;
}
.decision {
  border-color: color-mix(in srgb, var(--accent) 55%, var(--border));
  background: linear-gradient(180deg, color-mix(in srgb, var(--accent-soft) 70%, var(--card)), var(--card));
}
.card.diagram-card { padding-bottom: 1.35rem; }
h2 {
  font-size: 1.08rem; margin: 0 0 0.7rem; line-height: 1.3;
  display: flex; align-items: baseline; gap: 0.35rem;
}
h2 .anchor {
  color: var(--muted); font-weight: 500; font-size: 0.9em; opacity: 0; text-decoration: none;
}
.card:hover h2 .anchor, h2:focus-within .anchor { opacity: 0.7; }
h3 { font-size: 0.9rem; margin: 0.9rem 0 0.4rem; color: var(--muted); font-weight: 600; }
h4 { font-size: 0.9rem; margin: 0 0 0.35rem; color: var(--accent); }
.prose { word-break: break-word; }
.prose-p { margin: 0 0 0.55rem; white-space: pre-wrap; }
.prose-p:last-child { margin-bottom: 0; }
.lead .prose-p, .lead { font-size: 1.04rem; }
.meta { color: var(--muted); margin: 0 0 0.65rem; font-size: 0.9rem; }
ul, ol { margin: 0.2rem 0 0.55rem; padding-left: 1.15rem; }
li { margin: 0.15rem 0; }
.muted { color: var(--muted); }
.hint { font-size: 0.82rem; color: var(--muted); margin: 0.25rem 0 0.65rem; line-height: 1.45; }

/* Code */
.inline-code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 0.88em; padding: 0.1em 0.35em; border-radius: 5px;
  background: var(--code-bg); border: 1px solid var(--code-border); color: var(--code-ink);
}
.code-block {
  position: relative; margin: 0.55rem 0 0.75rem; border-radius: 10px;
  border: 1px solid var(--code-border); background: var(--code-bg); overflow: hidden;
}
.code-block .code-lang {
  display: block; padding: 0.3rem 0.7rem; font-size: 0.7rem; font-weight: 700;
  letter-spacing: 0.04em; text-transform: uppercase; color: var(--muted);
  border-bottom: 1px solid var(--code-border); background: color-mix(in srgb, var(--card) 50%, var(--code-bg));
}
.code-block pre {
  margin: 0; padding: 0.75rem 0.85rem; overflow: auto; max-height: 22rem;
}
.code-block code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 0.82rem; line-height: 1.5; color: var(--code-ink); white-space: pre;
}

/* Fold long text */
.prose-fold .prose-preview {
  margin: 0 0 0.35rem; color: var(--ink); font-size: 0.95rem; line-height: 1.45;
}
.fold { margin: 0; border: 0; }
.fold > summary {
  cursor: pointer; list-style: none; display: inline-flex; align-items: center; gap: 0.25rem;
  font-size: 0.8rem; font-weight: 600; color: var(--accent); user-select: none;
  padding: 0.15rem 0;
}
.fold > summary::-webkit-details-marker { display: none; }
.fold > summary .less { display: none; }
.fold[open] > summary .more { display: none; }
.fold[open] > summary .less { display: inline; }
.fold-body { margin-top: 0.55rem; padding-top: 0.55rem; border-top: 1px dashed var(--border); }

.speech {
  border-left: 3px solid hsl(var(--persona-h, 220) 55% 55%);
  padding: 0.5rem 0.8rem 0.5rem 0.9rem; margin: 0.55rem 0;
  background: color-mix(in srgb, var(--card) 85%, hsl(var(--persona-h, 220) 40% 50%));
  border-radius: 0 10px 10px 0;
}
.speech-head {
  display: flex; flex-wrap: wrap; align-items: center; gap: 0.35rem 0.65rem; margin-bottom: 0.3rem;
}
.speech-head h4 { margin: 0; color: hsl(var(--persona-h, 220) 55% 68%); }
.speech a.role-link { font-size: 0.78rem; color: var(--muted); }

.badge {
  display: inline-block; margin-top: 0.45rem; padding: 0.2rem 0.55rem; border-radius: 999px;
  background: var(--badge); color: var(--badge-ink); font-size: 0.8rem;
}

/* Diagrams */
.diagram-wrap {
  margin: 0.35rem 0 0.5rem; padding: 0.65rem; border-radius: 12px;
  border: 1px solid var(--border); background: color-mix(in srgb, var(--bg) 55%, var(--card));
  overflow-x: auto;
}
.diagram { display: block; }
.flow-label {
  fill: var(--ink); font-size: 12px; font-weight: 700;
  font-family: system-ui, -apple-system, sans-serif;
}
.flow-sub {
  fill: var(--muted); font-size: 10px;
  font-family: system-ui, -apple-system, sans-serif;
}
.flow-arrow { stroke: var(--accent); stroke-width: 1.75; }
.flow-arrow-head { fill: var(--accent); }
.debate-node-label, .arch-chair-label {
  fill: #fff; font-size: 10px; font-weight: 700;
  font-family: system-ui, -apple-system, "PingFang SC", sans-serif;
  paint-order: stroke; stroke: rgba(0,0,0,0.35); stroke-width: 2px;
}
.legend-text {
  fill: var(--muted); font-size: 11px;
  font-family: system-ui, -apple-system, "PingFang SC", sans-serif;
}
.diagram-row {
  display: grid; grid-template-columns: 1fr; gap: 0.75rem;
}
@media (min-width: 960px) {
  .diagram-row.two { grid-template-columns: 1.15fr 0.85fr; align-items: start; }
}

.edges { list-style: none; padding: 0; margin: 0; }
.edges li {
  display: grid; gap: 0.2rem; padding: 0.55rem 0.75rem; margin: 0.35rem 0;
  border-radius: 10px; border: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 90%, transparent);
}
.edge-line {
  display: flex; flex-wrap: wrap; align-items: center; gap: 0.3rem 0.4rem; font-size: 0.9rem;
}
.rel-chip {
  display: inline-flex; align-items: center; padding: 0.1rem 0.45rem; border-radius: 999px;
  font-size: 0.72rem; font-weight: 700;
}
.rel-chip.rebut {
  background: var(--rebut-soft); color: var(--rebut);
  border: 1px solid color-mix(in srgb, var(--rebut) 35%, var(--border));
}
.rel-chip.support {
  background: var(--support-soft); color: var(--support);
  border: 1px solid color-mix(in srgb, var(--support) 35%, var(--border));
}
.rel-chip.question {
  background: var(--question-soft); color: var(--question);
  border: 1px solid color-mix(in srgb, var(--question) 35%, var(--border));
}
.round-tag {
  color: var(--muted); font-size: 0.76rem; font-variant-numeric: tabular-nums;
}
.sum { color: var(--muted); font-size: 0.85rem; line-height: 1.4; }

.stage-grid { display: grid; grid-template-columns: 1fr; gap: 0.65rem; }
@media (min-width: 800px) { .stage-grid { grid-template-columns: 1fr 1fr; } }
.stage-col {
  padding: 0.55rem 0.7rem; border-radius: 10px; border: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 94%, var(--accent-soft));
}
.stage-col h3 { margin-top: 0; }

.role-grid {
  display: grid; grid-template-columns: repeat(auto-fill, minmax(11rem, 1fr));
  gap: 0.65rem; margin: 0.4rem 0 0.2rem;
}
.role-card {
  display: flex; flex-direction: column; gap: 0.3rem; padding: 0.85rem 0.9rem;
  border-radius: 12px; border: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 88%, hsl(var(--persona-h, 220) 40% 50%));
  text-decoration: none !important; color: inherit; min-height: 5.2rem;
  transition: border-color 0.15s ease, transform 0.15s ease, box-shadow 0.15s ease;
}
.role-card:hover {
  border-color: color-mix(in srgb, hsl(var(--persona-h, 220) 55% 50%) 55%, var(--border));
  transform: translateY(-1px); box-shadow: var(--glow); text-decoration: none !important;
}
.role-card .name {
  font-weight: 700; font-size: 0.95rem; color: hsl(var(--persona-h, 220) 55% 68%);
}
.role-card .snip {
  font-size: 0.78rem; color: var(--muted); line-height: 1.35;
  display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden;
}
.role-card .go { margin-top: auto; font-size: 0.76rem; color: var(--accent); font-weight: 600; }

.exchange-block {
  margin: 0.55rem 0; padding: 0.55rem 0.75rem; border-radius: 10px; border: 1px solid var(--border);
}
.exchange-block h4 {
  margin: 0 0 0.35rem; font-size: 0.82rem; color: var(--muted); font-weight: 650;
}
.exchange-block.rebut { border-color: color-mix(in srgb, var(--rebut) 30%, var(--border)); }
.exchange-block.support { border-color: color-mix(in srgb, var(--support) 30%, var(--border)); }
.exchange-block.question { border-color: color-mix(in srgb, var(--question) 30%, var(--border)); }

.highlights {
  display: flex; flex-wrap: wrap; gap: 0.4rem; margin: 0.35rem 0 0.15rem;
}
.chip {
  display: inline-flex; align-items: center; max-width: 100%;
  padding: 0.28rem 0.6rem; border-radius: 999px; font-size: 0.8rem;
  background: var(--accent-soft); color: var(--ink);
  border: 1px solid color-mix(in srgb, var(--accent) 25%, var(--border));
}
.chip.open {
  background: var(--question-soft);
  border-color: color-mix(in srgb, var(--question) 30%, var(--border));
}

.back { margin: 0.75rem 0 0; font-size: 0.8rem; }
.back a { color: var(--muted); }
.back a:hover { color: var(--accent); }
.nav-row { display: flex; flex-wrap: wrap; gap: 0.5rem 0.85rem; margin-bottom: 0.3rem; }
.nav-row a.file-nav { font-size: 0.85rem; font-weight: 600; }
.report-footer {
  margin-top: 1.15rem; padding-top: 0.7rem; border-top: 1px solid var(--border);
  color: var(--muted); font-size: 0.8rem;
}
.skip-link {
  position: absolute; left: -9999px; top: 0; background: var(--accent); color: #fff;
  padding: 0.4rem 0.7rem; z-index: 10; border-radius: 0 0 6px 0;
}
.skip-link:focus { left: 0; }
.decision-lead { font-size: 1.12rem; font-weight: 600; line-height: 1.45; margin: 0 0 0.65rem; }
`.trim()

function speakersInData(data: RoundtableReportData): PersonaId[] {
  const seen = new Set<PersonaId>()
  for (const r of data.rounds) {
    for (const s of r.speeches) {
      if ((PERSONA_IDS as readonly string[]).includes(s.speaker)) seen.add(s.speaker)
    }
  }
  return PERSONA_IDS.filter((id) => seen.has(id))
}

function seatLabelMap(lang: RoundtableLang, seats: PersonaId[]): Record<string, string> {
  const m: Record<string, string> = {}
  for (const id of seats) m[id] = personaLabel(id, lang)
  return m
}

function edgeListHtml(
  edges: RoundtableEdgeResult[],
  lang: RoundtableLang,
  opts?: { linkRoles?: boolean },
): string {
  if (!edges.length) return `<p class="muted">—</p>`
  return `<ul class="edges">
    ${edges
      .map((e) => {
        const from = opts?.linkRoles
          ? fileLink(personaReportFilename(e.from as PersonaId), esc(personaName(e.from, lang)))
          : esc(personaName(e.from, lang))
        const to = opts?.linkRoles
          ? fileLink(personaReportFilename(e.to as PersonaId), esc(personaName(e.to, lang)))
          : esc(personaName(e.to, lang))
        const relClass =
          e.relation === 'rebut' || e.relation === 'support' || e.relation === 'question'
            ? e.relation
            : 'question'
        return `<li>
          <div class="edge-line">
            <span class="from">${from}</span>
            <span class="rel-chip ${relClass}">${esc(edgeRel(lang, e.relation))}</span>
            <span class="to">${to}</span>
            <span class="round-tag">R${e.round}</span>
          </div>
          ${e.summary ? `<div class="sum">${esc(e.summary)}</div>` : ''}
        </li>`
      })
      .join('\n')}
  </ul>`
}

function speechArticle(
  s: SpeechRecord,
  lang: RoundtableLang,
  L: Labels,
  round: number,
  opts?: { linkRole?: boolean },
): string {
  const hue = PERSONA_HUE[s.speaker] ?? '220'
  const name = personaLabel(s.speaker, lang)
  const roleHref = personaReportFilename(s.speaker)
  const link = opts?.linkRole
    ? ` ${fileLink(roleHref, lang === 'zh-CN' || lang === 'zh-TW' ? '子报告 →' : 'role report →', 'role-link')}`
    : ''
  return `
        <article class="speech" style="--persona-h:${hue}" id="sec-round-${round}-${esc(s.speaker)}">
          <div class="speech-head">
            <h4>${esc(name)}</h4>${link}
          </div>
          ${collapsibleProse(s.content, { more: L.more, less: L.less })}
        </article>`
}

function documentShell(args: {
  lang: RoundtableLang
  title: string
  issueTitle: string
  headerHtml: string
  toc: TocItem[]
  bodyHtml: string
  footer: string
}): string {
  const L = LABELS[args.lang]
  const tocHtml = `
<nav class="toc" id="toc" aria-label="${esc(L.toc)}">
  <p class="toc-title">${esc(L.toc)}</p>
  <ol>
    ${args.toc
      .map((item) => `<li class="depth-${item.depth}">${jumpLink(item.id, esc(item.label))}</li>`)
      .join('\n    ')}
  </ol>
</nav>`

  return `<!DOCTYPE html>
<html lang="${esc(args.lang)}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="generator" content="hip-roundtable" />
  <title>${esc(args.title)} — ${esc(args.issueTitle)}</title>
  <style>
${ROUNDTABLE_REPORT_STYLES}
  </style>
</head>
<body>
  ${jumpLink(args.toc[0]?.id ?? 'top', esc(L.issue), 'skip-link')}
  <div class="shell" id="top">
    ${tocHtml}
    <div id="report-main">
      <div class="main-inner">
        ${args.headerHtml}
        ${args.bodyHtml}
        <footer class="report-footer">${esc(args.footer)}</footer>
      </div>
    </div>
  </div>
  <script>
${ROUNDTABLE_REPORT_NAV_SCRIPT}
  </script>
</body>
</html>
`
}

/** Build hip summary HTML (single file). */
export function buildRoundtableReportHtml(data: RoundtableReportData): string {
  return buildMainReport(data, speakersInData(data))
}

function buildMainReport(data: RoundtableReportData, seats: PersonaId[]): string {
  const lang = data.language
  const L = LABELS[lang]
  const when = data.generatedAt ?? new Date().toISOString()
  const issueTitle = data.issue.replace(/\s+/g, ' ').trim().slice(0, 80)
  const edges = data.edges ?? []
  const rebutEdges = edges.filter((e) => e.relation === 'rebut')
  const otherEdges = edges.filter((e) => e.relation !== 'rebut')
  const labelsMap = seatLabelMap(lang, seats)

  const toc: TocItem[] = [
    { id: 'sec-overview', label: L.overview, depth: 1 },
    { id: 'sec-decision', label: L.decision, depth: 1 },
    { id: 'sec-process', label: L.process, depth: 1 },
  ]
  for (const r of data.rounds) {
    toc.push({
      id: `sec-round-${r.round}`,
      label: roundHeading(lang, r.round),
      depth: 2,
    })
  }
  if (edges.length > 0) toc.push({ id: 'sec-edges', label: L.edges, depth: 1 })
  if (seats.length > 0) toc.push({ id: 'sec-roles', label: L.subReports, depth: 1 })

  // If no decision yet, still show overview/issue
  if (!data.decision) {
    toc.splice(1, 1, { id: 'sec-issue', label: L.issue, depth: 1 })
  }

  const metrics = metricsRow([
    { label: L.metricRounds, value: String(data.rounds.length) },
    { label: L.metricSeats, value: String(seats.length) },
    { label: L.metricEdges, value: String(edges.length) },
    { label: L.metricRebuts, value: String(rebutEdges.length) },
  ])

  const flowSvg = svgFlowPipeline({
    lang,
    issue: data.issue,
    rounds: data.rounds.map((r) => ({ round: r.round, focus: r.focus })),
    decision: data.decision?.decision,
    labels: {
      issue: L.issue,
      decision: L.decision,
      round: (n) => roundHeading(lang, n),
    },
  })

  const archSvg = seats.length
    ? svgSeatArchitecture({
        lang,
        seats,
        seatLabels: labelsMap,
        chairLabel: 'hip',
        title: L.architecture,
      })
    : ''

  const debateSvg =
    edges.length > 0 && seats.length
      ? svgDebateGraph({
          lang,
          seats,
          seatLabels: labelsMap,
          edges,
          title: L.debateMap,
        })
      : ''

  const overviewHtml = `
${sectionOpen('sec-overview', L.overview, 'diagram-card')}
  <p class="meta"><strong>${esc(L.issue)}:</strong> ${esc(firstLine(data.issue, 160))}</p>
  ${
    data.rationale
      ? `<p class="meta"><strong>${esc(L.why)}:</strong> ${esc(snip(data.rationale, 120))}</p>`
      : ''
  }
  ${metrics}
  <h3>${esc(L.flow)}</h3>
  ${flowSvg}
  ${
    archSvg
      ? `<h3>${esc(L.architecture)}</h3>
  <div class="diagram-row">${archSvg}</div>`
      : ''
  }
  ${
    data.agenda.length
      ? `<h3>${esc(L.agenda)}</h3>
  <div class="highlights">${data.agenda.map((a) => `<span class="chip">${esc(a)}</span>`).join('')}</div>`
      : ''
  }
  ${backLink(L)}
</section>`

  const decide = data.decision
  const decideHtml = decide
    ? `
${sectionOpen('sec-decision', L.decision, 'decision')}
  <p class="decision-lead">${esc(snip(decide.decision, 400))}</p>
  ${
    decide.decision.length > 400
      ? collapsibleProse(decide.decision, { more: L.more, less: L.less }, 400)
      : /```/.test(decide.decision)
        ? `<div class="prose">${richProseHtml(decide.decision)}</div>`
        : ''
  }
  <div class="stage-grid">
    <div class="stage-col">
      <h3>${esc(L.residual)}</h3>
      <ul>${bullets(decide.residual)}</ul>
    </div>
    <div class="stage-col">
      <h3>${esc(L.next)}</h3>
      <ol>${
        decide.nextSteps.length
          ? decide.nextSteps.map((x) => `<li>${esc(x)}</li>`).join('\n')
          : `<li class="muted">${esc(L.none)}</li>`
      }</ol>
    </div>
  </div>
  ${data.earlyExit ? `<p class="badge">${esc(L.early)}</p>` : ''}
  ${backLink(L)}
</section>`
    : `
${sectionOpen('sec-issue', L.issue)}
  ${collapsibleProse(data.issue, { more: L.more, less: L.less }, 180)}
  ${backLink(L)}
</section>`

  const processHtml = `
${sectionOpen('sec-process', L.process, 'diagram-card process')}
  <p class="hint">${esc(L.discussion)}</p>
  ${
    debateSvg
      ? `<h3>${esc(L.debateMap)}</h3>${debateSvg}`
      : ''
  }
  <div class="highlights" style="margin-top:0.75rem">
    ${data.rounds
      .map(
        (r) =>
          `<a class="chip" href="#sec-round-${r.round}" data-jump="sec-round-${r.round}">${esc(roundHeading(lang, r.round))}: ${esc(snip(r.focus, 24))}</a>`,
      )
      .join('')}
  </div>
  ${backLink(L)}
</section>`

  const roundsHtml = data.rounds
    .map((r) => {
      const speeches = r.speeches
        .map((s) => speechArticle(s, lang, L, r.round, { linkRole: seats.includes(s.speaker) }))
        .join('\n')
      const roundEdges = edges.filter((e) => e.round === r.round)
      const agreedChips = r.stage.agreed
        .slice(0, 6)
        .map((a) => `<span class="chip">${esc(a)}</span>`)
        .join('')
      const openChips = r.stage.open
        .slice(0, 6)
        .map((a) => `<span class="chip open">${esc(a)}</span>`)
        .join('')
      return `
${sectionOpen(`sec-round-${r.round}`, roundHeading(lang, r.round), 'round')}
  <p class="meta"><strong>${esc(L.focus)}:</strong> ${esc(r.focus)}</p>
  ${
    agreedChips || openChips
      ? `<h3>${esc(L.keyPoints)}</h3>
  <div class="highlights">${agreedChips}${openChips}</div>`
      : ''
  }
  <h3>${esc(L.speeches)}</h3>
  <div class="speeches">${speeches || `<p class="muted">${esc(L.none)}</p>`}</div>
  ${
    roundEdges.length
      ? `<details class="fold" style="margin-top:0.65rem">
    <summary><span class="more">${esc(L.detailsList)} (${roundEdges.length})</span><span class="less">${esc(L.less)}</span></summary>
    <div class="fold-body">${edgeListHtml(roundEdges, lang, { linkRoles: true })}</div>
  </details>`
      : ''
  }
  <h3>${esc(L.stage)}</h3>
  <div class="stage-grid">
    <div class="stage-col">
      <h3>${esc(L.agreed)}</h3>
      <ul>${bullets(r.stage.agreed)}</ul>
    </div>
    <div class="stage-col">
      <h3>${esc(L.open)}</h3>
      <ul>${bullets(r.stage.open)}</ul>
    </div>
  </div>
  ${
    r.stage.earlyExit
      ? `<p class="badge">${esc(L.early)}${r.stage.earlyExitReason ? `: ${esc(r.stage.earlyExitReason)}` : ''}</p>`
      : ''
  }
  ${backLink(L)}
</section>`
    })
    .join('\n')

  const edgesHtml =
    edges.length === 0
      ? ''
      : `
${sectionOpen('sec-edges', L.edges, 'diagram-card')}
  ${debateSvg || ''}
  <details class="fold" style="margin-top:0.75rem">
    <summary><span class="more">${esc(L.detailsList)}</span><span class="less">${esc(L.less)}</span></summary>
    <div class="fold-body">
      ${otherEdges.length ? edgeListHtml(otherEdges, lang, { linkRoles: true }) : ''}
      ${
        rebutEdges.length
          ? `<div id="sec-rebuttals" tabindex="-1">
        <h3>${esc(L.rebuttals)}</h3>
        ${edgeListHtml(rebutEdges, lang, { linkRoles: true })}
      </div>`
          : ''
      }
    </div>
  </details>
  ${backLink(L)}
</section>`

  const openLabel = lang === 'zh-CN' || lang === 'zh-TW' ? '打开子报告 →' : 'Open →'
  const rolesHtml =
    seats.length === 0
      ? ''
      : `
${sectionOpen('sec-roles', L.subReports)}
  <p class="hint">${esc(L.subReportsHint)}</p>
  <div class="role-grid">
    ${seats
      .map((id) => {
        const hue = PERSONA_HUE[id]
        const first =
          data.rounds.flatMap((r) => r.speeches).find((s) => s.speaker === id)?.content ?? ''
        const href = personaReportFilename(id)
        return `<a class="role-card" style="--persona-h:${hue}" href="${esc(href)}" data-file="${esc(href)}">
      <span class="name">${esc(personaLabel(id, lang))}</span>
      <span class="snip">${esc(firstLine(first, 90) || L.none)}</span>
      <span class="go">${esc(openLabel)}</span>
    </a>`
      })
      .join('\n    ')}
  </div>
  ${backLink(L)}
</section>`

  const headerHtml = `
<header class="report-header">
  <span class="pill">${esc(L.hipBadge)}</span>
  <h1>${esc(L.title)}</h1>
  <p class="sub">${esc(when)}${data.earlyExit ? ` · ${esc(L.early)}` : ''}</p>
</header>`

  // Prefer decision near top for scannability
  return documentShell({
    lang,
    title: L.title,
    issueTitle,
    headerHtml,
    toc,
    bodyHtml: `${overviewHtml}
        ${decideHtml}
        ${processHtml}
        ${roundsHtml}
        ${edgesHtml}
        ${rolesHtml}`,
    footer: L.footer,
  })
}

function buildPersonaReport(data: RoundtableReportData, persona: PersonaId): string {
  const lang = data.language
  const L = LABELS[lang]
  const when = data.generatedAt ?? new Date().toISOString()
  const issueTitle = data.issue.replace(/\s+/g, ' ').trim().slice(0, 80)
  const name = personaLabel(persona, lang)
  const hue = PERSONA_HUE[persona]
  const edges = data.edges ?? []
  const seats = speakersInData(data)
  const labelsMap = seatLabelMap(lang, seats)

  const mySpeeches = data.rounds.flatMap((r) =>
    r.speeches
      .filter((s) => s.speaker === persona)
      .map((s) => ({ round: r.round, focus: r.focus, content: s.content })),
  )

  const myEdges = edges.filter((e) => e.from === persona || e.to === persona)
  const outRebut = edges.filter((e) => e.from === persona && e.relation === 'rebut')
  const outSupport = edges.filter((e) => e.from === persona && e.relation === 'support')
  const outQ = edges.filter((e) => e.from === persona && e.relation === 'question')
  const inRebut = edges.filter((e) => e.to === persona && e.relation === 'rebut')
  const inSupport = edges.filter((e) => e.to === persona && e.relation === 'support')
  const inQ = edges.filter((e) => e.to === persona && e.relation === 'question')
  const hasExchange =
    outRebut.length + outSupport.length + outQ.length + inRebut.length + inSupport.length + inQ.length >
    0

  const stanceParts = mySpeeches.map((s) => s.content.trim()).filter(Boolean)
  const stanceBody =
    stanceParts.length === 0
      ? L.none
      : stanceParts.length === 1
        ? stanceParts[0]!
        : stanceParts.map((p, i) => `[R${mySpeeches[i]!.round}] ${p}`).join('\n\n')

  const toc: TocItem[] = [
    { id: 'sec-stance', label: L.myStance, depth: 1 },
    { id: 'sec-speeches', label: L.mySpeeches, depth: 1 },
    { id: 'sec-exchange', label: L.edges, depth: 1 },
  ]
  if (data.decision) toc.push({ id: 'sec-decision', label: L.vsDecision, depth: 1 })

  const personalGraph =
    myEdges.length && seats.length
      ? svgDebateGraph({
          lang,
          seats,
          seatLabels: labelsMap,
          edges: myEdges,
          title: L.debateMap,
        })
      : ''

  const exchangeBlock = (
    title: string,
    list: RoundtableEdgeResult[],
    cls: string,
    peerSide: 'to' | 'from',
  ): string => {
    if (!list.length) return ''
    return `
  <div class="exchange-block ${cls}">
    <h4>${esc(title)}</h4>
    <ul class="edges">
      ${list
        .map((e) => {
          const peer = peerSide === 'to' ? e.to : e.from
          const peerName = personaName(peer, lang)
          const peerLink = (PERSONA_IDS as readonly string[]).includes(peer)
            ? fileLink(personaReportFilename(peer as PersonaId), esc(peerName))
            : esc(peerName)
          return `<li>
          <div class="edge-line">
            ${peerLink}
            <span class="rel-chip ${cls}">${esc(edgeRel(lang, e.relation))}</span>
            <span class="round-tag">R${e.round}</span>
          </div>
          ${e.summary ? `<div class="sum">${esc(e.summary)}</div>` : ''}
        </li>`
        })
        .join('\n')}
    </ul>
  </div>`
  }

  const body = `
${sectionOpen('sec-stance', L.myStance)}
  ${metricsRow([
    { label: L.mySpeeches, value: String(mySpeeches.length) },
    { label: L.metricEdges, value: String(myEdges.length) },
    { label: L.metricRebuts, value: String(outRebut.length + inRebut.length) },
  ])}
  ${collapsibleProse(stanceBody, { more: L.more, less: L.less }, 200)}
  ${backLink(L)}
</section>

${sectionOpen('sec-speeches', L.mySpeeches)}
  ${
    mySpeeches.length
      ? mySpeeches
          .map(
            (s) => `
  <article class="speech" style="--persona-h:${hue}">
    <div class="speech-head">
      <h4>${esc(roundHeading(lang, s.round))}</h4>
      <span class="round-tag">${esc(L.focus)}: ${esc(s.focus)}</span>
    </div>
    ${collapsibleProse(s.content, { more: L.more, less: L.less })}
  </article>`,
          )
          .join('\n')
      : `<p class="muted">${esc(L.none)}</p>`
  }
  ${backLink(L)}
</section>

${sectionOpen('sec-exchange', L.edges, 'diagram-card')}
  ${personalGraph}
  ${
    hasExchange
      ? `<details class="fold" style="margin-top:0.65rem" open>
    <summary><span class="more">${esc(L.detailsList)}</span><span class="less">${esc(L.less)}</span></summary>
    <div class="fold-body">
  ${exchangeBlock(L.iRebutted, outRebut, 'rebut', 'to')}
  ${exchangeBlock(L.iSupported, outSupport, 'support', 'to')}
  ${exchangeBlock(L.iQuestioned, outQ, 'question', 'to')}
  ${exchangeBlock(L.rebuttedMe, inRebut, 'rebut', 'from')}
  ${exchangeBlock(L.supportedMe, inSupport, 'support', 'from')}
  ${exchangeBlock(L.questionedMe, inQ, 'question', 'from')}
    </div>
  </details>`
      : `<p class="muted">${esc(L.noExchange)}</p>`
  }
  ${backLink(L)}
</section>

${
  data.decision
    ? `
${sectionOpen('sec-decision', L.vsDecision, 'decision')}
  <p class="decision-lead">${esc(snip(data.decision.decision, 320))}</p>
  <div class="stage-grid">
    <div class="stage-col">
      <h3>${esc(L.residual)}</h3>
      <ul>${bullets(data.decision.residual)}</ul>
    </div>
    <div class="stage-col">
      <h3>${esc(L.next)}</h3>
      <ol>${
        data.decision.nextSteps.length
          ? data.decision.nextSteps.map((x) => `<li>${esc(x)}</li>`).join('\n')
          : `<li class="muted">${esc(L.none)}</li>`
      }</ol>
    </div>
  </div>
  ${backLink(L)}
</section>`
    : ''
}`

  const headerHtml = `
<header class="report-header" style="--persona-h:${hue}">
  <div class="nav-row">
    ${fileLink(ROUNDTABLE_REPORT_FILENAME, esc(L.openMain), 'file-nav')}
  </div>
  <span class="pill role">${esc(L.roleBadge)}</span>
  <h1>${esc(L.titlePersona)} · ${esc(name)}</h1>
  <p class="sub">${esc(when)} · ${esc(snip(data.issue, 60))}</p>
</header>`

  return documentShell({
    lang,
    title: `${L.titlePersona} · ${name}`,
    issueTitle,
    headerHtml,
    toc,
    bodyHtml: body,
    footer: L.footerPersona,
  })
}

/** Build the full deliverable set: hip summary + one HTML per speaking seat. */
export function buildRoundtableReportBundle(data: RoundtableReportData): RoundtableReportFile[] {
  const seats = speakersInData(data)
  const files: RoundtableReportFile[] = [
    {
      filename: ROUNDTABLE_REPORT_FILENAME,
      html: buildMainReport(data, seats),
      kind: 'main',
    },
  ]
  for (const persona of seats) {
    files.push({
      filename: personaReportFilename(persona),
      html: buildPersonaReport(data, persona),
      kind: 'persona',
      persona,
    })
  }
  return files
}
