/**
 * Self-contained HTML reports for a convened roundtable (Chat artifact deliverables).
 *
 * Bundle:
 * - roundtable-report.html — hip summary (decision, full discussion, rebuttal map, links to roles)
 * - roundtable-report-{persona}.html — each seat's own understanding + their exchanges
 *
 * Template: fixed TOC shell, wide main pane, data-jump nav (srcDoc-safe).
 * Cross-file links are relative (work when opened in the system browser).
 */
import { personaLabel } from './prompts.js'
import type {
  PersonaId,
  RoundtableEdgeResult,
  RoundtableLang,
  SpeechRecord,
  StageRecord,
} from './types.js'
import { PERSONA_IDS } from './types.js'

export interface RoundtableReportData {
  issue: string
  language: RoundtableLang
  agenda: string[]
  rationale: string
  rounds: Array<{
    round: number
    focus: string
    speeches: SpeechRecord[]
    stage: StageRecord
  }>
  decision?: {
    decision: string
    residual: string[]
    nextSteps: string[]
  }
  edges?: RoundtableEdgeResult[]
  earlyExit?: boolean
  generatedAt?: string
}

export interface RoundtableReportFile {
  filename: string
  html: string
  kind: 'main' | 'persona'
  persona?: PersonaId
}

const LABELS: Record<
  RoundtableLang,
  {
    title: string
    titlePersona: string
    toc: string
    issue: string
    plan: string
    agenda: string
    why: string
    round: string
    focus: string
    speeches: string
    stage: string
    agreed: string
    open: string
    edges: string
    discussion: string
    rebuttals: string
    decision: string
    residual: string
    next: string
    early: string
    footer: string
    footerPersona: string
    backToTop: string
    top: string
    subReports: string
    subReportsHint: string
    openMain: string
    hipBadge: string
    roleBadge: string
    myStance: string
    mySpeeches: string
    iRebutted: string
    iSupported: string
    iQuestioned: string
    rebuttedMe: string
    supportedMe: string
    questionedMe: string
    noExchange: string
    vsDecision: string
    process: string
    seats: string
    none: string
  }
> = {
  en: {
    title: 'Roundtable report (hip summary)',
    titlePersona: 'Role report',
    toc: 'Contents',
    issue: 'Issue',
    plan: 'Meeting plan',
    agenda: 'Agenda',
    why: 'Why convened',
    round: 'Round',
    focus: 'Focus',
    speeches: 'Advisor speeches',
    stage: 'Stage conclusion (hip)',
    agreed: 'Agreed',
    open: 'Still open',
    edges: 'Debate map',
    discussion: 'Discussion process',
    rebuttals: 'Rebuttals & challenges',
    decision: 'Decision (hip)',
    residual: 'Residual disagreements',
    next: 'Next steps',
    early: 'Ended early',
    footer: 'Generated by hip roundtable',
    footerPersona: 'Role report · hip roundtable',
    backToTop: 'Back to top',
    top: 'Top',
    subReports: 'Role reports',
    subReportsHint:
      'Each role’s own reading of the debate. Open this file in a browser to follow the links; or open the matching HTML from the workspace.',
    openMain: '← Back to hip summary',
    hipBadge: 'hip summary',
    roleBadge: 'role report',
    myStance: 'How I see it',
    mySpeeches: 'My contributions',
    iRebutted: 'I challenged',
    iSupported: 'I supported',
    iQuestioned: 'I questioned',
    rebuttedMe: 'Challenged me',
    supportedMe: 'Supported me',
    questionedMe: 'Asked me',
    noExchange: 'No direct exchanges recorded for this seat.',
    vsDecision: 'Against hip’s decision',
    process: 'Discussion timeline',
    seats: 'Seats',
    none: '—',
  },
  'zh-CN': {
    title: '圆桌会议报告（hip 汇总）',
    titlePersona: '角色报告',
    toc: '目录',
    issue: '议题',
    plan: '会议规划',
    agenda: '议程',
    why: '召开原因',
    round: '第',
    focus: '焦点',
    speeches: '顾问发言',
    stage: '阶段性结论（hip）',
    agreed: '已共识',
    open: '仍开放',
    edges: '交锋图谱',
    discussion: '讨论过程',
    rebuttals: '反驳与挑战',
    decision: '决策（hip）',
    residual: '残留分歧',
    next: '后续步骤',
    early: '提前结束',
    footer: '由 hip 圆桌会议生成',
    footerPersona: '角色报告 · hip 圆桌会议',
    backToTop: '返回顶部',
    top: '顶部',
    subReports: '各角色子报告',
    subReportsHint:
      '各席位对自己立场与交锋的理解。在浏览器中打开本文件可点击跳转；也可在工作区中打开对应 HTML。',
    openMain: '← 返回 hip 汇总',
    hipBadge: 'hip 汇总',
    roleBadge: '角色报告',
    myStance: '我的理解',
    mySpeeches: '我的发言',
    iRebutted: '我反驳了',
    iSupported: '我附议了',
    iQuestioned: '我提问了',
    rebuttedMe: '反驳我的',
    supportedMe: '支持我的',
    questionedMe: '向我提问的',
    noExchange: '本席位未记录到直接交锋。',
    vsDecision: '对照 hip 决策',
    process: '讨论时间线',
    seats: '席位',
    none: '—',
  },
  'zh-TW': {
    title: '圓桌會議報告（hip 匯總）',
    titlePersona: '角色報告',
    toc: '目錄',
    issue: '議題',
    plan: '會議規劃',
    agenda: '議程',
    why: '召開原因',
    round: '第',
    focus: '焦點',
    speeches: '顧問發言',
    stage: '階段性結論（hip）',
    agreed: '已共識',
    open: '仍開放',
    edges: '交鋒圖譜',
    discussion: '討論過程',
    rebuttals: '反駁與挑戰',
    decision: '決策（hip）',
    residual: '殘留分歧',
    next: '後續步驟',
    early: '提前結束',
    footer: '由 hip 圓桌會議生成',
    footerPersona: '角色報告 · hip 圓桌會議',
    backToTop: '返回頂部',
    top: '頂部',
    subReports: '各角色子報告',
    subReportsHint:
      '各席位對自己立場與交鋒的理解。在瀏覽器中開啟本檔可點擊跳轉；也可在工作區開啟對應 HTML。',
    openMain: '← 返回 hip 匯總',
    hipBadge: 'hip 匯總',
    roleBadge: '角色報告',
    myStance: '我的理解',
    mySpeeches: '我的發言',
    iRebutted: '我反駁了',
    iSupported: '我附議了',
    iQuestioned: '我提問了',
    rebuttedMe: '反駁我的',
    supportedMe: '支持我的',
    questionedMe: '向我提問的',
    noExchange: '本席位未記錄到直接交鋒。',
    vsDecision: '對照 hip 決策',
    process: '討論時間線',
    seats: '席位',
    none: '—',
  },
  ja: {
    title: '円卓会議レポート（hip 要約）',
    titlePersona: '役割レポート',
    toc: '目次',
    issue: '議題',
    plan: '会議計画',
    agenda: 'アジェンダ',
    why: '開催理由',
    round: 'ラウンド',
    focus: '焦点',
    speeches: 'アドバイザー発言',
    stage: '段階結論 (hip)',
    agreed: '合意',
    open: '未決',
    edges: '議論マップ',
    discussion: '議論の流れ',
    rebuttals: '反論と挑戦',
    decision: '決定 (hip)',
    residual: '残る対立',
    next: '次のステップ',
    early: '早期終了',
    footer: 'hip 円卓会議が生成',
    footerPersona: '役割レポート · hip 円卓会議',
    backToTop: '先頭へ',
    top: '先頭',
    subReports: '役割別レポート',
    subReportsHint:
      '各席の理解。ブラウザで開くとリンクで移動できます。ワークスペースの HTML からも開けます。',
    openMain: '← hip 要約へ戻る',
    hipBadge: 'hip 要約',
    roleBadge: '役割',
    myStance: '私の理解',
    mySpeeches: '私の発言',
    iRebutted: '反論した相手',
    iSupported: '支持した相手',
    iQuestioned: '質問した相手',
    rebuttedMe: '私への反論',
    supportedMe: '私への支持',
    questionedMe: '私への質問',
    noExchange: '直接のやり取りは記録されていません。',
    vsDecision: 'hip 決定との対照',
    process: '議論タイムライン',
    seats: '席',
    none: '—',
  },
  ko: {
    title: '원탁 회의 보고서 (hip 요약)',
    titlePersona: '역할 보고서',
    toc: '목차',
    issue: '안건',
    plan: '회의 계획',
    agenda: '안건 목록',
    why: '소집 이유',
    round: '라운드',
    focus: '초점',
    speeches: '자문 발언',
    stage: '단계 결론 (hip)',
    agreed: '합의',
    open: '미결',
    edges: '논쟁 지도',
    discussion: '토론 과정',
    rebuttals: '반박과 도전',
    decision: '결정 (hip)',
    residual: '잔여 이견',
    next: '다음 단계',
    early: '조기 종료',
    footer: 'hip 원탁 회의 생성',
    footerPersona: '역할 보고서 · hip 원탁',
    backToTop: '맨 위로',
    top: '맨 위',
    subReports: '역할별 보고서',
    subReportsHint:
      '각 좌석의 이해. 브라우저에서 열면 링크로 이동할 수 있습니다. 작업 공간 HTML에서도 열 수 있습니다.',
    openMain: '← hip 요약으로',
    hipBadge: 'hip 요약',
    roleBadge: '역할',
    myStance: '나의 이해',
    mySpeeches: '나의 발언',
    iRebutted: '내가 반박한 대상',
    iSupported: '내가 지지한 대상',
    iQuestioned: '내가 질문한 대상',
    rebuttedMe: '나를 반박한',
    supportedMe: '나를 지지한',
    questionedMe: '나에게 질문한',
    noExchange: '직접 교환이 기록되지 않았습니다.',
    vsDecision: 'hip 결정 대비',
    process: '토론 타임라인',
    seats: '좌석',
    none: '—',
  },
}

type Labels = (typeof LABELS)[RoundtableLang]

interface TocItem {
  id: string
  label: string
  depth: 1 | 2
}

/** Soft accent per persona for cards / speech bars. */
const PERSONA_HUE: Record<PersonaId, string> = {
  strategist: '220',
  skeptic: '0',
  creative: '280',
  operator: '150',
  audience: '35',
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function proseHtml(s: string): string {
  return esc(s).replace(/\n/g, '<br/>')
}

function bullets(items: string[]): string {
  if (!items.length) return '<li class="muted">—</li>'
  return items.map((x) => `<li>${esc(x)}</li>`).join('\n')
}

function roundHeading(lang: RoundtableLang, n: number): string {
  const L = LABELS[lang]
  if (lang === 'zh-CN' || lang === 'zh-TW') return `${L.round} ${n} 轮`
  if (lang === 'ja') return `${L.round} ${n}`
  if (lang === 'ko') return `${L.round} ${n}`
  return `${L.round} ${n}`
}

function edgeRel(lang: RoundtableLang, rel: string): string {
  if (lang === 'zh-CN' || lang === 'zh-TW') {
    if (rel === 'rebut') return '反驳'
    if (rel === 'support') return '附议'
    return '提问'
  }
  if (lang === 'ja') {
    if (rel === 'rebut') return '反論'
    if (rel === 'support') return '支持'
    return '質問'
  }
  if (lang === 'ko') {
    if (rel === 'rebut') return '반박'
    if (rel === 'support') return '지지'
    return '질문'
  }
  if (rel === 'rebut') return 'rebut'
  if (rel === 'support') return 'support'
  return 'question'
}

function personaName(id: string, lang: RoundtableLang): string {
  if ((PERSONA_IDS as readonly string[]).includes(id)) {
    return personaLabel(id as PersonaId, lang)
  }
  return id
}

/** Default deliverable filename under the session cwd. */
export const ROUNDTABLE_REPORT_FILENAME = 'roundtable-report.html'

export function personaReportFilename(persona: PersonaId): string {
  return `roundtable-report-${persona}.html`
}

/** In-page jump — data-jump + script avoids srcDoc iframe hash white-screen. */
function jumpLink(id: string, label: string, className = ''): string {
  const cls = className ? ` class="${esc(className)}"` : ''
  return `<a href="#${esc(id)}" data-jump="${esc(id)}"${cls}>${label}</a>`
}

/**
 * Cross-file link. `href` works when opened in a system browser.
 * `data-file` + nav script: in hip srcDoc preview, postMessage parent instead of navigating
 * (relative href in srcDoc blanks the iframe).
 */
function fileLink(href: string, label: string, className = ''): string {
  const cls = className ? ` class="${esc(className)}"` : ''
  return `<a href="${esc(href)}" data-file="${esc(href)}"${cls}>${label}</a>`
}

function backLink(L: Labels): string {
  return `<p class="back">${jumpLink('top', esc(L.backToTop))}</p>`
}

function sectionOpen(id: string, title: string, extraClass = ''): string {
  const cls = extraClass ? ` card ${extraClass}` : ' card'
  return `<section id="${esc(id)}" class="${cls.trim()}" tabindex="-1">
  <h2>${jumpLink(id, '#', 'anchor')}${esc(title)}</h2>`
}

/**
 * Navigation script:
 * - data-jump: scroll main pane without location.hash (srcDoc-safe)
 * - data-file: when embedded (window.parent !== window), postMessage parent to open sibling HTML
 *   instead of navigating the srcDoc iframe (which blanks). Standalone browser keeps normal href.
 *
 * Message shape (must match src/components/artifact/htmlReportNav.ts):
 *   { source: 'hip-roundtable-report', type: 'open-file', file: 'roundtable-report-strategist.html' }
 */
export const ROUNDTABLE_REPORT_NAV_SCRIPT = /* js */ `
(function () {
  var main = document.getElementById('report-main');
  function jump(id) {
    if (!id) return;
    if (id === 'top') {
      if (main) main.scrollTo({ top: 0, behavior: 'smooth' });
      else window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }
    var el = document.getElementById(id);
    if (!el) return;
    if (main && main.contains(el)) {
      var top = el.getBoundingClientRect().top - main.getBoundingClientRect().top + main.scrollTop - 12;
      main.scrollTo({ top: top, behavior: 'smooth' });
    } else {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }
  function openSibling(file) {
    if (!file) return false;
    if (!window.parent || window.parent === window) return false;
    try {
      window.parent.postMessage(
        { source: 'hip-roundtable-report', type: 'open-file', file: file },
        '*'
      );
      return true;
    } catch (err) {
      return false;
    }
  }
  document.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[data-jump], a[data-file]') : null;
    if (!a) return;
    if (a.hasAttribute('data-jump')) {
      e.preventDefault();
      jump(a.getAttribute('data-jump'));
      return;
    }
    var file = a.getAttribute('data-file');
    if (file && openSibling(file)) {
      e.preventDefault();
    }
  });
})();
`.trim()

/** Shared CSS (fixed TOC + wide content + debate / role aesthetics). */
export const ROUNDTABLE_REPORT_STYLES = /* css */ `
:root {
  --bg: #0c0e12;
  --card: #151922;
  --ink: #e8eaed;
  --muted: #9aa0a6;
  --accent: #7aa2ff;
  --accent-soft: rgba(122, 162, 255, 0.14);
  --border: #2a2f3a;
  --badge: #3d2a12;
  --badge-ink: #f0c674;
  --rebut: #f07178;
  --rebut-soft: rgba(240, 113, 120, 0.12);
  --support: #7fd99a;
  --support-soft: rgba(127, 217, 154, 0.12);
  --question: #e0b45a;
  --question-soft: rgba(224, 180, 90, 0.12);
  --toc-w: 15.5rem;
  --radius: 14px;
  --shadow: 0 1px 0 rgba(255,255,255,0.03) inset;
  --glow: 0 8px 32px rgba(0,0,0,0.28);
}
@media (prefers-color-scheme: light) {
  :root {
    --bg: #eef1f6;
    --card: #ffffff;
    --ink: #1a1d23;
    --muted: #5f6368;
    --accent: #3b6ef5;
    --accent-soft: rgba(59, 110, 245, 0.1);
    --border: #e2e5eb;
    --badge: #fff4e0;
    --badge-ink: #8a5a00;
    --rebut: #c23b3b;
    --rebut-soft: rgba(194, 59, 59, 0.08);
    --support: #1a7f4b;
    --support-soft: rgba(26, 127, 75, 0.08);
    --question: #9a6b00;
    --question-soft: rgba(154, 107, 0, 0.08);
    --shadow: 0 1px 2px rgba(16, 24, 40, 0.04);
    --glow: 0 10px 28px rgba(16, 24, 40, 0.06);
  }
}
* { box-sizing: border-box; }
html, body {
  height: 100%;
  margin: 0;
  overflow: hidden;
}
body {
  font: 15px/1.6 system-ui, -apple-system, "Segoe UI", "PingFang SC", "Noto Sans SC", sans-serif;
  color: var(--ink);
  background:
    radial-gradient(1200px 600px at 10% -10%, color-mix(in srgb, var(--accent) 12%, transparent), transparent 55%),
    radial-gradient(900px 500px at 100% 0%, color-mix(in srgb, var(--support) 8%, transparent), transparent 50%),
    var(--bg);
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

.shell {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
  min-height: 0;
}
@media (min-width: 720px) {
  .shell { flex-direction: row; }
}

.toc {
  flex: 0 0 auto;
  border-bottom: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 92%, transparent);
  backdrop-filter: blur(8px);
  padding: 0.75rem 0.85rem 0.85rem;
  max-height: 38vh;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
}
@media (min-width: 720px) {
  .toc {
    width: var(--toc-w);
    min-width: var(--toc-w);
    max-width: var(--toc-w);
    max-height: none;
    height: 100%;
    border-bottom: 0;
    border-right: 1px solid var(--border);
    padding: 1rem 0.85rem 1.25rem;
  }
}
.toc-title {
  font-size: 0.72rem;
  font-weight: 700;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--muted);
  margin: 0 0 0.55rem;
  padding: 0 0.35rem;
}
.toc ol { list-style: none; margin: 0; padding: 0; }
.toc > ol > li { margin: 0; }
.toc a {
  display: block;
  padding: 0.38rem 0.5rem;
  border-radius: 8px;
  color: var(--ink);
  font-size: 0.88rem;
  line-height: 1.35;
  text-decoration: none;
  cursor: pointer;
}
.toc a:hover {
  background: var(--accent-soft);
  color: var(--accent);
  text-decoration: none;
}
.toc a:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 1px;
}
.toc .depth-2 a {
  padding-left: 1rem;
  font-size: 0.82rem;
  color: var(--muted);
}
.toc .depth-2 a:hover { color: var(--accent); }

#report-main {
  flex: 1 1 auto;
  min-width: 0;
  min-height: 0;
  overflow: auto;
  -webkit-overflow-scrolling: touch;
  width: 100%;
}
.main-inner {
  width: 100%;
  max-width: none;
  margin: 0;
  padding: 1.1rem 1.25rem 2.5rem;
}
@media (min-width: 720px) {
  .main-inner { padding: 1.35rem 1.75rem 3rem; }
}
@media (min-width: 1200px) {
  .main-inner { padding: 1.5rem 2.25rem 3rem; }
}

.report-header {
  margin-bottom: 1.25rem;
  padding: 1.15rem 1.25rem;
  border-radius: var(--radius);
  border: 1px solid var(--border);
  background: linear-gradient(135deg, color-mix(in srgb, var(--card) 88%, var(--accent-soft)), var(--card));
  box-shadow: var(--glow);
}
.report-header h1 {
  font-size: 1.55rem;
  margin: 0.35rem 0 0.35rem;
  letter-spacing: -0.02em;
  line-height: 1.25;
}
.sub { color: var(--muted); font-size: 0.85rem; margin: 0; }
.pill {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  padding: 0.18rem 0.6rem;
  border-radius: 999px;
  font-size: 0.72rem;
  font-weight: 700;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  background: var(--accent-soft);
  color: var(--accent);
  border: 1px solid color-mix(in srgb, var(--accent) 35%, var(--border));
}
.pill.role {
  background: color-mix(in srgb, hsl(var(--persona-h, 220) 55% 50%) 16%, transparent);
  color: hsl(var(--persona-h, 220) 60% 68%);
  border-color: color-mix(in srgb, hsl(var(--persona-h, 220) 55% 50%) 35%, var(--border));
}

.card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 1.15rem 1.35rem;
  margin-bottom: 0.95rem;
  box-shadow: var(--shadow);
  scroll-margin-top: 0.75rem;
}
.card.is-active { box-shadow: 0 0 0 2px var(--accent); }
.decision {
  border-color: color-mix(in srgb, var(--accent) 55%, var(--border));
  background: linear-gradient(180deg, color-mix(in srgb, var(--accent-soft) 70%, var(--card)), var(--card));
}
h2 {
  font-size: 1.12rem;
  margin: 0 0 0.75rem;
  line-height: 1.3;
  display: flex;
  align-items: baseline;
  gap: 0.35rem;
}
h2 .anchor {
  color: var(--muted);
  font-weight: 500;
  font-size: 0.9em;
  opacity: 0;
  text-decoration: none;
}
.card:hover h2 .anchor,
h2:focus-within .anchor { opacity: 0.7; }
h2 .anchor:hover { opacity: 1; color: var(--accent); }
h3 {
  font-size: 0.92rem;
  margin: 1rem 0 0.4rem;
  color: var(--muted);
  font-weight: 600;
}
h4 {
  font-size: 0.9rem;
  margin: 0 0 0.35rem;
  color: var(--accent);
}
.prose { white-space: pre-wrap; word-break: break-word; }
.lead { font-size: 1.06rem; }
.meta { color: var(--muted); margin: 0 0 0.75rem; }
ul, ol { margin: 0.25rem 0 0.75rem; padding-left: 1.2rem; }
li { margin: 0.2rem 0; }
.muted { color: var(--muted); }

.speech {
  border-left: 3px solid hsl(var(--persona-h, 220) 55% 55%);
  padding: 0.55rem 0.85rem 0.55rem 0.95rem;
  margin: 0.7rem 0;
  background: color-mix(in srgb, var(--card) 85%, hsl(var(--persona-h, 220) 40% 50%));
  border-radius: 0 10px 10px 0;
}
.speech-head {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.4rem 0.65rem;
  margin-bottom: 0.35rem;
}
.speech-head h4 { margin: 0; color: hsl(var(--persona-h, 220) 55% 68%); }
.speech a.role-link {
  font-size: 0.78rem;
  color: var(--muted);
}
.speech a.role-link:hover { color: var(--accent); }

.badge {
  display: inline-block;
  margin-top: 0.5rem;
  padding: 0.2rem 0.55rem;
  border-radius: 999px;
  background: var(--badge);
  color: var(--badge-ink);
  font-size: 0.8rem;
}

/* Debate / edges */
.edges { list-style: none; padding: 0; margin: 0; }
.edges li {
  display: grid;
  gap: 0.25rem;
  padding: 0.7rem 0.85rem;
  margin: 0.45rem 0;
  border-radius: 10px;
  border: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 90%, transparent);
}
.edge-line {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.35rem 0.45rem;
  font-size: 0.92rem;
}
.rel-chip {
  display: inline-flex;
  align-items: center;
  padding: 0.12rem 0.5rem;
  border-radius: 999px;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.02em;
}
.rel-chip.rebut {
  background: var(--rebut-soft);
  color: var(--rebut);
  border: 1px solid color-mix(in srgb, var(--rebut) 35%, var(--border));
}
.rel-chip.support {
  background: var(--support-soft);
  color: var(--support);
  border: 1px solid color-mix(in srgb, var(--support) 35%, var(--border));
}
.rel-chip.question {
  background: var(--question-soft);
  color: var(--question);
  border: 1px solid color-mix(in srgb, var(--question) 35%, var(--border));
}
.round-tag {
  color: var(--muted);
  font-size: 0.78rem;
  margin-left: 0.15rem;
  font-variant-numeric: tabular-nums;
}
.sum { color: var(--muted); font-size: 0.88rem; line-height: 1.45; }

/* Timeline */
.timeline { list-style: none; margin: 0; padding: 0 0 0 0.15rem; }
.timeline > li {
  position: relative;
  padding: 0 0 1.1rem 1.15rem;
  border-left: 2px solid color-mix(in srgb, var(--accent) 35%, var(--border));
}
.timeline > li:last-child { padding-bottom: 0; border-left-color: transparent; }
.timeline > li::before {
  content: '';
  position: absolute;
  left: -0.35rem;
  top: 0.25rem;
  width: 0.55rem;
  height: 0.55rem;
  border-radius: 50%;
  background: var(--accent);
  box-shadow: 0 0 0 3px var(--accent-soft);
}
.tl-title {
  font-weight: 650;
  margin: 0 0 0.25rem;
  font-size: 0.95rem;
}
.tl-meta { color: var(--muted); font-size: 0.85rem; margin: 0 0 0.45rem; }

/* Role gallery */
.role-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(11.5rem, 1fr));
  gap: 0.75rem;
  margin: 0.5rem 0 0.25rem;
}
.role-card {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  padding: 0.9rem 0.95rem;
  border-radius: 12px;
  border: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 88%, hsl(var(--persona-h, 220) 40% 50%));
  text-decoration: none !important;
  color: inherit;
  transition: border-color 0.15s ease, transform 0.15s ease, box-shadow 0.15s ease;
  min-height: 5.5rem;
}
.role-card:hover {
  border-color: color-mix(in srgb, hsl(var(--persona-h, 220) 55% 50%) 55%, var(--border));
  transform: translateY(-1px);
  box-shadow: var(--glow);
  text-decoration: none !important;
}
.role-card .name {
  font-weight: 700;
  font-size: 0.98rem;
  color: hsl(var(--persona-h, 220) 55% 68%);
}
.role-card .snip {
  font-size: 0.8rem;
  color: var(--muted);
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.role-card .go {
  margin-top: auto;
  font-size: 0.78rem;
  color: var(--accent);
  font-weight: 600;
}

.exchange-block {
  margin: 0.65rem 0;
  padding: 0.65rem 0.85rem;
  border-radius: 10px;
  border: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 92%, transparent);
}
.exchange-block h4 {
  margin: 0 0 0.45rem;
  font-size: 0.85rem;
  color: var(--muted);
  font-weight: 650;
  text-transform: none;
  letter-spacing: 0;
}
.exchange-block.rebut { border-color: color-mix(in srgb, var(--rebut) 30%, var(--border)); }
.exchange-block.support { border-color: color-mix(in srgb, var(--support) 30%, var(--border)); }
.exchange-block.question { border-color: color-mix(in srgb, var(--question) 30%, var(--border)); }

.back {
  margin: 0.85rem 0 0;
  font-size: 0.8rem;
}
.back a { color: var(--muted); }
.back a:hover { color: var(--accent); }
.nav-row {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem 0.85rem;
  align-items: center;
  margin-bottom: 0.35rem;
}
.nav-row a.file-nav {
  font-size: 0.85rem;
  font-weight: 600;
}
.hint {
  font-size: 0.82rem;
  color: var(--muted);
  margin: 0.35rem 0 0.75rem;
  line-height: 1.45;
}
.report-footer {
  margin-top: 1.25rem;
  padding-top: 0.75rem;
  border-top: 1px solid var(--border);
  color: var(--muted);
  font-size: 0.8rem;
}
.skip-link {
  position: absolute;
  left: -9999px;
  top: 0;
  background: var(--accent);
  color: #fff;
  padding: 0.4rem 0.7rem;
  z-index: 10;
  border-radius: 0 0 6px 0;
}
.skip-link:focus { left: 0; }
.stage-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 0.75rem;
}
@media (min-width: 800px) {
  .stage-grid { grid-template-columns: 1fr 1fr; }
}
.stage-col {
  padding: 0.65rem 0.8rem;
  border-radius: 10px;
  border: 1px solid var(--border);
  background: color-mix(in srgb, var(--card) 94%, var(--accent-soft));
}
.stage-col h3 { margin-top: 0; }
`.trim()

function speakersInData(data: RoundtableReportData): PersonaId[] {
  const seen = new Set<PersonaId>()
  for (const r of data.rounds) {
    for (const s of r.speeches) {
      if ((PERSONA_IDS as readonly string[]).includes(s.speaker)) {
        seen.add(s.speaker)
      }
    }
  }
  return PERSONA_IDS.filter((id) => seen.has(id))
}

function snip(text: string, n = 96): string {
  const t = text.replace(/\s+/g, ' ').trim()
  if (t.length <= n) return t
  return `${t.slice(0, n - 1)}…`
}

function edgeListHtml(
  edges: RoundtableEdgeResult[],
  lang: RoundtableLang,
  opts?: { linkRoles?: boolean },
): string {
  if (!edges.length) return `<p class="muted">—</p>`
  return `<ul class="edges">
    ${edges
      .map((e) => {
        const from = opts?.linkRoles
          ? fileLink(
              personaReportFilename(e.from as PersonaId),
              esc(personaName(e.from, lang)),
            )
          : esc(personaName(e.from, lang))
        const to = opts?.linkRoles
          ? fileLink(
              personaReportFilename(e.to as PersonaId),
              esc(personaName(e.to, lang)),
            )
          : esc(personaName(e.to, lang))
        const relClass =
          e.relation === 'rebut' || e.relation === 'support' || e.relation === 'question'
            ? e.relation
            : 'question'
        return `<li>
          <div class="edge-line">
            <span class="from">${from}</span>
            <span class="rel-chip ${relClass}">${esc(edgeRel(lang, e.relation))}</span>
            <span class="to">${to}</span>
            <span class="round-tag">R${e.round}</span>
          </div>
          ${e.summary ? `<div class="sum">${esc(e.summary)}</div>` : ''}
        </li>`
      })
      .join('\n')}
  </ul>`
}

function speechArticle(
  s: SpeechRecord,
  lang: RoundtableLang,
  round: number,
  opts?: { linkRole?: boolean },
): string {
  const hue = PERSONA_HUE[s.speaker] ?? '220'
  const name = personaLabel(s.speaker, lang)
  const roleHref = personaReportFilename(s.speaker)
  const link = opts?.linkRole
    ? ` ${fileLink(roleHref, lang === 'zh-CN' || lang === 'zh-TW' ? '子报告 →' : 'role report →', 'role-link')}`
    : ''
  return `
        <article class="speech" style="--persona-h:${hue}" id="sec-round-${round}-${esc(s.speaker)}">
          <div class="speech-head">
            <h4>${esc(name)}</h4>${link}
          </div>
          <div class="prose">${proseHtml(s.content)}</div>
        </article>`
}

function documentShell(args: {
  lang: RoundtableLang
  title: string
  issueTitle: string
  headerHtml: string
  toc: TocItem[]
  bodyHtml: string
  footer: string
}): string {
  const L = LABELS[args.lang]
  const tocHtml = `
<nav class="toc" id="toc" aria-label="${esc(L.toc)}">
  <p class="toc-title">${esc(L.toc)}</p>
  <ol>
    ${args.toc
      .map(
        (item) =>
          `<li class="depth-${item.depth}">${jumpLink(item.id, esc(item.label))}</li>`,
      )
      .join('\n    ')}
  </ol>
</nav>`

  return `<!DOCTYPE html>
<html lang="${esc(args.lang)}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="generator" content="hip-roundtable" />
  <title>${esc(args.title)} — ${esc(args.issueTitle)}</title>
  <style>
${ROUNDTABLE_REPORT_STYLES}
  </style>
</head>
<body>
  ${jumpLink(args.toc[0]?.id ?? 'top', esc(L.issue), 'skip-link')}
  <div class="shell" id="top">
    ${tocHtml}
    <div id="report-main">
      <div class="main-inner">
        ${args.headerHtml}
        ${args.bodyHtml}
        <footer class="report-footer">${esc(args.footer)}</footer>
      </div>
    </div>
  </div>
  <script>
${ROUNDTABLE_REPORT_NAV_SCRIPT}
  </script>
</body>
</html>
`
}

/** Build hip summary HTML (single file). */
export function buildRoundtableReportHtml(data: RoundtableReportData): string {
  return buildMainReport(data, speakersInData(data))
}

function buildMainReport(data: RoundtableReportData, seats: PersonaId[]): string {
  const lang = data.language
  const L = LABELS[lang]
  const when = data.generatedAt ?? new Date().toISOString()
  const issueTitle = data.issue.replace(/\s+/g, ' ').trim().slice(0, 80)
  const edges = data.edges ?? []
  const rebutEdges = edges.filter((e) => e.relation === 'rebut')
  const otherEdges = edges.filter((e) => e.relation !== 'rebut')

  const toc: TocItem[] = [
    { id: 'sec-issue', label: L.issue, depth: 1 },
    { id: 'sec-plan', label: L.plan, depth: 1 },
    { id: 'sec-process', label: L.process, depth: 1 },
  ]
  for (const r of data.rounds) {
    const label = roundHeading(lang, r.round)
    const focus = r.focus.trim()
    toc.push({
      id: `sec-round-${r.round}`,
      label: focus ? `${label} · ${focus.slice(0, 36)}${focus.length > 36 ? '…' : ''}` : label,
      depth: 2,
    })
  }
  if (edges.length > 0) {
    toc.push({ id: 'sec-edges', label: L.edges, depth: 1 })
    if (rebutEdges.length) {
      toc.push({ id: 'sec-rebuttals', label: L.rebuttals, depth: 2 })
    }
  }
  if (data.decision) {
    toc.push({ id: 'sec-decision', label: L.decision, depth: 1 })
  }
  if (seats.length > 0) {
    toc.push({ id: 'sec-roles', label: L.subReports, depth: 1 })
  }

  const issueHtml = `
${sectionOpen('sec-issue', L.issue)}
  <div class="prose lead">${proseHtml(data.issue)}</div>
  ${backLink(L)}
</section>`

  const planHtml = `
${sectionOpen('sec-plan', L.plan)}
  <p class="meta"><strong>${esc(L.why)}:</strong> ${esc(data.rationale || L.none)}</p>
  <h3>${esc(L.agenda)}</h3>
  <ol>${
    data.agenda.length
      ? data.agenda.map((a) => `<li>${esc(a)}</li>`).join('\n')
      : `<li class="muted">${esc(L.none)}</li>`
  }</ol>
  ${
    seats.length
      ? `<h3>${esc(L.seats)}</h3>
  <p class="meta">${seats.map((id) => esc(personaLabel(id, lang))).join(' · ')}</p>`
      : ''
  }
  ${backLink(L)}
</section>`

  const timelineItems = data.rounds
    .map((r) => {
      const nSpeeches = r.speeches.length
      const nRebut = edges.filter((e) => e.round === r.round && e.relation === 'rebut').length
      const nSupport = edges.filter((e) => e.round === r.round && e.relation === 'support').length
      const stats =
        lang === 'zh-CN' || lang === 'zh-TW'
          ? `${nSpeeches} 次发言${nRebut ? ` · ${nRebut} 次反驳` : ''}${nSupport ? ` · ${nSupport} 次附议` : ''}`
          : `${nSpeeches} speeches${nRebut ? ` · ${nRebut} rebuttals` : ''}${nSupport ? ` · ${nSupport} supports` : ''}`
      return `<li>
      <p class="tl-title">${esc(roundHeading(lang, r.round))}</p>
      <p class="tl-meta"><strong>${esc(L.focus)}:</strong> ${esc(r.focus)} · ${esc(stats)}</p>
      <p class="meta">${jumpLink(`sec-round-${r.round}`, lang === 'zh-CN' || lang === 'zh-TW' ? '查看本轮详情 →' : 'View round →')}</p>
    </li>`
    })
    .join('\n')

  const processHtml = `
${sectionOpen('sec-process', L.process, 'process')}
  <p class="hint">${esc(L.discussion)}</p>
  <ol class="timeline">
    ${timelineItems || `<li class="muted">${esc(L.none)}</li>`}
  </ol>
  ${backLink(L)}
</section>`

  const roundsHtml = data.rounds
    .map((r) => {
      const speeches = r.speeches
        .map((s) => speechArticle(s, lang, r.round, { linkRole: seats.includes(s.speaker) }))
        .join('\n')
      const roundEdges = edges.filter((e) => e.round === r.round)
      return `
${sectionOpen(`sec-round-${r.round}`, roundHeading(lang, r.round), 'round')}
  <p class="meta"><strong>${esc(L.focus)}:</strong> ${esc(r.focus)}</p>
  <h3>${esc(L.speeches)}</h3>
  <div class="speeches">${speeches || `<p class="muted">${esc(L.none)}</p>`}</div>
  ${
    roundEdges.length
      ? `<h3>${esc(L.edges)}</h3>${edgeListHtml(roundEdges, lang, { linkRoles: true })}`
      : ''
  }
  <h3>${esc(L.stage)}</h3>
  <div class="stage-grid">
    <div class="stage-col">
      <h3>${esc(L.agreed)}</h3>
      <ul>${bullets(r.stage.agreed)}</ul>
    </div>
    <div class="stage-col">
      <h3>${esc(L.open)}</h3>
      <ul>${bullets(r.stage.open)}</ul>
    </div>
  </div>
  ${
    r.stage.earlyExit
      ? `<p class="badge">${esc(L.early)}${r.stage.earlyExitReason ? `: ${esc(r.stage.earlyExitReason)}` : ''}</p>`
      : ''
  }
  ${backLink(L)}
</section>`
    })
    .join('\n')

  const edgeHint =
    lang === 'zh-CN' || lang === 'zh-TW'
      ? '箭头方向：发起方 → 关系 → 目标方。摘要来自发言中的主张与攻击点。'
      : 'Direction: actor → relation → target. Summaries come from claims and attacks in speeches.'

  const edgesHtml =
    edges.length === 0
      ? ''
      : `
${sectionOpen('sec-edges', L.edges)}
  <p class="hint">${esc(edgeHint)}</p>
  ${otherEdges.length ? edgeListHtml(otherEdges, lang, { linkRoles: true }) : ''}
  ${
    rebutEdges.length
      ? `
  <div id="sec-rebuttals" tabindex="-1">
    <h3>${esc(L.rebuttals)}</h3>
    ${edgeListHtml(rebutEdges, lang, { linkRoles: true })}
  </div>`
      : ''
  }
  ${backLink(L)}
</section>`

  const decide = data.decision
  const decideHtml = decide
    ? `
${sectionOpen('sec-decision', L.decision, 'decision')}
  <div class="prose lead">${proseHtml(decide.decision)}</div>
  <h3>${esc(L.residual)}</h3>
  <ul>${bullets(decide.residual)}</ul>
  <h3>${esc(L.next)}</h3>
  <ol>${
    decide.nextSteps.length
      ? decide.nextSteps.map((x) => `<li>${esc(x)}</li>`).join('\n')
      : `<li class="muted">${esc(L.none)}</li>`
  }</ol>
  ${data.earlyExit ? `<p class="badge">${esc(L.early)}</p>` : ''}
  ${backLink(L)}
</section>`
    : ''

  const openLabel = lang === 'zh-CN' || lang === 'zh-TW' ? '打开子报告 →' : 'Open →'
  const rolesHtml =
    seats.length === 0
      ? ''
      : `
${sectionOpen('sec-roles', L.subReports)}
  <p class="hint">${esc(L.subReportsHint)}</p>
  <div class="role-grid">
    ${seats
      .map((id) => {
        const hue = PERSONA_HUE[id]
        const first =
          data.rounds
            .flatMap((r) => r.speeches)
            .find((s) => s.speaker === id)?.content ?? ''
        const href = personaReportFilename(id)
        return `<a class="role-card" style="--persona-h:${hue}" href="${esc(href)}" data-file="${esc(href)}">
      <span class="name">${esc(personaLabel(id, lang))}</span>
      <span class="snip">${esc(snip(first, 110) || L.none)}</span>
      <span class="go">${esc(openLabel)}</span>
    </a>`
      })
      .join('\n    ')}
  </div>
  ${backLink(L)}
</section>`

  const headerHtml = `
<header class="report-header">
  <span class="pill">${esc(L.hipBadge)}</span>
  <h1>${esc(L.title)}</h1>
  <p class="sub">${esc(when)}${data.earlyExit ? ` · ${esc(L.early)}` : ''}</p>
</header>`

  return documentShell({
    lang,
    title: L.title,
    issueTitle,
    headerHtml,
    toc,
    bodyHtml: `${issueHtml}
        ${planHtml}
        ${processHtml}
        ${roundsHtml}
        ${edgesHtml}
        ${decideHtml}
        ${rolesHtml}`,
    footer: L.footer,
  })
}

function buildPersonaReport(data: RoundtableReportData, persona: PersonaId): string {
  const lang = data.language
  const L = LABELS[lang]
  const when = data.generatedAt ?? new Date().toISOString()
  const issueTitle = data.issue.replace(/\s+/g, ' ').trim().slice(0, 80)
  const name = personaLabel(persona, lang)
  const hue = PERSONA_HUE[persona]
  const edges = data.edges ?? []

  const mySpeeches = data.rounds.flatMap((r) =>
    r.speeches
      .filter((s) => s.speaker === persona)
      .map((s) => ({ round: r.round, focus: r.focus, content: s.content })),
  )

  const outRebut = edges.filter((e) => e.from === persona && e.relation === 'rebut')
  const outSupport = edges.filter((e) => e.from === persona && e.relation === 'support')
  const outQ = edges.filter((e) => e.from === persona && e.relation === 'question')
  const inRebut = edges.filter((e) => e.to === persona && e.relation === 'rebut')
  const inSupport = edges.filter((e) => e.to === persona && e.relation === 'support')
  const inQ = edges.filter((e) => e.to === persona && e.relation === 'question')
  const hasExchange =
    outRebut.length + outSupport.length + outQ.length + inRebut.length + inSupport.length + inQ.length >
    0

  const stanceParts = mySpeeches.map((s) => s.content.trim()).filter(Boolean)
  const stanceBody =
    stanceParts.length === 0
      ? L.none
      : stanceParts.length === 1
        ? stanceParts[0]!
        : stanceParts.map((p, i) => `[R${mySpeeches[i]!.round}] ${p}`).join('\n\n')

  const toc: TocItem[] = [
    { id: 'sec-stance', label: L.myStance, depth: 1 },
    { id: 'sec-speeches', label: L.mySpeeches, depth: 1 },
    { id: 'sec-exchange', label: L.edges, depth: 1 },
  ]
  if (data.decision) {
    toc.push({ id: 'sec-decision', label: L.vsDecision, depth: 1 })
  }

  const exchangeBlock = (
    title: string,
    list: RoundtableEdgeResult[],
    cls: string,
    peerSide: 'to' | 'from',
  ): string => {
    if (!list.length) return ''
    return `
  <div class="exchange-block ${cls}">
    <h4>${esc(title)}</h4>
    <ul class="edges">
      ${list
        .map((e) => {
          const peer = peerSide === 'to' ? e.to : e.from
          const peerName = personaName(peer, lang)
          const peerLink = (PERSONA_IDS as readonly string[]).includes(peer)
            ? fileLink(personaReportFilename(peer as PersonaId), esc(peerName))
            : esc(peerName)
          return `<li>
          <div class="edge-line">
            ${peerLink}
            <span class="rel-chip ${cls}">${esc(edgeRel(lang, e.relation))}</span>
            <span class="round-tag">R${e.round}</span>
          </div>
          ${e.summary ? `<div class="sum">${esc(e.summary)}</div>` : ''}
        </li>`
        })
        .join('\n')}
    </ul>
  </div>`
  }

  const body = `
${sectionOpen('sec-stance', L.myStance)}
  <div class="prose lead">${proseHtml(stanceBody)}</div>
  ${backLink(L)}
</section>

${sectionOpen('sec-speeches', L.mySpeeches)}
  ${
    mySpeeches.length
      ? mySpeeches
          .map(
            (s) => `
  <article class="speech" style="--persona-h:${hue}">
    <div class="speech-head">
      <h4>${esc(roundHeading(lang, s.round))}</h4>
      <span class="round-tag">${esc(L.focus)}: ${esc(s.focus)}</span>
    </div>
    <div class="prose">${proseHtml(s.content)}</div>
  </article>`,
          )
          .join('\n')
      : `<p class="muted">${esc(L.none)}</p>`
  }
  ${backLink(L)}
</section>

${sectionOpen('sec-exchange', L.edges)}
  ${
    hasExchange
      ? `${exchangeBlock(L.iRebutted, outRebut, 'rebut', 'to')}
  ${exchangeBlock(L.iSupported, outSupport, 'support', 'to')}
  ${exchangeBlock(L.iQuestioned, outQ, 'question', 'to')}
  ${exchangeBlock(L.rebuttedMe, inRebut, 'rebut', 'from')}
  ${exchangeBlock(L.supportedMe, inSupport, 'support', 'from')}
  ${exchangeBlock(L.questionedMe, inQ, 'question', 'from')}`
      : `<p class="muted">${esc(L.noExchange)}</p>`
  }
  ${backLink(L)}
</section>

${
  data.decision
    ? `
${sectionOpen('sec-decision', L.vsDecision, 'decision')}
  <div class="prose lead">${proseHtml(data.decision.decision)}</div>
  <h3>${esc(L.residual)}</h3>
  <ul>${bullets(data.decision.residual)}</ul>
  <h3>${esc(L.next)}</h3>
  <ol>${
    data.decision.nextSteps.length
      ? data.decision.nextSteps.map((x) => `<li>${esc(x)}</li>`).join('\n')
      : `<li class="muted">${esc(L.none)}</li>`
  }</ol>
  ${backLink(L)}
</section>`
    : ''
}`

  const headerHtml = `
<header class="report-header" style="--persona-h:${hue}">
  <div class="nav-row">
    ${fileLink(ROUNDTABLE_REPORT_FILENAME, esc(L.openMain), 'file-nav')}
  </div>
  <span class="pill role">${esc(L.roleBadge)}</span>
  <h1>${esc(L.titlePersona)} · ${esc(name)}</h1>
  <p class="sub">${esc(when)} · ${esc(snip(data.issue, 60))}</p>
</header>`

  return documentShell({
    lang,
    title: `${L.titlePersona} · ${name}`,
    issueTitle,
    headerHtml,
    toc,
    bodyHtml: body,
    footer: L.footerPersona,
  })
}

/**
 * Build the full deliverable set: hip summary + one HTML per speaking seat.
 */
export function buildRoundtableReportBundle(data: RoundtableReportData): RoundtableReportFile[] {
  const seats = speakersInData(data)
  const files: RoundtableReportFile[] = [
    {
      filename: ROUNDTABLE_REPORT_FILENAME,
      html: buildMainReport(data, seats),
      kind: 'main',
    },
  ]
  for (const persona of seats) {
    files.push({
      filename: personaReportFilename(persona),
      html: buildPersonaReport(data, persona),
      kind: 'persona',
      persona,
    })
  }
  return files
}
